### ISSUE TITLE
pip install horovod fails with error: Unable to determine CXX11 ABI to use with TensorFlow

### ISSUE THREAD

**Issue by ksasi** [uber/horovod#101]
Hi,

sasikanthkotti$ pip install horovod on mac fails as below : 

Collecting horovod
  Using cached horovod-0.11.0.tar.gz
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod ... error
  Complete output from command /anaconda2/envs/Tensorflow_Python3_6/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-build-l5wzzk3m/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/24/sln_smf506j41c593wqcmm180000gn/T/tmpuadcilgepip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.6
  creating build/lib.macosx-10.7-x86_64-3.6/horovod
  copying horovod/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod
  creating build/lib.macosx-10.7-x86_64-3.6/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/keras
  creating build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops_test.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
  running build_ext
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o
  gcc -bundle -undefined dynamic_lookup -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o -L/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/core -L/anaconda2/envs/Tensorflow_Python3_6/lib -ltensorflow_framework -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.so
  ld: library not found for -ltensorflow_framework
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o
  gcc -bundle -undefined dynamic_lookup -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o -L/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/core -L/anaconda2/envs/Tensorflow_Python3_6/lib -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.so
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.o
  In file included from build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc:2:
  /anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:20:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 error generated.
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.o
  In file included from build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc:2:
  /anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:20:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: Unable to determine CXX11 ABI to use with TensorFlow (see error above).

  ----------------------------------------
  Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /anaconda2/envs/Tensorflow_Python3_6/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-build-l5wzzk3m/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-7s3cvoih-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/horovod
    copying horovod/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod
    creating build/lib.macosx-10.7-x86_64-3.6/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/keras
    creating build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.macosx-10.7-x86_64-3.6/horovod/tensorflow
    running build_ext
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o
    gcc -bundle -undefined dynamic_lookup -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o -L/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/core -L/anaconda2/envs/Tensorflow_Python3_6/lib -ltensorflow_framework -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.so
    ld: library not found for -ltensorflow_framework
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o
    gcc -bundle -undefined dynamic_lookup -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -L/anaconda2/envs/Tensorflow_Python3_6/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.o -L/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/core -L/anaconda2/envs/Tensorflow_Python3_6/lib -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_libs.so
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.o
    In file included from build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc:2:
    /anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:20:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -I/anaconda2/envs/Tensorflow_Python3_6/include -arch x86_64 -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=1 -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include -I/anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/external/nsync/public -I/anaconda2/envs/Tensorflow_Python3_6/include/python3.6m -c build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc -o build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.o
    In file included from build/temp.macosx-10.7-x86_64-3.6/test_compile/test_tensorflow_abi.cc:2:
    /anaconda2/envs/Tensorflow_Python3_6/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/op.h:20:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 error generated.
    error: Unable to determine CXX11 ABI to use with TensorFlow (see error above).

    ----------------------------------------
Command "/anaconda2/envs/Tensorflow_Python3_6/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-build-l5wzzk3m/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-7s3cvoih-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/24/sln_smf506j41c593wqcmm180000gn/T/pip-build-l5wzzk3m/horovod/

Details : 
OS : macOS High Sierra Version 10.13.1
Open MPI: 3.0.0

Please advice.

Thanks and Regards,
Sasikanth

**Comment by alsrgv** [comment]
@ksasi, could you try to add `CFLAGS=-stdlib=libc++` in front of your `pip install horovod`?

**Comment by ksasi** [comment]
Adding the flag CFLAGS=-stdlib=libc++ in front of your pip install horovod, seems to have helped. Below is the output : 

CFLAGS=-stdlib=libc++ pip install horovod
Collecting horovod
  Using cached horovod-0.11.0.tar.gz
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod ... done
  Stored in directory: /Users/sasikanthkotti/Library/Caches/pip/wheels/20/1e/24/2e9619fed60caccab50730f226c9972f503090efc2adb231bc
Successfully built horovod
Installing collected packages: horovod
Successfully installed horovod-0.11.0

Thanks and Regards,
Sasikanth

**Comment by ruanchong** [comment]
@alsrgv helped.

**Comment by denfromufa** [comment]
With ppc64 compiler installed with conda I'm getting this error after enabling this CFLAGS:

`powerpc64le-conda_cos7-linux-gnu-cc: error: unrecognized command line option '-stdlib=libc++'`

**Comment by denfromufa** [comment]
Oh, I see pardon, I'm using GCC not Clang. Might be a different issue with the same error:

```
anaconda3/envs/powerai.1.6.1/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework/step_stats.pb.h:1466:23: note: suggested alternative: 'GOOGLE_DLOG'
       scheduled_micros_ = GOOGLE_LONGLONG(0);
                           ^~~~~~~~~~~~~~~
                           GOOGLE_DLOG
    error: Unable to determine CXX11 ABI to use with TensorFlow (see error above).
```

**Comment by alsrgv** [comment]
@denfromufa, can you open a new issue for this?  Or is it #1165?

**Comment by denfromufa** [comment]
@alsrgv the issue is not relevant anymore, horovod builds ok with gcc 7.3 from conda in powerai 1.6/1.6.1 and with either smpi 10.1+ or openmpi 4.0.1.
