### ISSUE TITLE
Unable to run the HOROVOD framework

### ISSUE THREAD

**Issue by abidmalik1967** [uber/horovod#103]
I am using Ubuntu machine for the framework and got the following error.

import tensorflow as tf
>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amalik/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 34, in <module>
    from horovod.tensorflow.mpi_ops import size
  File "/home/amalik/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 74, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/amalik/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 56, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/amalik/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/amalik/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE
>>> 

Any suggestions!!!

**Comment by alsrgv** [comment]
Hi @abidmalik1967,

Can you uninstall Horovod, reinstall with `-v` flag added at the end of `pip install` command, and paste the logs?  I want to understand all the compilation flags that were used.

Also, can you share the way you installed TensorFlow in this environment?

Lastly, is it an option for you to use a plain `virtualenv`?

Thanks,
Alex

**Comment by zxw866** [comment]
I have the same problem. The logs :
HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod -v
Collecting horovod
  1 location(s) to search for versions of horovod:
  * https://pypi.python.org/simple/horovod/
  Getting page https://pypi.python.org/simple/horovod/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/horovod/ HTTP/1.1" 200 1543
  Analyzing links from page https://pypi.python.org/simple/horovod/
    Found link https://pypi.python.org/packages/07/bb/f2edeee902a6c5e345f5cc6d8ba3f5b6805506489da4bb6cf35665cccd95/horovod-0.9.5.tar.gz#md5=a883937ed44f95a98b434a3c13178aa0 (from https://pypi.python.org/simple/horovod/), version: 0.9.5
    Found link https://pypi.python.org/packages/11/48/e56cb33974a7fc24252e304e7e60b7b892eb7c1093099493913880b6f4ce/horovod-0.9.8.tar.gz#md5=e981a37f7ee6c1f4ba5dcac637184e7a (from https://pypi.python.org/simple/horovod/), version: 0.9.8
    Found link https://pypi.python.org/packages/2c/c4/cd8d9d1136465e6f23a535cc4c49fad24da92982f1275d7c38a564d5417b/horovod-0.9.9.tar.gz#md5=1d680e9ffe37552f4510c29e0fcfefc3 (from https://pypi.python.org/simple/horovod/), version: 0.9.9
    Found link https://pypi.python.org/packages/58/8d/6a84cd3fa9bdeb96e6c162d26d05c6e594c38f788005f2d2f42ed2bfcfe5/horovod-0.9.1.tar.gz#md5=277e9c1bc7b459a49eb1aca7731ca5bd (from https://pypi.python.org/simple/horovod/), version: 0.9.1
    Found link https://pypi.python.org/packages/5c/cd/a5775db7c3e78b255be107089924f2d05293e507266341e3c9e895811b70/horovod-0.11.2.tar.gz#md5=ed574831ba2c4a2c83f2f7456184b8b3 (from https://pypi.python.org/simple/horovod/), version: 0.11.2
    Found link https://pypi.python.org/packages/6f/88/ad4124c8a0e12ab8b0b32547db6d5477ce21510b09b95d586a927e3427bf/horovod-0.11.1.tar.gz#md5=7fb9237720eb32acfa7665cfd195adb7 (from https://pypi.python.org/simple/horovod/), version: 0.11.1
    Found link https://pypi.python.org/packages/7a/f6/c550b90424136eef13a20527c815778c67d222ec2807e2b526758e5a55f9/horovod-0.9.12.tar.gz#md5=4a337f7a46de2f7551544d9040789de0 (from https://pypi.python.org/simple/horovod/), version: 0.9.12
    Found link https://pypi.python.org/packages/7e/49/5c6b766e2b8071dfce493969332041d1a1210501d44b32f9289f1ecf3b8d/horovod-0.10.1.tar.gz#md5=362a75690be26da95468dbbae49ee67d (from https://pypi.python.org/simple/horovod/), version: 0.10.1
    Found link https://pypi.python.org/packages/7f/78/3c42b58fa37d5811eb2178e6d8f0e586b18fd883f8575a2da8a7bce9b02b/horovod-0.9.4.tar.gz#md5=d436ab4b0efa0734f270f4ba24d1d665 (from https://pypi.python.org/simple/horovod/), version: 0.9.4
    Found link https://pypi.python.org/packages/81/3b/d4cd7933a1b25dbb6f6a3e4f7e23b1519596c470d2cde5956818f903ac21/horovod-0.9.11.tar.gz#md5=6479832b37ab2971b032e17e5ed4be6f (from https://pypi.python.org/simple/horovod/), version: 0.9.11
    Found link https://pypi.python.org/packages/8a/82/085978898e51938791c35949fb757905e746503369e898074f76f6044d32/horovod-0.9.3.tar.gz#md5=4f4dd52b7763ec7d2da0da55ad04aeff (from https://pypi.python.org/simple/horovod/), version: 0.9.3
    Found link https://pypi.python.org/packages/8c/91/91495a609f7b4077ba4eeb00c8494bf29eb94de76e5a7a458cf57add7f0e/horovod-0.9.0.tar.gz#md5=1cd031e8d892cab8e2cf05cfe2caba55 (from https://pypi.python.org/simple/horovod/), version: 0.9.0
    Found link https://pypi.python.org/packages/9c/62/3d37b3697a06e0c5ef97fd01f690f4b94509486df4f5401a65461e110d1c/horovod-0.9.7.tar.gz#md5=42c02e8e117303e35744fdce39d79ac5 (from https://pypi.python.org/simple/horovod/), version: 0.9.7
    Found link https://pypi.python.org/packages/9c/be/5aebe7ecd7024e0ad12196127d22488a73defa3c1b6fac0eea20d7aa6115/horovod-0.9.6.tar.gz#md5=bc4ae17e261dffef0b9ce1e125336a75 (from https://pypi.python.org/simple/horovod/), version: 0.9.6
    Found link https://pypi.python.org/packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz#md5=694ca17e718cd3d62831e23dbf1f5437 (from https://pypi.python.org/simple/horovod/), version: 0.9.10
    Found link https://pypi.python.org/packages/c3/86/c4bab0bccbd5001503e242e7c6b2dd2d4cbef1089775b8008983b410bd73/horovod-0.10.0.tar.gz#md5=349f01f4a98642351e8f8fe1b777d260 (from https://pypi.python.org/simple/horovod/), version: 0.10.0
    Found link https://pypi.python.org/packages/d7/83/b1118fc1e2e55394a4b58c293b6a679b047cd46e2559ae9b79e3f2633610/horovod-0.11.0.tar.gz#md5=e2172125615b72d8d67c27bb9a486529 (from https://pypi.python.org/simple/horovod/), version: 0.11.0
    Found link https://pypi.python.org/packages/dc/e3/7fd51f21e287ae2cdf21d5a6534e59faf9852a0ef70f43164896c92b44e7/horovod-0.11.3.tar.gz#md5=5253672835b536d7d1e5b1d63b28f969 (from https://pypi.python.org/simple/horovod/), version: 0.11.3
    Found link https://pypi.python.org/packages/f2/ce/ebc0a4321b3475932543d425f14102fc86ef803be2d1a545ac3297a8e5f4/horovod-0.10.2.tar.gz#md5=ea0e5bde6195def0f47c8387c0d21ffd (from https://pypi.python.org/simple/horovod/), version: 0.10.2
    Found link https://pypi.python.org/packages/fc/53/314d19c558f726e480489e97d576883b6bd79b7d811913216b30d7849b8b/horovod-0.9.2.tar.gz#md5=804dbcd20c1de82c7adb5213c4d0363c (from https://pypi.python.org/simple/horovod/), version: 0.9.2
  Using version 0.11.3 (newest of versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.11.1, 0.11.2, 0.11.3)
  "GET /packages/dc/e3/7fd51f21e287ae2cdf21d5a6534e59faf9852a0ef70f43164896c92b44e7/horovod-0.11.3.tar.gz HTTP/1.1" 200 72777
  Downloading horovod-0.11.3.tar.gz (72kB)
  Downloading from URL https://pypi.python.org/packages/dc/e3/7fd51f21e287ae2cdf21d5a6534e59faf9852a0ef70f43164896c92b44e7/horovod-0.11.3.tar.gz#md5=5253672835b536d7d1e5b1d63b28f969 (from https://pypi.python.org/simple/horovod/)
    100% |████████████████████████████████| 81kB 104kB/s
  Running setup.py (path:/tmp/pip-build-7Tqf7b/horovod/setup.py) egg_info for package horovod
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/horovod.egg-info
    writing pip-egg-info/horovod.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/horovod.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/horovod.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-7Tqf7b/horovod has version 0.11.3, which satisfies requirement horovod from https://pypi.python.org/packages/dc/e3/7fd51f21e287ae2cdf21d5a6534e59faf9852a0ef70f43164896c92b44e7/horovod-0.11.3.tar.gz#md5=5253672835b536d7d1e5b1d63b28f969
Installing collected packages: horovod
  Running setup.py install for horovod ...     Running command /home/xwzhang/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7Tqf7b/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2SGgk2-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    running build_ext
    /home/xwzhang/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
      from ._conv import register_converters as _register_converters
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/home/xwzhang/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -L/home/xwzhang/anaconda2/lib -Wl,-rpath=/home/xwzhang/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -L/home/xwzhang/anaconda2/lib -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/home/xwzhang/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cuda.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -L/home/xwzhang/anaconda2/lib -Wl,-rpath=/home/xwzhang/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/home/xwzhang/anaconda2/lib -lcudart -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -I/usr/local/cuda/include -I/home/xwzhang/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_nccl.cc -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -L/home/xwzhang/anaconda2/lib -Wl,-rpath=/home/xwzhang/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_nccl.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/home/xwzhang/anaconda2/lib -lnccl -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.so
    building 'horovod.tensorflow.mpi_lib' extension
    creating build/temp.linux-x86_64-2.7/horovod
    creating build/temp.linux-x86_64-2.7/horovod/tensorflow
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/local/cuda/include -I/home/xwzhang/anaconda2/include/python2.7 -c horovod/tensorflow/mpi_message.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_message.o -std=c++11 -fPIC -O2 -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/local/cuda/include -I/home/xwzhang/anaconda2/include/python2.7 -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/local/cuda/include -I/home/xwzhang/anaconda2/include/python2.7 -c horovod/tensorflow/timeline.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/timeline.o -std=c++11 -fPIC -O2 -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    g++ -pthread -shared -L/home/xwzhang/anaconda2/lib -Wl,-rpath=/home/xwzhang/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_message.o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o build/temp.linux-x86_64-2.7/horovod/tensorflow/timeline.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/home/xwzhang/anaconda2/lib -lcudart -lnccl -lpython2.7 -o build/lib.linux-x86_64-2.7/horovod/tensorflow/mpi_lib.so -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -L/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow -ltensorflow_framework
    running install_lib
    creating /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod
    copying build/lib.linux-x86_64-2.7/horovod/__init__.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod
    creating /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-2.7/horovod/tensorflow/__init__.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-2.7/horovod/tensorflow/mpi_lib.so -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow
    copying build/lib.linux-x86_64-2.7/horovod/tensorflow/mpi_ops_test.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow
    creating /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/keras
    copying build/lib.linux-x86_64-2.7/horovod/keras/__init__.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/keras
    copying build/lib.linux-x86_64-2.7/horovod/keras/callbacks.py -> /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/keras
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/__init__.py to __init__.pyc
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py to __init__.pyc
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py to mpi_ops.pyc
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops_test.py to mpi_ops_test.pyc
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/keras/__init__.py to __init__.pyc
    byte-compiling /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/keras/callbacks.py to callbacks.pyc
    running install_egg_info
    running egg_info
    writing horovod.egg-info/PKG-INFO
    writing top-level names to horovod.egg-info/top_level.txt
    writing dependency_links to horovod.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'horovod.egg-info/SOURCES.txt'
    Copying horovod.egg-info to /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod-0.11.3-py2.7.egg-info
    running install_scripts
    writing list of installed files to '/tmp/pip-2SGgk2-record/install-record.txt'
done
  Removing source in /tmp/pip-build-7Tqf7b/horovod
Successfully installed horovod-0.11.3
Cleaning up...

Any suggestions ?

Thanks !

**Comment by alsrgv** [comment]
@zxw866, can you paste the exact error you're getting?

**Comment by zxw866** [comment]
>>> import horovod.tensorflow
/home/xwzhang/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/__init__.py", line 34, in <module>
    from horovod.tensorflow.mpi_ops import size
  File "/home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 74, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_ops.py", line 56, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/xwzhang/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/xwzhang/anaconda2/lib/python2.7/site-packages/horovod/tensorflow/mpi_lib.so: undefined symbol: _ZNSt6thread15_M_start_threadESt10shared_ptrINS_10_Impl_baseEEPFvvE

**Comment by alsrgv** [comment]
Can you try suggestions from https://stackoverflow.com/questions/41096313/pyopencl-import-error-cffi-so-undefined-symbol?answertab=votes#tab-top ?

**Comment by zxw866** [comment]
It works! 
Appreciate your help!

**Comment by rvallari1** [comment]
I got the same error.

>>> import horovod.tensorflow as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/intel/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 43, in <module>
    from horovod.tensorflow.mpi_ops import allgather
  File "/home/intel/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 57, in <module>
    ['HorovodAllgather', 'HorovodAllreduce'])
  File "/home/intel/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 44, in _load_library
    library = load_library.load_op_library(filename)
  File "/home/intel/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/intel/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow8OpKernel4nameB5cxx11Ev



So, I followed the same steps as given in this link:  https://stackoverflow.com/questions/41096313/pyopencl-import-error-cffi-so-undefined-symbol?answertab=votes#tab-top

Then , this error came: https://github.com/horovod/horovod/issues/406

I installed Horovod through this command : conda install -c engility/label/broken horovod
And install using openmpi-4.0.0 INSTALL

**Comment by alsrgv** [comment]
@rvallari1, can you try installing GCC7 in your Conda environment?
```
$ conda install gcc_linux-64 gxx_linux-64
```

**Comment by rvallari1** [comment]
Tried this too as mentioned here : https://github.com/horovod/horovod/issues/656#issuecomment-487244627
Problem still exists. Can you explain how flags to be used in the command.

**Comment by alsrgv** [comment]
@rvallari1, could you share the full installation log using [Gist](https://gist.github.com)?

**Comment by rvallari1** [comment]
@alsrgv Solved it, earlier using NUC7i7bnb..
