### ISSUE TITLE
horovod hangs on hvd.init() with mpirun to multiple hosts

### ISSUE THREAD

**Issue by chenglinzhang** [uber/horovod#111]
Horovod 0.11.1 (HOROVOD_GPU_*=MPI pip install with no-cache)
OpenMPI  (3.0 with cuda 8 support)
NCCL2 not available
Tensorflow 1.2
Python 3.6

Command line:
mpirun -mca btl_tcp_if_exclude docker0 -np 4 -bind-to none -oversubscribe -H host1:2,host2:2 python3 tensorflow_mnist.py

It runs fine on a single host with GPUs, e.g., host1:2 or host2:2. Here tensorflow_mnist.py is a horovod example. 

Every tensorflow_mnist.py instance hangs in hvd.init() if running on multiple hosts. For debug, I added a print() statement before and after hvd.init(). 

Any help will be appreciated.

**Comment by alsrgv** [comment]
@chenglinzhang, do you get any output if you let it run for a longer time, e.g. 10 minutes?

**Comment by alsrgv** [comment]
@chenglinzhang, another idea discovered in #110 is to try to manually `ssh host2` from `host1` and if it prompts to confirm identity, say `yes`.

**Comment by chenglinzhang** [comment]
Thanks for the quick response. Password-less ssh has been enabled from host1 to host2 and vise versa. I can run hello_c and ring_c tests for example with mpirun on host1:2,host2:2.

**Comment by chenglinzhang** [comment]
There was no output when it was let run more than 30 minutes.

**Comment by alsrgv** [comment]
@chenglinzhang, gotcha. Can you make a gist with the full output of `strace -f -e 'trace=!poll' mpirun ...`? It helped to find an ssh issue last time.

**Comment by chenglinzhang** [comment]
Problem solved. Horovod was installed to host2 with an older version of MPI. A reinstallation with MPI 3.0 resolved the problem.  Thanks.
