### ISSUE TITLE
horovod's work pattern? 

### ISSUE THREAD

**Issue by qiang13568** [uber/horovod#117]
1. single server single GPU
2. single server multiple GPUS
3. multiple servers single GPU   (servers cluster but single GPU each server)
4. multiple servers multiple GPUS (servers cluster and multiple GPUs each server)

I have been wondering which one is right? Two pictures below are from official document, i am puzzled.

![image](https://user-images.githubusercontent.com/18524705/33643082-0924a546-da78-11e7-8075-9bc77cce7561.png)

![image](https://user-images.githubusercontent.com/18524705/33643174-6ba3b004-da78-11e7-8408-e8a8e2cb842e.png)

**Comment by alsrgv** [comment]
@qiang13568, all four are valid use cases for Horovod.  The quote you mentioned refers to another dimension - how many GPUs each **worker** will utilize?  In most cases, the model would fit on one GPU, and so most of the examples are currently focused on that.

However, it's possible with Horovod to split the model across multiple GPUs with a server, and then do an `allreduce` among servers.  This was discussed a bit in #96.

**Comment by qiang13568** [comment]
@alsrgv thanks for your reply sincerely. According to your answer, can I  think of multiple servers with single GPU each as mainstream, but multiple servers with multiple GPUs each can be easily implemented?

And another question, which situation horovod is  used more usually?

**Comment by alsrgv** [comment]
@qiang13568, one GPU per worker process is mainstream with servers having one or multiple GPUs.  Tricks described in #96 to support models that don't fit single GPU are not mainstream but supported.

**Comment by qiang13568** [comment]
@alsrgv thank you very much！

**Comment by alsrgv** [comment]
I'll close this issue as it appears to be resolved.
