### ISSUE TITLE
Is there some schemes about different GPUs?

### ISSUE THREAD

**Issue by jinzequn** [uber/horovod#121]
For example , I have 4 GTX1080 and 4 GTX1070,  horovod could set different batch size or something else to handle this situations?

**Comment by alsrgv** [comment]
@jinzequn, if you run Horovod with `mpirun` like this: `mpirun -np 8 -H srv-gtx1080:4,srv-gtx1070:4 ... python train.py`, then first four ranks `hvd.rank() == [0..3]` will correspond to GTX1080, and `hvd.rank() == [4..7]` will correspond to GTX1070.  You can then adjust batch size with an if statement.

Your effective batch size will be a sum of batch sizes on all GPUs.  E.g. if your batch size on GTX1080 is 64 and on GTX1070 is 32, then your effective batch size will be 64\*4+32\*4 = 384.

**Comment by jinzequn** [comment]
OK, is that means I have to set it by myself, horovod couldn't adapt different GPUs?

**Comment by alsrgv** [comment]
@jinzequn, that's right.  Horovod doesn't know which GPUs have how much memory and what are appropriate batch sizes.

**Comment by jinzequn** [comment]
@alsrgv I get that, thanks a lot
