### ISSUE TITLE
Horovod sends `model.predict` to all the GPUs  instead of 1 !

### ISSUE THREAD

**Issue by SrivastavaKshitij** [uber/horovod#122]
Hi @alsrgv 

I am scaling my training process to 8 nodes (32 GPUs). After the training is complete, and I want the model to predict the output on the test set so that I can calculate F-scores, it sends the data to all the GPUs and calculates 32 F-scores. Could you please let me know how can I make sure that it calculates just one final F score ?

![screen shot 2017-12-12 at 10 55 12 am](https://user-images.githubusercontent.com/19312052/33894262-870af548-df2b-11e7-980b-f395c2fd4343.png)

**Comment by alsrgv** [comment]
Hi @SrivastavaKshitij,

If I understand your question correctly, you can just add an `if` statement around prediction code to predict is only on first GPU, like this:
```python
if hvd.rank() == 0:
  # prediction code
  ...
  # print f1 scores
```

**Comment by SrivastavaKshitij** [comment]
Yes, thank you. thats the correct solution. Somehow I overlooked  the solution.. Thanks for your quick response.
