### ISSUE TITLE
Non-OK-status: RegisterAlreadyLocked(op_data_factory) error with tensorflow 1.4 and openmpi 2.1.2

### ISSUE THREAD

**Issue by manjunaths** [uber/horovod#123]
I am getting the below error with latest horovod and OpenMPI 2.1.2 with NCCL 2.0 and Cuda 8.0 and Cudnn 6.0 with latest Tensorflow. I am trying to run the

This works perfectly with Tensorflow 1.4 release version. I am trying to get (https://github.com/alsrgv/benchmarks) working and for that I need a later version of Tensorflow.

I am trying to run the tensorflow_mnist.py example.

Any ideas on how I can fix this ?

`mpirun -host ynode01,ynode02 -np 2 -N 1 -x LD_PRELOAD -x LD_LIBRARY_PATH -x PYTHONPATH -mca btl_openib_cuda_rdma_limit 1048576 -mca btl_openib_want_cuda_gdr 1  -mca btl_openib_verbose 1 -report-bindings -mca coll_fca_enable 1 -x CUDA_VISIBLE_DEVICES=5 $PWD/ompi_wrapper.sh`
`[ynode01:10388] Warning: could not find environment variable "LD_PRELOAD"`
`[ynode01:10388] Warning: could not find environment variable "PYTHONPATH"`
`[ynode01:10388] MCW rank 0 bound to socket 0[core 0[hwt 0]]: [B/././././././././././././.][./././././././././././././.]`
`[ynode02:13395] MCW rank 1 bound to socket 0[core 0[hwt 0-1]]: [BB/../../../../../../../../../../../../..][../../../../../../../../../../../../../..]`
`2017-12-14 03:12:43.833700: F tensorflow/core/framework/op.cc:54] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _Arg`
`2017-12-14 03:12:44.167222: F tensorflow/core/framework/op.cc:54] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _Arg`
`/ml/ml01/manju/ompi_Tensorflow14venv/codes/horovod/examples/ompi_wrapper.sh: line 15: 10411 Aborted                 (core dumped) python tensorflow_mnist.py`

`/ml/ml01/manju/ompi_Tensorflow14venv/codes/horovod/examples/ompi_wrapper.sh: line 15: 13404 Aborted                 (core dumped) python tensorflow_mnist.py

**Comment by manjunaths** [comment]
I got this fixed, using gcc 5.3.1 instead of gcc 4.8.5 seems to have made this issue go away. Closing it. Thanks.

**Comment by alsrgv** [comment]
Glad you were able to resolve it!
