### ISSUE TITLE
Restore model failed

### ISSUE THREAD

**Issue by weixsong** [uber/horovod#126]
Hi,

I tried to restore a model trained by my 8-gpu tower implementation, this model is used as warm up model for 16 gpu horovod MPI implementation.
But I got some error:
```
.... Adam_1 not found in checkpoint
.... Adam not found in checkpoint
```

Is that because my model used for warm up is trained by tower implementation, this model format is not compatible with Horovod model format requirement?

Or How I supposed to solve this issue?

**Comment by alsrgv** [comment]
@weixsong, in your `model.load_weights`, can you add `by_name=True`?

```python
    model.load_weights('checkpoint-123.h5', by_name=True)
```

Then it should be able to ignore these Adam weights.

**Comment by weixsong** [comment]
@alsrgv ,
I'm using <code>tf.train.MonitoredTrainingSession</code> to let it restore the model from checkpoint_dir, is that also OK to control it?

**Comment by weixsong** [comment]
@alsrgv ,
seems Tensorflow did not treat Adam parameters as trainable, so not saved in checkpoint. I think if I save all parameters, it will be OK.
