### ISSUE TITLE
Add link/credit to original Baidu implementation (somewhere)

### ISSUE THREAD

**Issue by gibiansky** [uber/horovod#128]
Hey folks,

Horovod is based off stuff we built at Baidu, originally published [here](https://github.com/baidu-research/tensorflow-allreduce) but later merged into a TF contrib to TF master. 

No big deal but it would be nice if you could add info crediting the original authors of the allreduce and TF integration somewhere on the README. (There's a reference to a blog post, but no mention of Horovod code being based off the `tensorflow-allreduce` codebase or the subsequent TF contrib package). Thanks!

**Comment by alsrgv** [comment]
Hi @gibiansky, sure thing!

Any particular resource you'd like us to link? We currently have a link to your blog post at the end of https://github.com/uber/horovod/blob/master/README.md and there's mention of the original repo in a https://github.com/uber/horovod/blob/master/LICENSE file.

**Comment by alsrgv** [comment]
If you plan to keep https://github.com/baidu-research/tensorflow-allreduce around, it would probably be a good resource to reference.

**Comment by gibiansky** [comment]
I think the `tensorflow-allreduce` is the right place to reference, although it's not going to be maintained (since it's not merged as `tf.contrib.mpi_collectives`). Maybe just write something along the lines of, "The Horovod source code was based off the Baidu `tensorflow-allreduce` repository written by Andrew Gibiansky and Joel Hestness and described in this blog post" somewhere at the bottom of the README. (Wording / location doesn't matter too much to me, I've just had a bunch of people come to me and say, "Hey did you see Horovod? Their code looks identical, isn't that suspicious?")

Anyway, thanks! For the record I like Horovod a lot and am using it right now on a personal project of mine.

**Comment by alsrgv** [comment]
Cool, will add it in the next round of doc updates.

**Comment by LoneRifle** [comment]
fwiw - the original blog post seems to have gone missing, with an archive.org copy found at..
https://web.archive.org/web/20180309112609/http://research.baidu.com/bringing-hpc-techniques-deep-learning/

**Comment by alsrgv** [comment]
@gibiansky, any plans to restore the article?

**Comment by gibiansky** [comment]
Yeah, I'm working on this ... I got in touch with folks at Baidu last week and they gave me person to rehost the article somewhere since their web team seems to be slow in getting it back online. I'll find a permanent place for it by the end of this week or so and stick a link here.

**Comment by LoneRifle** [comment]
I'd just like to take the opportunity to thank you both for working on your respective codebases. Even though I do not actually use Tensorflow, I appreciate the fact that the open-source efforts spent by you all benefit the wider dev community at large, and in Baidu's case, resulted in improvements to the original codebase (through tensorflow/tensorflow#12299). This is a point that I am striving to make where I am, and hope to be able to get across in time to come!

**Comment by gibiansky** [comment]
@alsrgv Finally got a chance to sit down and post a new version, with permission from folks at Baidu SVAIL. I now host a copy of this [here](http://andrew.gibiansky.com/blog/machine-learning/baidu-allreduce/). Please link to that instead!

**Comment by gibiansky** [comment]
Additionally I added an addendum linking back to Horovod, since it's IMO the best place to get your TF-supported allreduce nowadays.

**Comment by alsrgv** [comment]
@gibiansky, thanks!  This is getting fixed in #501.
