### ISSUE TITLE
Benchmark description

### ISSUE THREAD

**Issue by apcode** [uber/horovod#13]
The benchmarks in the README are not clear to me. Could you possibly clarify?

The single GPU version has benchamrk of 133 for inception.
The multi GPU versions have Distributed Tensorflow at 10.4
The Horovod results range from 14.4 to 15.6.

I presume given single GPU results that higher is worse. But you have bolded the highest result for Horovod suggesting that is best. These results suggest Distributed Tensorflow is far faster.

So, what are the numbers and is higher better?

**Comment by alsrgv** [comment]
Hi @apcode,

Thanks for raising this issue.  The numbers in the table are actually multiples of single-GPU performance, so Horovod's 15.6 for Inception V3 means 2074.8 images/sec, while Distributed TensorFlow gets 10.4 which translates to 1383.2 images/sec.

We will update the README to clarify this.

**Comment by apcode** [comment]
Ah the 'x' now makes sense in the 'on 16 GPU' row.

Thanks.
