### ISSUE TITLE
Unable to run Horovod in distributed environment

### ISSUE THREAD

**Issue by gyeongin** [uber/horovod#146]
Hi,

I've faced an unknown hanging issue while running Horovod on 2 machines.
My environment is:
* tensorflow r1.5 branch built from source
* 2 MT4115 ConnectX®-4 HCA for each machine + IB switch
* 10G ethernet
* OpenMPI 3.0.0

I can execute the following commands (both on `server1`):
```
mpirun -np 2 -H server1:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca pml ob1 -mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,65536,32 python horovod/examples/tensorflow_mnist.py
```
```
mpirun -np 2 -H server2:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca pml ob1 -mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,65536,32 python horovod/examples/tensorflow_mnist.py
```
But I cannot execute this:
```
mpirun -np 2 -H server1:1,server2:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca pml ob1 -mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,65536,32 python horovod/examples/tensorflow_mnist.py
```

I have tested basic MPI examples such as `mpi_ring.cc` using multiple machines, and confirmed that it works without problem.
I have also tried excluding specific network devices using flags like `btl_openib_if_exclude` or `btl_tcp_if_include`, but it didn't help.

By attaching gdb to mpi-spawned Python processes, I've observed that [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/direct_session.cc#L606) hangs forever, which means some operations used in horovod mnist model do not finish.

**Comment by alsrgv** [comment]
@gyeongin, thanks for the detailed description.  Can you attach the output of `thread apply all bt` from gdb as well as output from the script?

Can you also check that there's no other MPI installed in the system?  E.g. `find /usr | grep mpi | grep \\.so`.

**Comment by gyeongin** [comment]
Thanks for quick response, @alsrgv. I've checked I dont have other MPI installation
Please refer to the links below: 
1) output from the script `mpirun -np 2 -H server1:1,server2:1 ...` [link](https://gist.github.com/gyeongin/c8ba37ff3a35fbb34add542eb6ab253b)
2) bt of TF process on server-1 [link](https://gist.github.com/gyeongin/99878195cebdca5a2a6ad71c17e1901f)
3) bt of TF process on server-2 [link](https://gist.github.com/gyeongin/6339f91a54d127892d499f133790d037)

**Comment by alsrgv** [comment]
Seems that it happened [before](https://github.com/uber/horovod/issues/74#issuecomment-342173803).  Can you try `-mca btl_openib_if_include mlx5_0:1`?  If that doesn't work, can you also try `-mca btl ^openib`?  The latter will force MPI to use TCP for coordination, but NCCL will still use InfiniBand.

**Comment by gyeongin** [comment]
Still does not work with the following command ;)
```
mpirun -np 2 -H server-1:1,server-2:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -mca pml ob1 -mca btl ^openib -x NCCL_IB_DISABLE=1 -mca btl_openib_receive_queues P,128,32:P,2048,32:P,12288,32:P,65536,32 python horovod/examples/tensorflow_mnist.py
```

**Comment by alsrgv** [comment]
Any change to output or backtraces?  In previous trace, MPI hanged on the broadcast operation [one](https://gist.github.com/gyeongin/99878195cebdca5a2a6ad71c17e1901f#file-with-mca-btl-openib-L1872), [two](https://gist.github.com/gyeongin/6339f91a54d127892d499f133790d037#file-with-mca-btl-openib-L1846).

**Comment by gyeongin** [comment]
@alsrgv You are pointing new backtraces, which uses `-mca btl ^openib`.

**Comment by gyeongin** [comment]
@alsrgv Do you use CUDA-aware MPI installation? (e.g., OpenMPI configured with `--with-cuda` option)
What do you think about [this](http://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/index.html#intergpu) documentation? Is this can be a problem in Horovod?

**Comment by alsrgv** [comment]
@gyeongin, very interesting pointer! We are not using CUDA-aware MPI typically. Horovod only uses CUDA-aware MPI if you compile it with `HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI`. Which installation command did you use?

**Comment by gyeongin** [comment]
@alsrgv I've used the following command for installing Horovod:
`HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI pip install --no-cache-dir horovod`
I have CUDA-aware OpenMPI installation and my tensorflow is built with MPI support.

**Comment by alsrgv** [comment]
@gyeongin, can you reinstall Horovod with `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod` and, if it's not enough, try TF without MPI support (just in case)?

**Comment by gyeongin** [comment]
@alsrgv `HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod` works, thanks!
Does removing `HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI` flag make Horovod works a little slower for sparse tensors?

**Comment by alsrgv** [comment]
@gyeongin, if your sparse tensors are not huge, e.g. typical word embedding, it should not matter much, but for very large sparse tensors you may notice a difference.

This is the first time I'm seeing CUDA MPI break NCCL though.  We should update the documentation to account for that.
