### ISSUE TITLE
Building Horovod from source

### ISSUE THREAD

**Issue by gyeongin** [uber/horovod#155]
Hi, I am trying to make some modifications to Horovod internals, but could not find documentations for building Horovod from source. Could you kindly let me know how to do this?

**Comment by alsrgv** [comment]
@gyeongin, the simplest way would be...

```
$ git clone https://github.com/uber/horovod
$ cd horovod
$ python setup.py sdist
$ [flags] pip install sdist/horovod*.tar.gz
```

**Comment by gyeongin** [comment]
@alsrgv Thanks!

**Comment by alsrgv** [comment]
I'll close this issue as it appears to be resolved.

**Comment by libliang** [comment]
@fanshiqing @alsrgv  Hello, I am also trying to build horovod from source, since we need to build it based on CUDA 9.2
What is the difference between building  bdist_whell and  sdist?  can you please kindly tell me?

many thanks

**Comment by alsrgv** [comment]
@libliang, `bdist_wheel` will build you a wheel file on that can be installed on a server with exactly the same build flags (e.g. HOROVOD_GPU_ALLREDUCE) and version of TensorFlow, MPI, CUDA, and NCCL as the server you built the wheel on.

`sdist` provides source tarball that you can install on a target server with build flags and versions of dependencies available on the server that you're installing the tarball.

We almost always use `python setup.py sdist` instead of `bdist_wheel` because it gives this "late binding" benefits.

**Comment by Young768** [comment]
@alsrgv Hi Alex, I tried to build horovod from downloaded source code:
$ git clone https://github.com/uber/horovod
$ cd horovod
$ python setup.py sdist
After I ran these commands, i got tar.gz package under dist file. So I ran 
$pip install --no-cache-dir dist/horovod-0.16.1.tar.gz

I can build horovod from pip install horovod successfully. But when I ran the above, I met these errors. Could you please have a look?

Processing ./dist/horovod-0.16.1.tar.gz
Requirement already satisfied: cloudpickle in /root/anaconda3/lib/python3.7/site-packages (from horovod==0.16.1) (0.8.0)
Requirement already satisfied: psutil in /root/anaconda3/lib/python3.7/site-packages (from horovod==0.16.1) (5.6.1)
Requirement already satisfied: six in /root/anaconda3/lib/python3.7/site-packages (from horovod==0.16.1) (1.12.0)
Requirement already satisfied: cffi>=1.4.0 in /root/anaconda3/lib/python3.7/site-packages (from horovod==0.16.1) (1.12.2)
Requirement already satisfied: pycparser in /root/anaconda3/lib/python3.7/site-packages (from cffi>=1.4.0->horovod==0.16.1) (2.19)
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /root/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-w5225pjj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-g8tlzzif/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-3.7/horovod
    creating build/lib.linux-x86_64-3.7/horovod/spark
    copying horovod/spark/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark
    creating build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/__init__.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    copying horovod/mxnet/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/mxnet
    creating build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/task_fn.py -> build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/run.py -> build/lib.linux-x86_64-3.7/horovod/run
    copying horovod/run/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/util.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/compression.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow
    creating build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/util.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/basics.py -> build/lib.linux-x86_64-3.7/horovod/common
    copying horovod/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/common
    creating build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/keras
    creating build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/compression.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch
    copying horovod/torch/mpi_ops.py -> build/lib.linux-x86_64-3.7/horovod/torch
    creating build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    copying horovod/_keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/_keras
    creating build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/mpirun_rsh.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/job_id.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    copying horovod/spark/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/driver
    creating build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/mpirun_exec_fn.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    copying horovod/spark/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/spark/task
    creating build/lib.linux-x86_64-3.7/horovod/run/driver
    copying horovod/run/driver/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/run/driver
    copying horovod/run/driver/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/driver
    creating build/lib.linux-x86_64-3.7/horovod/run/common
    copying horovod/run/common/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common
    creating build/lib.linux-x86_64-3.7/horovod/run/task
    copying horovod/run/task/task_service.py -> build/lib.linux-x86_64-3.7/horovod/run/task
    copying horovod/run/task/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/task
    creating build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/threads.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/cache.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/network.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    copying horovod/run/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/util
    creating build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/driver_service.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/task_service.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    copying horovod/run/common/service/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common/service
    creating build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/host_hash.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/settings.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/network.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/timeout.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/env.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/safe_shell_exec.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/codec.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/__init__.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    copying horovod/run/common/util/secret.py -> build/lib.linux-x86_64-3.7/horovod/run/common/util
    creating build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/callbacks.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    copying horovod/tensorflow/keras/__init__.py -> build/lib.linux-x86_64-3.7/horovod/tensorflow/keras
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    copying horovod/torch/mpi_lib_impl/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib_impl
    creating build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    copying horovod/torch/mpi_lib/__init__.py -> build/lib.linux-x86_64-3.7/horovod/torch/mpi_lib
    running build_ext
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/root/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /root/anaconda3/compiler_compat -L/root/anaconda3/lib -Wl,-rpath=/root/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-3.7/test_compile/test_cpp_flags.so
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/include/python3.7m -c build/temp.linux-x86_64-3.7/test_compile/test_link_flags.cc -o build/temp.linux-x86_64-3.7/test_compile/test_link_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -shared -B /root/anaconda3/compiler_compat -L/root/anaconda3/lib -Wl,-rpath=/root/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ -Wl,--version-script=horovod.lds build/temp.linux-x86_64-3.7/test_compile/test_link_flags.o -o build/temp.linux-x86_64-3.7/test_compile/test_link_flags.so
    building 'horovod.tensorflow.mpi_lib' extension
    creating build/temp.linux-x86_64-3.7/horovod
    creating build/temp.linux-x86_64-3.7/horovod/common
    creating build/temp.linux-x86_64-3.7/horovod/common/ops
    creating build/temp.linux-x86_64-3.7/horovod/common/optim
    creating build/temp.linux-x86_64-3.7/horovod/tensorflow
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_MPL2_ONLY=1 -Ithird_party/eigen -Ithird_party/lbfgs/include -Ithird_party/boost/assert/include -Ithird_party/boost/config/include -Ithird_party/boost/core/include -Ithird_party/boost/detail/include -Ithird_party/boost/iterator/include -Ithird_party/boost/lockfree/include -Ithird_party/boost/mpl/include -Ithird_party/boost/parameter/include -Ithird_party/boost/predef/include -Ithird_party/boost/preprocessor/include -Ithird_party/boost/static_assert/include -Ithird_party/boost/type_traits/include -Ithird_party/boost/utility/include -Ithird_party/flatbuffers/include -I/root/anaconda3/include/python3.7m -c horovod/common/common.cc -o build/temp.linux-x86_64-3.7/horovod/common/common.o -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/root/anaconda3/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_MPL2_ONLY=1 -Ithird_party/eigen -Ithird_party/lbfgs/include -Ithird_party/boost/assert/include -Ithird_party/boost/config/include -Ithird_party/boost/core/include -Ithird_party/boost/detail/include -Ithird_party/boost/iterator/include -Ithird_party/boost/lockfree/include -Ithird_party/boost/mpl/include -Ithird_party/boost/parameter/include -Ithird_party/boost/predef/include -Ithird_party/boost/preprocessor/include -Ithird_party/boost/static_assert/include -Ithird_party/boost/type_traits/include -Ithird_party/boost/utility/include -Ithird_party/flatbuffers/include -I/root/anaconda3/include/python3.7m -c horovod/common/fusion_buffer_manager.cc -o build/temp.linux-x86_64-3.7/horovod/common/fusion_buffer_manager.o -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/root/anaconda3/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_MPL2_ONLY=1 -Ithird_party/eigen -Ithird_party/lbfgs/include -Ithird_party/boost/assert/include -Ithird_party/boost/config/include -Ithird_party/boost/core/include -Ithird_party/boost/detail/include -Ithird_party/boost/iterator/include -Ithird_party/boost/lockfree/include -Ithird_party/boost/mpl/include -Ithird_party/boost/parameter/include -Ithird_party/boost/predef/include -Ithird_party/boost/preprocessor/include -Ithird_party/boost/static_assert/include -Ithird_party/boost/type_traits/include -Ithird_party/boost/utility/include -Ithird_party/flatbuffers/include -I/root/anaconda3/include/python3.7m -c horovod/common/half.cc -o build/temp.linux-x86_64-3.7/horovod/common/half.o -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/root/anaconda3/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from horovod/common/half.cc:21:0:
    horovod/common/half.h: In function ‘void horovod::common::HalfBits2Float(short unsigned int*, float*)’:
    horovod/common/half.h:70:44: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
       *res = *reinterpret_cast<float const*>(&f);
                                                ^
    gcc -pthread -B /root/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEIGEN_MPL2_ONLY=1 -Ithird_party/eigen -Ithird_party/lbfgs/include -Ithird_party/boost/assert/include -Ithird_party/boost/config/include -Ithird_party/boost/core/include -Ithird_party/boost/detail/include -Ithird_party/boost/iterator/include -Ithird_party/boost/lockfree/include -Ithird_party/boost/mpl/include -Ithird_party/boost/parameter/include -Ithird_party/boost/predef/include -Ithird_party/boost/preprocessor/include -Ithird_party/boost/static_assert/include -Ithird_party/boost/type_traits/include -Ithird_party/boost/utility/include -Ithird_party/flatbuffers/include -I/root/anaconda3/include/python3.7m -c horovod/common/message.cc -o build/temp.linux-x86_64-3.7/horovod/common/message.o -std=c++11 -fPIC -O2 -Wall -mf16c -mavx -I/usr/local/include -pthread -Wl,-rpath -Wl,/usr/local/lib -Wl,--enable-new-dtags -L/usr/local/lib -lmpi -I/root/anaconda3/lib/python3.7/site-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from horovod/common/message.cc:18:0:
    horovod/common/wire/message_generated.h:22:37: fatal error: flatbuffers/flatbuffers.h: No such file or directory
    compilation terminated.
    INFO: Unable to build TensorFlow plugin, will skip it.
    
    Traceback (most recent call last):
      File "/root/anaconda3/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
        extra_postargs)
      File "/root/anaconda3/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/root/anaconda3/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/root/anaconda3/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 948, in build_extensions
        build_tf_extension(self, options)
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 623, in build_tf_extension
        build_ext.build_extension(tensorflow_mpi_lib)
      File "/root/anaconda3/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
        _build_ext.build_extension(self, ext)
      File "/root/anaconda3/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/root/anaconda3/lib/python3.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/root/anaconda3/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1
    
    INFO: Unable to build PyTorch plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 750, in check_torch_version
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 959, in build_extensions
        torch_version = check_torch_version()
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 757, in check_torch_version
        'import torch failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import torch failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 750, in check_torch_version
        import torch
    ModuleNotFoundError: No module named 'torch'
    
    
    INFO: Unable to build MXNet plugin, will skip it.
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 71, in check_mx_version
        import mxnet as mx
    ModuleNotFoundError: No module named 'mxnet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 974, in build_extensions
        build_mx_extension(self, options)
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 693, in build_mx_extension
        check_mx_version()
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 78, in check_mx_version
        'import mxnet failed, is it installed?\n\n%s' % traceback.format_exc())
    distutils.errors.DistutilsPlatformError: import mxnet failed, is it installed?
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-w5225pjj/setup.py", line 71, in check_mx_version
        import mxnet as mx
    ModuleNotFoundError: No module named 'mxnet'
    
    
    error: None of TensorFlow, PyTorch, or MXNet plugins were built. See errors above.
    
    ----------------------------------------
Command "/root/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-w5225pjj/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-g8tlzzif/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-w5225pjj/

**Comment by alsrgv** [comment]
@Young768, these days you need to `git clone --recursive https://github.com/horovod/horovod` because we added submodules.

**Comment by Young768** [comment]
@alsrgv Hi Alex. Yep It works. Thanks

**Comment by pusabre** [comment]
This is still happening for me. I cloned sources with submodules:
`git clone --recursive https://github.com/horovod/horovod`
but when I try to `import horovod.tensorflow` then it breaks:
`>>> import horovod.tensorflow as htf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zucchabar/horovod/horovod/tensorflow/__init__.py", line 25, in <module>
    check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/home/zucchabar/horovod/horovod/common/util.py", line 46, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.`

**Comment by alsrgv** [comment]
@pusabre, can you try this sequence:
```
$ git clone https://github.com/horovod/horovod
$ cd horovod
$ python setup.py sdist
$ cd dist
$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir dist/horovod-0.16.4.tar.gz
```

**Comment by pusabre** [comment]
@alsrgv thank you for your comment. I am out off the office for a week but I will give it a try for sure and let you know about the results.

**Comment by PiseyYou** [comment]
> (horovod) pisey@slave01:~/anaconda3/envs/horovod/horovod/dist$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir horovod-0.18.1.tar.gz
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./horovod-0.18.1.tar.gz
Requirement already satisfied: cloudpickle in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from horovod==0.18.1) (1.2.1)
Requirement already satisfied: psutil in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from horovod==0.18.1) (5.6.3)
Requirement already satisfied: pyyaml in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from horovod==0.18.1) (5.1.2)
Requirement already satisfied: six in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from horovod==0.18.1) (1.12.0)
Requirement already satisfied: cffi>=1.4.0 in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from horovod==0.18.1) (1.12.3)
Requirement already satisfied: pycparser in /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages (from cffi>=1.4.0->horovod==0.18.1) (2.19)
Building wheels for collected packages: horovod
  Building wheel for horovod (setup.py) ... done
  Created wheel for horovod: filename=horovod-0.18.1-cp36-cp36m-linux_x86_64.whl size=194547712 sha256=7f185c22a815cf694ab3895d09daa41e14e56832e478043bedc4f131b16bde9a
  Stored in directory: /tmp/pip-ephem-wheel-cache-je2vnrck/wheels/23/f7/32/cb5f2ffce6002f382ce9ec11bcb81d142a0018f8f072dc2688
Successfully built horovod
Installing collected packages: horovod
  Found existing installation: horovod 0.18.1
    Uninstalling horovod-0.18.1:
      Successfully uninstalled horovod-0.18.1
Successfully installed horovod-0.18.1


> (horovod) pisey@slave01:~/anaconda3/envs/horovod/horovod$ mpirun -np 1 -H localhost:1 python examples/tensorflow_mnist.py
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

 

>  _np_qint8 = np.dtype([("qint8", np.int8, 1)])

> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
> _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

> np_resource = np.dtype([("resource", np.ubyte, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

> _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

>  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /home/pisey/anaconda3/envs/horovod/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.

>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> Traceback (most recent call last):
> File "examples/tensorflow_mnist.py", line 19, in <module>
>  import horovod.tensorflow as hvd
>  File "/home/pisey/anaconda3/envs/horovod/horovod/horovod/tensorflow/__init__.py", line 24, in <module>

 

> check_extension('horovod.tensorflow', 'HOROVOD_WITH_TENSORFLOW', __file__, 'mpi_lib')
  File "/home/pisey/anaconda3/envs/horovod/horovod/horovod/common/util.py", line 51, in check_extension
    'Horovod with %s=1 to debug the build error.' % (ext_name, ext_env_var))
ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.
--------------------------------------------------------------------------

> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.

--------------------------------------------------------------------------
--------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
>   Process name: [[23853,1],0]
>  Exit code:    1

--------------------------------------------------------------------------


dear @alsrgv, follow your instuctor, I did following, and no error, but when I try to run examply/tensorflow_mnist.py, the error ocurr, Horovod with HOROVOD_WITH_TENSORFLOW=1 pip *, seem became a loop, any suggestion to deal such error?

$ git clone https://github.com/horovod/horovod
$ cd horovod
$ python setup.py sdist
$ cd dist
$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_WITH_TENSORFLOW=1 pip install --no-cache-dir dist/horovod-0.18.1.tar.gz

`ImportError: Extension horovod.tensorflow has not been built.  If this is not expected, reinstall Horovod with HOROVOD_WITH_TENSORFLOW=1 to debug the build error.`

**Comment by abditag2** [comment]
@PiseyYou you have to do `pip install tensorflow` before installing horovod.

**Comment by PiseyYou** [comment]
after run under root permission, it works.

**Comment by chenchen-tom** [comment]
> > @PiseyYou you have to do `pip install tensorflow` before installing horovod.
> 
> dear, tensorflow has already install, or it will appear the error such as `no model named tensorflow`, I create the virtual envs named 'horovod', install tensorflow, pytorch, mxnet and all necessary package inside. But when try to install the horovod, seem the solution above didn't work. I wonder whether there is some setting or command outside the virtual envs or install envs, and some point add 'sudo' sometimes work on somewhere, I try different place both sudo and without, but the way is not working. I was curious whether there is somehow with experience with virtual envs sovle the install problem.

Will this solve the problem yet, I also encountered

**Comment by Tonyhukaifan** [comment]
Appreciate for your resolution，it works.
