### ISSUE TITLE
Question about the HOROVOD_MPICXX_SHOW environment variable

### ISSUE THREAD

**Issue by ksy3395** [uber/horovod#169]
Hello,

I am trying to install horovod on Ubuntu 17.10 x64, and I am having an error I couldn't solve.
Could you help me with this error? I check the $PATH, and it has openmpi, and I don't know about  HOROVOD_MPICXX_SHOW environment variable.

I got this error:
error: mpicxx -show failed (see error below), is MPI in $PATH?
  Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.

and the $PATH:
/root/tensorflow/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/root/.openmpi/bin:/home/root/.openmpi/bin

The whole error message:
Collecting horovod
  Using cached horovod-0.11.2.tar.gz
Building wheels for collected packages: horovod
  Running setup.py bdist_wheel for horovod ... error
  Complete output from command /root/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GC9XIh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpSzJObBpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/horovod
  copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
  creating build/lib.linux-x86_64-2.7/horovod/keras
  copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
  copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
  creating build/lib.linux-x86_64-2.7/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
  copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
  copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
  running build_ext
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
  error: mpicxx -show failed (see error below), is MPI in $PATH?
  Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.
  
  Traceback (most recent call last):
    File "/tmp/pip-build-GC9XIh/horovod/setup.py", line 173, in get_mpi_flags
      shlex.split(show_command), universal_newlines=True).strip()
    File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
      process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
      errread, errwrite)
    File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
      raise child_exception
  OSError: [Errno 2] No such file or directory
  
  
  ----------------------------------------
  Failed building wheel for horovod
  Running setup.py clean for horovod
Failed to build horovod
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /root/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GC9XIh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-DNfIwR-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/tensorflow/include/site/python2.7/horovod:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/callbacks.py -> build/lib.linux-x86_64-2.7/horovod/keras
    copying horovod/keras/__init__.py -> build/lib.linux-x86_64-2.7/horovod/keras
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -fPIC -O2 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-l1RrwO/python2.7-2.7.14=. -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.o -o build/temp.linux-x86_64-2.7/test_compile/test_cpp_flags.so
    error: mpicxx -show failed (see error below), is MPI in $PATH?
    Note: If your version of MPI has a custom command to show compilation flags, please specify it with the HOROVOD_MPICXX_SHOW environment variable.
    
    Traceback (most recent call last):
      File "/tmp/pip-build-GC9XIh/horovod/setup.py", line 173, in get_mpi_flags
        shlex.split(show_command), universal_newlines=True).strip()
      File "/usr/lib/python2.7/subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1025, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
    
    
    ----------------------------------------
Command "/root/tensorflow/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-GC9XIh/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-DNfIwR-record/install-record.txt --single-version-externally-managed --compile --install-headers /root/tensorflow/include/site/python2.7/horovod" failed with error code 1 in /tmp/pip-build-GC9XIh/horovod/

**Comment by mohammedayub44** [comment]
@ksy3395  I'm getting the same error. How did you happen to solve this ? If you could please share your resolution steps.

**Comment by mohammedayub44** [comment]
For now, I followed this blog post : 
`https://superuser.com/questions/927512/how-to-set-path-for-sudo-commands`
to edit the sudoers $PATH because pip overrides user's $PATH variable.
and then ran 
 `sudo pip install --verbose --no-cache-dir horovod`

and it worked fine. 
I'm not sure this is the most secure way to do it, as not everyone will have access to edit the sudoers $PATH file.
