### ISSUE TITLE
Compatibility with other DL frameworks

### ISSUE THREAD

**Issue by SrivastavaKshitij** [uber/horovod#171]
Hey there

I just want to know if Horovod is compatible with other deep learning frameworks such as MXnet and PyTorch and if yes, are there any specifics which needs to be taken care of when installing Horovod with these frameworks ?

Thanks

**Comment by alsrgv** [comment]
@SrivastavaKshitij, as of now, Horovod only supports TensorFlow and Keras with TensorFlow backend.  We are investigating PyTorch support at the moment.

**Comment by avolkov1** [comment]
You guys are awesome! Great code and awesome architecture.
