### ISSUE TITLE
mnist_advanced example freezing after printing epoch 1/24

### ISSUE THREAD

**Issue by prafulag** [uber/horovod#180]
After printing "Epoch 1/24" from all devices, the GPU util goes to zero whereas process is still active on GPU with memory allocated. 

However, mnist example is working fine. Seems to be some issue in fit_generator ?

**Comment by alsrgv** [comment]
If you're using NCCL, can you run with NCCL_DEBUG=INFO and see if it prints any more info?

Thanks,
Alex

**Comment by alsrgv** [comment]
What version of Keras are you using?

**Comment by prafulag** [comment]
2.1.3

**Comment by alsrgv** [comment]
Can you share the output of nvidia-smi as it runs out of memory?

**Comment by xKelsius** [comment]
@prafulag I'm also encountering this issue across multiple GPUs, although I'm not running out of memory. The process seems to hang after printing "Epoch 1/X" where X is number of epochs requested.

**Comment by xKelsius** [comment]
@prafulag Just as an update, my issue seemed to be with using the wrong version of NCCL. I was using a conda environment that happened to have NCCL 1.3.4 installed, when I needed to use NCCL 2.x. Hope that helps or helps someone else.

**Comment by alsrgv** [comment]
I'll close this issue as it appears to be resolved.
