### ISSUE TITLE
docker image push fails with file integrity checksum failed

### ISSUE THREAD

**Issue by atinsood** [uber/horovod#181]
docker build -t user/horovod_15 .
docker tag 9b74b628d808 <private_registry>/horovod_15:latest
docker push <private_registry>/horovod_15:latest
bb722ac35434: Pushing [==================================================>]  569.6MB/569.6MB layer
keeps failing with file integrity checksum failed for "usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5"

**Comment by alsrgv** [comment]
These two pointers may help you:
1. https://stackoverflow.com/questions/39529630/unable-to-push-docker-image-on-local-private-registry
2. https://github.com/moby/moby/issues/33991

**Comment by atinsood** [comment]
yep, think a few things helped. we were using python 3.5 so using pip3 in the dockerfile helped.  also we don't use nvidia docker so had to do a few soft links.

closing this, since this seems to be running well now. appreciate the help @alsrgv
