### ISSUE TITLE
hvd.init() hangs on aws deep learning instance

### ISSUE THREAD

**Issue by gururao001** [uber/horovod#187]
Hello,
I am using base deep learning aws instance with g3 (2 gpus)
 After horovod installation using this command
**HOROVOD_GPU_ALLREDUCE=NCCL pip install horovod --user**
it hangs before hvd.init() (by printing out the statements) 

I have ens3 and lo 
I have two tesla M60s 

#

**Comment by alsrgv** [comment]
@gururao001, on AWS you should uninstall MPI that comes with their base image:

```
$ sudo apt purge -y openmpi-bin openmpi-common libopenmpi-dev libopenmpi1.10
$ sudo rm -rf /usr/local/mpi
$ wget https://www.open-mpi.org/software/ompi/v3.0/downloads/openmpi-3.0.0.tar.gz
$ tar zxvf openmpi-3.0.0.tar.gz
$ cd openmpi-3.0.0; ./configure; make -j $(nproc); sudo make install; sudo ldconfig
$ rm -rf openmpi-3.0.0*
$ HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod
```

**Comment by gururao001** [comment]
Hey, @alsrgv  Thanks a lot for the help. I got it running after uninstalling mpi. But I have ncclCommInitRank failed: unhandled cuda error. I followed your troubleshooting advice. I get the following error


2018-03-02 15:20:03.975737: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-02 15:20:03.993236: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-02 15:20:04.110239: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-02 15:20:04.110759: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 0000:00:1d.0
totalMemory: 7.43GiB freeMemory: 7.35GiB
2018-03-02 15:20:04.110783: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla M60, pci bus id: 0000:00:1d.0, compute capability: 5.2)
2018-03-02 15:20:04.139810: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-02 15:20:04.140101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: Tesla M60 major: 5 minor: 2 memoryClockRate(GHz): 1.1775
pciBusID: 0000:00:1e.0
totalMemory: 7.43GiB freeMemory: 7.35GiB
2018-03-02 15:20:04.140126: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 1, name: Tesla M60, pci bus id: 0000:00:1e.0, compute capability: 5.2)
RUNNING SESSION
RUNNING SESSION
[ip-172-31-38-15:47472] 1 more process has sent help message help-mpi-btl-base.txt / btl:no-nics
[ip-172-31-38-15:47472] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
ip-172-31-38-15:47480:47588 [-1] INFO NET : Using interface ens3:172.31.38.15<0>
ip-172-31-38-15:47480:47588 [-880816816] INFO NET/IB : Using interface ens3 for sideband communication
ip-172-31-38-15:47480:47588 [32723] INFO Using internal Network Socket
ip-172-31-38-15:47480:47588 [3485997] INFO Using NCCL Low-latency algorithm for sizes below 16384
ip-172-31-38-15:47480:47588 [32724] INFO NET : Using interface ens3:172.31.38.15<0>
ip-172-31-38-15:47480:47588 [32724] INFO NET : Using interface docker0:172.17.0.1<0>
ip-172-31-38-15:47480:47588 [32724] INFO NET : Using interface br-05faed8a29f4:172.18.0.1<0>
ip-172-31-38-15:47480:47588 [32724] INFO NET : Using interface veth3026fd5:fe80::20be:8dff:fe32:553e%veth3026fd5<0>
ip-172-31-38-15:47480:47588 [-1] INFO NET/Socket : 4 interfaces found
NCCL version 2.1.4+cuda9.1

ip-172-31-38-15:47480:47588 [-880818808] init.cu:547 WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'
ip-172-31-38-15:47481:47599 [-1] INFO NET : Using interface ens3:172.31.38.15<0>
ip-172-31-38-15:47481:47599 [41918544] INFO NET/IB : Using interface ens3 for sideband communication
ip-172-31-38-15:47481:47599 [0] INFO Using internal Network Socket
ip-172-31-38-15:47481:47599 [3485997] INFO Using NCCL Low-latency algorithm for sizes below 16384

ip-172-31-38-15:47481:47599 [-1] init.cu:547 WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'
Traceback (most recent call last):
  File "new_train_op_horovod.py", line 320, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "new_train_op_horovod.py", line 316, in main
    run_training()
  File "new_train_op_horovod.py", line 301, in run_training
    _, batch_cost = sess.run([train_op, loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: ncclCommInitRank failed: unhandled cuda error
	 [[Node: DistributedGradientDescentOptimizer_Allreduce/HorovodAllreduce_gradients_fully_conn_Add_grad_tuple_control_dependency_1_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/fully_conn/Add_grad/tuple/control_dependency_1)]]

**Comment by gururao001** [comment]
Hey, @alsrgv  Thanks for the help man! It solved the problem. A couple of  follow-up questions
1. I read that NCCL 2 does not support fp16. Is there a workaround for it as fp16 improves speeds during training in latest voltas? 
2. when I run the program with horovod i see two iterations are taking place at the same time (2 gpu system). I am relatively new to horovod. So is there a way to sanity check whether all reduce is happening? It is not really obvious to me. Thanks

**Comment by alsrgv** [comment]
@gururao001,

1. According to http://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html#lossscaling, it's better to keep weights in FP32.  Since gradients are to be aggregated between many GPUs, it is likely better to keep them in FP32 as well.  You will still get a performance benefit of computing gradients in FP16 on each worker.  E.g. you can run TF benchmarks with FP16 and see performance improvements.

That said, this area is still being explored, and it may be faster to average gradients in FP16 directly, without suffering from reduced precision.  If you want to explore this direction, I can push a branch for you with FP16 support.

2. If you run with `-x NCCL_DEBUG=INFO`, you will see messages from NCCL setting up rings. If you do, it means that allreduce is working.

**Comment by yaroslavvb** [comment]
Hm, I just followed these instructions and I can't find mpiexec anymore

**Comment by alsrgv** [comment]
@yaroslavvb, if you ran `make install`, it must be somewhere.  What about `mpirun`?

**Comment by yaroslavvb** [comment]
Ah yes, mpirun got dropped into `/usr/local/bin`, but not mpiexec
Also this procedure seems to be incompatible with mpi4py (`pip install mpi4py; python run.py` ... `libmpi.so.12: cannot open shared object file`)

**Comment by alsrgv** [comment]
@yaroslavvb, try reinstalling mpi4py, make sure to use `--no-cache-dir` option.

**Comment by gururao001** [comment]
Hey @alsrgv thanks for the info. It was really helpful. So when trying to force all reduce in CPU using device_dense='/cpu:0' I don't see info about setting up rings but I see it when doing with gpu. Is it normal? I installed horovod using the command 'HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod'. Is there another version of horovod to force cpu reductions? Thanks

**Comment by alsrgv** [comment]
@gururao001,

You can do a dummy test where you do: `hvd.allreduce(tf.constant(hvd.rank() == 0 ? 1. : 2.))` and print out the answer, which should be 1.5 if you have two processes.

BTW, what's the reason you want to force reductions to CPU?  It's almost always slower.

**Comment by gururao001** [comment]
@alsrgv  Thanks man! So I am assuming reductions in GPU are going to take up some gpu memory. So I want to test whether I can increase the batch size while doing the reductions in CPU. What do you think?

**Comment by gururao001** [comment]
Also while prefetching the data can we continue doing next iteration in GPU while reductions happens in CPU?

**Comment by alsrgv** [comment]
OK, sure - it's good idea to try both. Please share if you see better performance on CPU.

**Comment by gururao001** [comment]
sure @alsrgv

**Comment by gururao001** [comment]
Hey @alsrgv I am getting this error https://gist.github.com/gururao001/7134780210e3521e319ac212e4cc2b4e 
Is openmpi using too many threads? how do I resolve it?

**Comment by gururao001** [comment]
@alsrgv Its actually p3.16x instances that got the error. It works fine on p3.8x with same code, same data and same ami. very strange. Just wanted to ask you if you seen this before. Thanks for responding so quickly man!

**Comment by alsrgv** [comment]
@gururao001, very strange. What if you try another instance, maybe there was a hardware issue?

**Comment by gururao001** [comment]
@alsrgv good point. Let me try that. Also just curious is there some optimations on horovod side to be run to make it faster on aws p3?

**Comment by alsrgv** [comment]
@gururao001, the same way as in https://github.com/uber/horovod/blob/master/docs/running.md.
