### ISSUE TITLE
an issue in the dockerfile, seems the cudnn version does't match.

### ISSUE THREAD

**Issue by GoodJoey** [uber/horovod#192]
tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 7101 (compatibility version 7100) but source was compiled with 7004 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  

maybe it is because the nvidia/cuda image has been updated.

**Comment by alsrgv** [comment]
@GoodJoey, indeed, it got updated.  I just pushed PR #193 to upgrade to TF 1.6.0 which seems to be working fine.  Feel free to use Dockerfile from that PR.

**Comment by seelam** [comment]
This update 5 days ago (move from cudnn 7.0 to 7.1) caused this issue for future reference: https://gitlab.com/nvidia/cuda/commit/3138ae16591b6a06edce4ea55864c8782360092d

If you wish to stick with Tensorflow 1.5, uninstall 7.1 and and install 7.0 as follows:

```
#Newer version cuda 9.0 base image updates the cudnn to 7.1. See here:
#https://gitlab.com/nvidia/cuda/commit/3138ae16591b6a06edce4ea55864c8782360092d
#While tensorflow is still compiled with 7.0 so this upgrade breaks the application.
#Remove cudnn7.1.1 and install cudnn7.0.5

RUN apt-get remove -y libcudnn7

RUN apt-get install -y --allow-unauthenticated \
    libcudnn7=7.0.5.15-1+cuda9.0 \
    libcudnn7-dev=7.0.5.15-1+cuda9.0
```
