### ISSUE TITLE
question: if the model is too large to load into one gpu, how to adjust the paramerts?

### ISSUE THREAD

**Issue by GoodJoey** [uber/horovod#199]
For example, if i have 4 gpu in each of my node, but the single gpu doesn't have enough memory to load resnet101(it's a hypothesis, i know one way is to reduce the batch_size), what should i do?
i tried to set --num_gpus=2, but seems the gpu num has to be 1 if we use --variable_update horovod.

nvidia-docker run -it --network=host -v /mnt/share/ssh:/root/.ssh horovod:latest
root@c278c88dd552:/examples# mpirun -np 16 -H host1:4,host2:4,host3:4,host4:4 \
    -mca plm_rsh_args "-p 12345" python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod

Thanks.

**Comment by ink1** [comment]
Most approaches (synchronous or asynchronous) to distributed learning share (clone) parameters and therefore replicate the model. You can try splitting the model, say, on two and arranging a flow. Then you'd use even rank for part one and odd rank for part two but doing so is significantly more complicated than simple replication. So, yes, reduce the batch size, reduce accuracy.

**Comment by alsrgv** [comment]
Reducing the batch size to 32 is very appropriate.  It will not necessarily reduce accuracy.  If you're up for modifying the code, you can pin GPUs and do a mixture of model parallel and data parallel approach, see #96.  Lastly, you can also use [gradient checkpointing](https://github.com/openai/gradient-checkpointing).

**Comment by GoodJoey** [comment]
got it, thanks.
