### ISSUE TITLE
Question: RDMA Horovod with NCCL

### ISSUE THREAD

**Issue by Zhaojp-Frank** [uber/horovod#20]
Hi, 
a question on the first 16-GPU benchmark shown in the README, it's said RoCE 25Gb, and "RDMA Horovod (allreduce on GPU with NCCL)", however, NCCL2 so far doesn't support RoCE RDMA, so it's a typo about this 'RDMA Horovod'? right? 

RDMA Horovod (allreduce on GPU with NCCL) | 2,022.6 (15.0x) | 1,746.2 (14.6x) | 1,787.4 (13.7x)
-- | -- | -- | --

instead, in the 2nd benchmark on 64-GPU, it's 'TCP Horovod (allreduce on GPU with NCCL)'

**Comment by alsrgv** [comment]
Hi, @Zhaojp-Frank.  The [latest version of NCCL](http://docs.nvidia.com/deeplearning/sdk/nccl-release-notes/rel_2.0.5.html#rel_2.0.5) released a few days ago has experimental support for RoCE, which is what we have tested in this benchmark.

**Comment by Zhaojp-Frank** [comment]
wow, that's cool! thanks. We'd like to try Horovod and latest NCCL 
pls close this issue.

**Comment by alsrgv** [comment]
Great! Please share your feedback when you do.
