### ISSUE TITLE
Horovod and Google cloud ML Engine

### ISSUE THREAD

**Issue by zippeurfou** [uber/horovod#200]
Hi,
This is more of a guide request than a bug report. Feel free to close the issue if it is outside of the scope of what is covered here.
There is a nice guide for Microsoft Azure and I was hoping to find something similar for Google cloud ML but couldn't find any.
I believe there is a real value to it as a lot of people use google cloud ML.
Best,

**Comment by alsrgv** [comment]
@zippeurfou, from what I understand Cloud ML will not be able to run MPI jobs. We are looking at whether Horovod training can be done as a Kubernetes job. Contributions would be very welcome here.

**Comment by alsrgv** [comment]
@zippeurfou, we've recently added Kubernetes job support via Kubeflow (https://github.com/kubeflow/kubeflow/tree/master/kubeflow/openmpi).
