### ISSUE TITLE
Restoring checkpoints when using multiple servers

### ISSUE THREAD

**Issue by gururao001** [uber/horovod#202]
Hey @alsrgv When I restore checkpoints when using multiple servers I am getting this error 

WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.

When I do restore from only one server everything works fine! I think it is because when I restore only one server is working while other is not! Is there a fix for this? 

Thanks

**Comment by alsrgv** [comment]
@gururao001, which rank #s are displayed in the error message?  Can you paste the code that you use for restoring from the checkpoint?

**Comment by gururao001** [comment]
1. error message 
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock. Stalled ops: DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_51_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_48_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_38_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_34_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_32_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_28_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_42_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_24_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_21_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_12_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_8_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_4_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_fully_conn_MatMul_grad_tuple_control_dependency_1_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_fully_conn_Add_grad_tuple_control_dependency_1_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_conv2d_BiasAdd_grad_tuple_control_dependency_1_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_candidate_kernel_Momentum_0 [ready ranks: 5, 6, 4, 7], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_18_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_fully_conn_weights_0 [ready ranks: 5, 6, 4, 7], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_11_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_gates_bias_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_gates_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_gates_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_candidate_kernel_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_candidate_kernel_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_global_step_0 [ready ranks: 6, 5, 7, 4], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_gates_bias_0 [ready ranks: 5, 6, 7, 4], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_candidate_bias_Momentum_0 [ready ranks: 4, 6, 7, 5], HorovodBroadcast_conv2d_biases_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_candidate_bias_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_fully_conn_weights_Momentum_0 [ready ranks: 7, 4, 6, 5], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_2_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_candidate_bias_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_gates_kernel_0 [ready ranks: 4, 7, 5, 6], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_candidate_bias_Momentum_0 [ready ranks: 5, 4, 6, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_candidate_bias_0 [ready ranks: 5, 6, 4, 7], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_41_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_gates_bias_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_candidate_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_gates_bias_Momentum_0 [ready ranks: 5, 4, 6, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_gates_kernel_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_gates_bias_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_candidate_kernel_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_candidate_bias_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_candidate_bias_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_conv2d_weights_0 [ready ranks: 5, 6, 7, 4], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_candidate_kernel_0 [ready ranks: 5, 7, 6, 4], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_gates_kernel_0 [ready ranks: 5, 6, 7, 4], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_22_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_gates_bias_0 [ready ranks: 5, 4, 7, 6], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_candidate_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_fully_conn_biases_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_gates_kernel_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_gates_bias_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_3_gru_cell_candidate_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_gates_kernel_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_fully_conn_biases_Momentum_0 [ready ranks: 5, 7, 6, 4], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_gates_bias_Momentum_0 [ready ranks: 6, 4, 7, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_gates_bias_Momentum_0 [ready ranks: 5, 4, 7, 6], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_44_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_31_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_gates_kernel_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_candidate_kernel_Momentum_0 [ready ranks: 5, 4, 6, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_gates_kernel_Momentum_0 [ready ranks: 6, 7, 4, 5], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_0_gru_cell_candidate_bias_0 [ready ranks: 7, 5, 6, 4], HorovodBroadcast_conv2d_biases_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_gates_kernel_0 [ready ranks: 5, 6, 4, 7], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_conv2d_Conv2D_grad_tuple_control_dependency_1_0 [ready ranks: 3, 2, 1, 0], DistributedMomentumOptimizer_Allreduce/HorovodAllreduce_gradients_AddN_14_0 [ready ranks: 3, 2, 1, 0], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_2_gru_cell_gates_bias_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_conv2d_weights_Momentum_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_candidate_bias_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_1_gru_cell_candidate_kernel_0 [ready ranks: 5, 6, 4, 7], HorovodBroadcast_rnn_bidirectional_rnn_fw_multi_rnn_cell_cell_4_gru_cell_candidate_bias_0 [ready ranks: 5, 6, 4, 7]



2. the code to restore from checkpoints is just thus

ckpt = tf.train.get_checkpoint_state(FLAGS.checkpoint_dir)
saver.restore(sess, ckpt.model_checkpoint_path)

**Comment by gururao001** [comment]
Also to store checkpoints I am using 
 if iters % 100 == 0 and hvd.rank() == 0:
        saver.save(sess, os.path.join(FLAGS.checkpoint_dir, 'checkpoint-%s') % str(iters))

**Comment by alsrgv** [comment]
@gururao001, do you do `broadcast_global_variables` on all ranks?  Seems that ranks 4-7 want to broadcast, but rank 0-3 already want to do training.

**Comment by gururao001** [comment]
@alsrgv so I have the same script copied in both servers and I do the following  
bcast = hvd.broadcast_global_variables(0)
sess.run(bcast)
Also do I have to store checkpoints in both the server?

**Comment by alsrgv** [comment]
@gururao001, you can restore from the checkpoint on rank 0, and then execute broadcast.  That will set weights on all workers.

**Comment by gururao001** [comment]
@alsrgv thanks, man! It works!  Also one more thing I can fit 80 batch size on one server with 4 GPUs but when I scale to multiple servers I cant linearly scale the batch size. I cant fit 160 two servers with same configuration and same GPUs' . What might be the reason?

**Comment by alsrgv** [comment]
@gururao001, I assume you're talking about global batch size, i.e. batch size per GPU * number of GPUs.  Can you try reducing the batch size by 10% and see if it helps?  NCCL may be occupying a little bit of GPU space.

**Comment by vitalyli** [comment]
Hi @alsrgv Is there any example how to restore from Tensorflow checkpoint? I'm trying to restore it using a custom hook, like this one, which errors, see error below: 

    class MyRestoreCheckpointHook(SessionRunHook):
        def __init__(self, rank, checkpoint):
            super(MyRestoreCheckpointHook, self).__init__()
            self.rank = rank
            self.checkpoint = checkpoint

        def begin(self):
            """Called once before using the session."""
            pass

        def after_create_session(self, session, coord):  # pylint: disable=unused-argument
            #session.run([tf.global_variables_initializer()])
            if hvd.rank() == self.rank:
                self.restore_checkpoint()

        def before_run(self, run_context):  # pylint: disable=unused-argument
            return None

        def restore_checkpoint(self):
            if self.checkpoint is not None:
                print("rank %s restoring from checkpoint: %s" % (self.rank,self.checkpoint))
                ckpt = tf.train.get_checkpoint_state(os.path.dirname(self.checkpoint) + "/checkpoint")
                if ckpt and ckpt.model_checkpoint_path:
                    saver = tf.train.Saver(max_to_keep=10, sharded=True)
                    saver.restore(sess, ckpt.model_checkpoint_path)
                    print("restored from checkpoint: %s" % ckpt.model_checkpoint_path)

    hooks = [

        #FIXME: pass checkpoint as parameter
        MyRestoreCheckpointHook(0, "/gpu_data/troika/runs/20180702014654/checkpoint"),

        # Horovod: BroadcastGlobalVariablesHook broadcasts initial variable states
        # from rank 0 to all other processes. This is necessary to ensure consistent
        # initialization of all workers when training is started with random weights
        # or restored from a checkpoint.
        hvd.BroadcastGlobalVariablesHook(0),

        # Horovod: adjust number of steps based on number of GPUs.
        tf.train.StopAtStepHook(last_step=200000000 // hvd.size()),

        tf.train.LoggingTensorHook(tensors={'step': global_step, 'loss': cost}, every_n_iter=100),
    ]

INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: Horovod has been shut down. This has been caused by an exception on one of the rank or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks has finished execution.
         [[Node: HorovodBroadcast_W4_0 = HorovodBroadcast[T=DT_FLOAT, root_rank=0, _device="/job:localhost/replica:0/task:0/device:CPU:0"](W4/read/_157)]]
         [[Node: HorovodBroadcast_W23_Adam_0/_227 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_77_HorovodBroadcast_W23_Adam_0", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'HorovodBroadcast_W4_0', defined at:
  File "/gpu_data/troika/runs/20180702173427/script/tensorflow_pttr_tfrec10.py", line 359, in <module>
    train_main(FLAGS)
  File "/gpu_data/troika/runs/20180702173427/script/tensorflow_pttr_tfrec10.py", line 252, in train_main
    config=config) as sess:
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 405, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 816, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 532, in __init__
    h.begin()
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 127, in begin
    self.bcast_op = broadcast_global_variables(self.root_rank)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 96, in broadcast_global_variables
    for var in tf.global_variables()])
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 96, in <listcomp>
    for var in tf.global_variables()])
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 119, in broadcast
    return MPI_LIB.horovod_broadcast(tensor, name=name, root_rank=root_rank)
  File "<string>", line 94, in horovod_broadcast
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 328, in apply_op
    op_type_name, name, **keywords)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/iad/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

AbortedError (see above for traceback): Horovod has been shut down. This has been caused by an exception on one of the rank or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks has finished execution.
