### ISSUE TITLE
dockerfile need to downgrade cuDNN

### ISSUE THREAD

**Issue by donghwicha** [uber/horovod#203]
if there is anyone who are faced with the error below,

> "Loaded runtime CuDNN library: 7101 (compatibility version 7100) but source was compiled with 7004 (compatibility version 7000). "

The thread below can be pointer to resolve this issue, 
https://github.com/keras-team/keras/issues/9567

and the command lines on the reply below could be added to the dockerfile of the current horovod until Keras supports new version cuDNN.
https://github.com/keras-team/keras/issues/9567#issuecomment-371566669

**Comment by alsrgv** [comment]
It appears that NVIDIA changed their docker file next day after TF 1.6.0 was released, that's why it was not picked up.  I will update the Dockerfile, thanks for the fix!
