### ISSUE TITLE
Unable to run distributed training with two server that both using Anaconda

### ISSUE THREAD

**Issue by traveller59** [uber/horovod#205]
## Environment
Ubuntu 16.04
cuda9.0, cudnn7.0
openmpi with cuda

## Problems
When I run horovod in local environment, every thing is fine, but then I try to run horovod in a remote machine, ```print(sys.version)``` print 'python 2.7' but my Anaconda environment is python 3.6, I have add anaconda path to .bashrc and when I directly use ssh to access remote machine and run python, the python environment is normal(3.6.4).
## command
```
mpirun -np 2  --allow-run-as-root\
    -H server1:1,server2:1 \
    -bind-to none -map-by slot \
    -mca pml ob1 -mca btl ^openib \
    python train_horovod.py
```

**Comment by alsrgv** [comment]
@traveller59, instead of using `python`, can you try using `/path/to/anaconda/bin/python`?  If you're using a custom environment, you may need to activate it in the command, too.

**Comment by ink1** [comment]
You can try
```
mpirun -np 2 -H server1:1,server2:1 which python
```
to find out which python is being picked up.

I'm playing with horovod and really pleased with it. I'm also using anaconda and simply pass env vars
```
mpirun -np 2 -H server1:1,server2:1 -x LD_LIBRARY_PATH -x PATH which python
```

I'm not even using Open MPI with CUDA support, just the one I'd built previously.
Ethernet 10 Gbps, two servers with 4x P100 in each give me 1712s (342ms/step) on the first ImageNet epoch running keras_imagenet_resnet50.py (also cuda 9.0, cudnn 7.0 & nccl 2.1)

Guys, great library!

**Comment by alsrgv** [comment]
Thanks, @ink1!  It's a good idea to pass `-x PATH`, we shall update our docs to include it in sample commands.

**Comment by traveller59** [comment]
Thanks! Now the problem is solved, I use that cnn benchmark with two cloud server(1xP100, 3Gbps) and get 130->180 speed up.
