### ISSUE TITLE
include/socket.h:194 WARN Call to recv failed : Connection reset by peer

### ISSUE THREAD

**Issue by Matrixsun** [uber/horovod#210]
I have  installed  nccl 2 ,   start up the example by:
 mpirun -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib  --mca btl_base_verbose 30   -mca btl_tcp_if_include eth1 -np 8 -H 192.168.189.55:4,192.168.190.74:4  python tensorflow_mnist.py

but ,the model is hang, and the show is : 

ml-gpu-ser015:2123:2230 [3] include/socket.h:194 WARN Call to recv failed : Connection reset by peer
ml-gpu-ser015:2123:2230 [3] INFO transport/net_ib.cu:555 -> 2
ml-gpu-ser015:2123:2230 [3] INFO transport/net_ib.cu:628 -> 2
ml-gpu-ser015:2123:2230 [3] INFO include/net.h:30 -> 2 [Net]
ml-gpu-ser015:2123:2230 [3] INFO include/net.h:38 -> 2 [Net]
ml-gpu-ser015:2123:2230 [3] INFO bootstrap.cu:169 -> 2
ml-gpu-ser015:2123:2230 [3] INFO init.cu:422 -> 2
ml-gpu-ser015:2123:2230 [3] INFO init.cu:542 -> 2

ml-gpu-ser015:2121:2233 [1] include/socket.h:194 WARN Call to recv failed : Connection reset by peer
ml-gpu-ser015:2121:2233 [1] INFO transport/net_ib.cu:555 -> 2
ml-gpu-ser015:2121:2233 [1] INFO transport/net_ib.cu:628 -> 2
ml-gpu-ser015:2121:2233 [1] INFO include/net.h:30 -> 2 [Net]
ml-gpu-ser015:2121:2233 [1] INFO include/net.h:38 -> 2 [Net]
ml-gpu-ser015:2121:2233 [1] INFO bootstrap.cu:169 -> 2
ml-gpu-ser015:2121:2233 [1] INFO init.cu:422 -> 2
ml-gpu-ser015:2121:2233 [1] INFO init.cu:542 -> 2

**Comment by alsrgv** [comment]
@Matrixsun, did you figure it out with `https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-non-routed-network-interfaces`?

**Comment by Matrixsun** [comment]
yeah, I think . but I check it again . when I am sure in my problem I would post it
