### ISSUE TITLE
Error on using hvd.mpi_threads_supported()  error: undefined symbol: mpi_threads_supported

### ISSUE THREAD

**Issue by lkmokadam** [uber/horovod#213]
Error on using hvd.mpi_threads_supported() 

error: undefined symbol: mpi_threads_supported

`mpi_threads_supported = MPI_COMMON_LIB_CTYPES.mpi_threads_supported()`
 should be 
`mpi_threads_supported = MPI_COMMON_LIB_CTYPES.horovod_mpi_threads_supported()`

**Comment by alsrgv** [comment]
Thanks for the report and the fix!
