### ISSUE TITLE
How to use horovod with tensorflow's slim training

### ISSUE THREAD

**Issue by tremblerz** [uber/horovod#220]
In this [models repository](https://github.com/tensorflow/models) session objects are not available explicitly. Any suggestions on how to reconcile horovod with slim's inbuilt model training?

**Comment by alsrgv** [comment]
TF-Slim is rather outdated, I would recommend switching to `MonitoredTrainingSession` or `Estimator` APIs.

If you really want to use Slim, you can pass `session_config` and `init_fn` to [train](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/learning.py) function.

`init_fn` would do something along these lines:
```python
def broadcast_init_fn():
  bcast = hvd.broadcast_global_variables(0)
  return lambda sess: sess.run(bcast)
```

**Comment by tremblerz** [comment]
Thanks for the answer. I agree with the fact that it is outdated. Although, I think aforementioned `models` repository is still widely used to train well known CNN models.

**Comment by YuJingBaoBao** [comment]
Hello,
I am trying to use horovod with tf slim , on 12 GPUs of 3 machines ( 4 GPUs each). The training step runs on 12 GPUs separately , but parameters doesn't copy between GPUs. Do you have any suggestions ? Thanks.
