### ISSUE TITLE
Running Tensorflow with Horovod with Slurm

### ISSUE THREAD

**Issue by abidmalik1967** [uber/horovod#230]
@alsrgv   I am trying to run tf_cnn_benchmarks with Horovod on a cluster. The cluster has 20 GPU nodes with 2 P100 GPUs per node. I am using the following script.

#!/bin/bash -l

#SBATCH -p long
#SBATCH -t 1:00:00
#SBATCH -N 20
#SBATCH -C pascal
#SBATCH --gres=gpu:2
#SBATCH --qos=normal
#SBATCH -o hostname_%j.out

module load openmpi/3.0.0-gnu
module load anaconda2/4.2.0
module load cuda/9.0
module load cuDNN/v7.0-cuda9.0

cd /sdcc/Tensorflow/horovod/benchmarks/scripts/tf_cnn_benchmarks

mpirun -np 40  -npernode 2  python tf_cnn_benchmarks.py --model=resnet50 --batch_size=64 --horovod_device=gpu --num_batches=2000 --print_training_accuracy

The problem is that I am running out of memory. It seems that the system is spawning on few nodes and not distributing properly. The following commands  work in the script.
( with two Nodes)

mpirun -np 2  -npernode 1  python tf_cnn_benchmarks.py --model=resnet50 --batch_size=64 --horovod_device=gpu --num_batches=2000 --print_training_accuracy

(with one node)
mpirun -np 1  -npernode 1  python tf_cnn_benchmarks.py --model=resnet50 --batch_size=64 --horovod_device=gpu --num_batches=2000 --print_training_accuracy

-------
Do I need special flags?  

Also, I got the following output:
w:  1.6
Model:       resnet50
Dataset:     imagenet (synthetic)
Mode:        training
SingleSess:  False
Batch size:  64 global
             64 per device
Num batches: 2000
Num epochs:  0.10
Devices:     ['/gpu:0']
Data format: NCHW
Layout optimizer: False
Optimizer:   sgd
Variables:   parameter_serve

The Horovod uses ring algorithm why I am getting "variables: parameter"?

**Comment by alsrgv** [comment]
@abidmalik1967, try adding `--variable_update horovod` as per https://github.com/uber/horovod/blob/master/docs/benchmarks.md

**Comment by abidmalik1967** [comment]
@alsrgv  I am using the following flags:


mpirun -np 2  -npernode 2 -x LD_LIBRARY_PATH  python tf_cnn_benchmarks.py --model=resnet50 --batch_size=64 --horovod_device=gpu --num_batches=2000 --print_training_accuracy --variable_update horovod
LD_LIBRARY_PATH has the link to NCCL2 library.

Now I can horovod instead of parameter server. It means the library is in action now.

---------
However,
I am getting the following error due to NCCL. I am reproducing part of it.


Running warm up
Running warm up
I0402 06:52:03.083786 47514946534720 tf_logging.py:116] Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.UnknownError'>, ncclAllReduce failed: invalid data type
         [[Node: v0/tower_0/HorovodAllreduce_v0_tower_0_gradients_AddN_1_0 = HorovodAllreduce[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](v0/tower_0/gradients/AddN_1)]]
         [[Node: group_deps_3/_1658 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4523_group_deps_3", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by abidmalik1967** [comment]
@alsrgv  Here are some more information:

ldd `find $HOME/.local/lib/python2.7/site-packages | grep horovod/tensorflow/mpi_lib.so`
	linux-vdso.so.1 =>  (0x00007fffdeffd000)
	libcudart.so.9.0 => /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudart.so.9.0 (0x00002b451442c000)
	libpython2.7.so.1.0 => /hpcgpfs01/software/anaconda2/4.2.0/lib/libpython2.7.so.1.0 (0x00002b451469a000)
	libmpi.so.40 => /hpcgpfs01/software/openmpi/3.0.0-gnu/lib64/libmpi.so.40 (0x00002b4514a94000)
	libtensorflow_framework.so => not found
	libstdc++.so.6 => /hpcgpfs01/software/anaconda2/4.2.0/lib/libstdc++.so.6 (0x00002b4514d8f000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b45150a5000)
	libgcc_s.so.1 => /hpcgpfs01/software/anaconda2/4.2.0/lib/libgcc_s.so.1 (0x00002b45153a7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b45155ba000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b45157d6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b4515b97000)
	librt.so.1 => /lib64/librt.so.1 (0x00002b4515d9c000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00002b4515fa4000)
	libopen-rte.so.40 => /hpcgpfs01/software/openmpi/3.0.0-gnu/lib64/libopen-rte.so.40 (0x00002b45161a8000)
	libopen-pal.so.40 => /hpcgpfs01/software/openmpi/3.0.0-gnu/lib64/libopen-pal.so.40 (0x00002b451645a000)
	libz.so.1 => /lib64/libz.so.1 (0x00002b451675a000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f1aa3d2000)

I don't see any nccllib!!!! I build Horovod with NCCL as stated on the web site.

**Comment by abidmalik1967** [comment]
Also what is 

libmpi.so.40 => /hpcgpfs01/software/openmpi/3.0.0-gnu/lib64/libmpi.so.40 (0x00002b4514a94000)
libtensorflow_framework.so => not found

Why am I getting this?

**Comment by alsrgv** [comment]
@abidmalik1967, `ncclAllReduce failed: invalid data type` is indicative of using the wrong version of NCCL (see troubleshooting [page](https://github.com/uber/horovod/blob/master/docs/troubleshooting.md#ncclallreduce-failed-invalid-data-type)).  If you're using anaconda, can you remove `nccl` package that it may have?

**Comment by abidmalik1967** [comment]
@alsrgv Thanks. I was able to run it on 10 GPU Nodes.  Will try to scale it on bigger machines.
