### ISSUE TITLE
Performance is worse going from 1->2 CPU on word2vec

### ISSUE THREAD

**Issue by ortutay** [uber/horovod#232]
I'm testing out horovod and getting surprising result for the word2vec example. I rand it using 1 CPU and got the following output:

```
$mpirun -np 1 -H HOST_1_IP:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python3 horovod/examples/tensorflow_word2vec.py
Average loss at step  0 :  278.37115478515625  (after 0 sec)
Average loss at step  2000 :  118.12933391666412  (after 3 sec)
Average loss at step  4000 :  55.968544741153714  (after 7 sec)
Average loss at step  6000 :  35.000530384778976  (after 10 sec)
Average loss at step  8000 :  25.225876871585847  (after 14 sec)
Average loss at step  10000 :  18.73096161544323  (after 17 sec)
Average loss at step  12000 :  14.984504812717438  (after 21 sec)
Average loss at step  14000 :  12.163058218836785  (after 24 sec)
```

The "after X sec" is the only change I made to the code.

I then ran it on two nodes, expecting same or better performance. Instead I got this:

```
$ mpirun -np 2 -H HOST_1_IP:1,HOST_2_IP:1 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python3 horovod/examples/tensorflow_word2vec.py
Average loss at step  0 :  273.261962890625  (after 0 sec)
Average loss at step  0 :  297.68731689453125  (after 0 sec)
Average loss at step  2000 :  86.69265195655822  (after 18 sec)
Average loss at step  2000 :  86.28557972884178  (after 18 sec)
Average loss at step  4000 :  30.283855571866034  (after 35 sec)
Average loss at step  4000 :  30.56607323861122  (after 35 sec)
Average loss at step  6000 :  16.98294668459892  (after 52 sec)
Average loss at step  6000 :  16.79783684563637  (after 52 sec)
Average loss at step  8000 :  11.582870275378227  (after 69 sec)
Average loss at step  8000 :  11.758318723201752  (after 69 sec)
```

Note that it takes around 2x longer in terms of clock time to reach the same loss.

Is this expected behavior?

**Comment by ortutay** [comment]
I am running on t2.medium instances on AWS

**Comment by alsrgv** [comment]
hi @ortutay, as mentioned in #228, word2vec example is there to show how to use Horovod with sparse gradients rather than an example with a great scaling.  Amount of work performed per worker is much less than the communication required for synchronization, that's why you see worse performance between nodes.

**Comment by ortutay** [comment]
Thanks @alsrgv for the explanation. Are there any debug outputs that help monitor amount of communication vs. computation to assist with optimizing?

**Comment by alsrgv** [comment]
@ortutay, you can use `top` or `htop` for monitoring CPU utilization, `nvidia-smi` for monitoring GPU utilization and `ethtool -S` for monitoring network utilization.

**Comment by ortutay** [comment]
Thanks @alsrgv
