### ISSUE TITLE
Running Horovod on P3 Instances

### ISSUE THREAD

**Issue by richardliaw** [uber/horovod#238]
Hi, I have a question about running Horovod on AWS P3.16x instances (with the newest DL AMI). 

I understand that these instances offers support for NCCL 2, which advertises multi-node collective communication primitives. 

If I follow these instructions (https://github.com/uber/horovod/blob/master/docs/gpus.md), will object/gradient transfer during training result in CPU involvement? 

Thanks! (If this is the wrong place to ask, would you be so kind to redirect?)

**Comment by alsrgv** [comment]
@richardliaw, this comment may help you - https://github.com/uber/horovod/issues/187#issuecomment-369821478.  If you install with NCCL support, it will use NCCL for all-reduce.  You can use `mpirun` argument `-x NCCL_DEBUG=INFO` to confirm - you should see NCCL debug output.

**Comment by richardliaw** [comment]
Thanks for the reference! So it seems like CPU involvement is avoided. 

Do you know where I can read about the specifics of how the multi-node GPU <-> GPU communication is implemented?

**Comment by alsrgv** [comment]
@richardliaw, I should clarify that since AWS does not have RDMA networking, there will be data transfer between GPU - CPU on the way to NIC:
```
+-------+       +-------+
|  NIC--+--<->--+--NIC  |
|   |   |       |   |   |
|  CPU  |       |  CPU  |
|   |   |       |   |   |
|  GPU  |       |  GPU  |
+-------+       +-------+
```
However, CPU will not be used for the expensive averaging operation.

If RDMA was available, one could bypass CPU with GPUDirect technology:
```
+---------+       +---------+
|  NIC----+--<->--+----NIC  |
| /       |       |       \ |
| |  CPU  |       |  CPU  | |
| \       |       |       / |
|  GPU    |       |    GPU  |
+---------+       +---------+
```

**Comment by richardliaw** [comment]
OK I see, your explanations and diagrams are very helpful. Thanks!
