### ISSUE TITLE
Horovod Timeline

### ISSUE THREAD

**Issue by abidmalik1967** [uber/horovod#244]
I was unable to get the trace. I am getting the following message:

**WARNING: Error opening the Horovod Timeline file /home/amalik/horovod/benchmarks/TRACES/, will not write a timeline.**

I ran with the following command:

 **mpirun -np 6 -H node04:1,node05:1,node06:1,node07:1,node01:1,node02:1 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -x HOROVOD_TIMELINE python  scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model alexnet --batch_size 10 --variable_update horovod**

Where " HOROVOD_TIMELINE" was set to "/home/amalik/horovod/benchmarks/TRACES/".

**Comment by alsrgv** [comment]
@abidmalik1967, you should set `HOROVOD_TIMELINE` to a filename, rather than a directory.  It will write file only on rank 0, so there's no worry about concurrent writes.

**Comment by abidmalik1967** [comment]
@alsrgv Thanks Got. It is a pretty neat stuff.
