### ISSUE TITLE
How to analyze timeline log with horovod

### ISSUE THREAD

**Issue by scotthuang1989** [uber/horovod#255]
I post this  issue on [stackoverlfow](https://stackoverflow.com/questions/50072398/how-to-analyze-timeline-log-with-horovod), but I found that no horovod tag. so I put it on tensorflow tag and hope I can find more useful advice at here.

After some debug, I found a very extreme situation, the **NEGOTIATE_ALLREDUCE**  takes a lot time. 
NCCL is installed and I have set the **LD_LIBRARY_PATH** correctly. 

Anyone know what's going on?

![image](https://user-images.githubusercontent.com/5325686/39393010-908a304c-4af2-11e8-8b6f-6c56b34ea8af.png)

**Comment by alsrgv** [comment]
@scotthuang1989, `NEGOTIATE_ALLREDUCE` captures the timeline of when each worker sent readiness event for a particular tensor.  If you see this phase take 30 seconds, it means there's a very large imbalance between your workers.  What's your time per iteration on a single GPU?

**Comment by scotthuang1989** [comment]
If I train on local GPUs, it take ~0.03 to finish a batch.    BTW, my latest debug show that if I set my dense device as CPU with this line of code:  `opt = hvd.DistributedOptimizer(opt, device_dense='/cpu:0')`  , learning speed is faster, but is still 2-3 times slower then on local GPU. I check NCCL documentations, according to my understanding, NCCL only speed up training when all GPU is on one node, so if I want train a model on multiple GPUs, maybe CPU as dense device is the right choice?

**Comment by alsrgv** [comment]
@scotthuang1989, 0.03s is pretty low time per batch and may be challenging to scale.  What model are you training, what's your batch size and checkpoint size?  How long does it take to converge?  What kind of NICs do you have?

**Comment by scotthuang1989** [comment]
0.03s is achieved on local GPUs,  if I run it on multiple server. speed is 2 - 3 times slower. I want to find out why. For now, I don't analyze the converge speed. just focus on how fast it can run on GPUs.  here my NICs:  for now, the read and write speed is around 400M/s, just half of its capabiltiy, So I think NICs should not be the bottleneck.

> Settings for enp2s0f0:
> 	Supported ports: [ TP ]
> 	Supported link modes:   100baseT/Full 
> 	                        1000baseT/Full 
> 	                        10000baseT/Full 
> 	Supported pause frame use: Symmetric
> 	Supports auto-negotiation: Yes
> 	Advertised link modes:  100baseT/Full 
> 	                        1000baseT/Full 
> 	                        10000baseT/Full 
> 	Advertised pause frame use: Symmetric
> 	Advertised auto-negotiation: Yes
> 	Speed: 10000Mb/s
> 	Duplex: Full
> 	Port: Twisted Pair
> 	PHYAD: 0
> 	Transceiver: internal
> 	Auto-negotiation: on
> 	MDI-X: Unknown

**Comment by alsrgv** [comment]
@scotthuang1989, you need to collect millisecond-level profile from NIC to see bottlenecks.  10 Gbit/s is not great for distributed training.  You may see something similar to:

![image](https://user-images.githubusercontent.com/16640218/39482802-4885711e-4d25-11e8-908e-8598db4ac38e.png)

In this case, average utilization is below 25 Gbit/s, but it's actually getting bottlenecked by network half of the time.

You may still get better total throughput than a single server by throwing >4 servers at the problem - but it's pretty wasteful.

**Comment by scotthuang1989** [comment]
@alsrgv  sorry for late response. Just got stuck on others thing.  I try to measure network speed with `nload` , the max speed is amlost 1.5 - 2 times then average. the network is indeed the bottleneck. BTW, how to you generate the nice graph, I can find a tool to do that.

**Comment by alsrgv** [comment]
@scotthuang1989, no problem!  We captured information using `ethtool`:

```
while sleep .001; do printf '%s %s\n' "$(date '+%s%3N')" "$(ethtool -S eth0 | grep 'rx_bytes\|tx_bytes' | xargs)"; done >> ethtool.txt
```

And then render using Jupyter Notebook + matplotlib.

**Comment by scotthuang1989** [comment]
@alsrgv  thanks for your support, it is really helpful.

**Comment by denfromufa** [comment]
@alsrgv is there any equivalent of ethtool, but not for NIC, instead for PCIE switch/fabric within a node between CPUs and GPUs?
