### ISSUE TITLE
Do we have official docker image in docker hub?

### ISSUE THREAD

**Issue by cheyang** [uber/horovod#261]

**Comment by alsrgv** [comment]
@cheyang, not yet - but we are working on it :-)

**Comment by alsrgv** [comment]
@cheyang, we have added images on docker hub:  https://hub.docker.com/r/uber/horovod/

Latest are:
* Python 2.7 - uber/horovod:0.12.1-tf1.8.0-py2.7
* Python 3.5 - uber/horovod:0.12.1-tf1.8.0-py3.5
