### ISSUE TITLE
Order of broadcast ops' evaluation

### ISSUE THREAD

**Issue by zuowang** [uber/horovod#27]
./horovod/tensorflow/__init__.py:89
```
return tf.group(*[tf.assign(var, broadcast(var, root_rank))
                      for var in tf.global_variables()])
```
@alsrgv I think we can't make sure  that the broadcast ops are evaluated by TensorFlow in the same order for each instance for all platform. Do you think so?

**Comment by alsrgv** [comment]
Hi @zuowang,

You are right - there's no guarantee about op order in this case. We have another layer of orchestration that runs before we invoke collective ops to avoid mixing up different tensors.

The way it works is:
> Rank 0 maintains the registry of tensors that are ready to be broadcasted/reduced. All other processes send a signal to Rank 0 when they’re ready to broadcast/reduce each tensor, and Rank 0 sends back commands to start broadcast/reduce.

**Comment by zuowang** [comment]
I have found the related code. Thanks a lot! BTW, the order can also be guaranteed  with the use of tf.control_dependencies() statement.

**Comment by jianyinglang** [comment]
@zuowang Thanks for the post! Would you mind share me some example of using tf.control_dependencies()?
