### ISSUE TITLE
DistributedOptimizer cannot be used when underlying optimizer overwrites compute_gradients and apply_gradients

### ISSUE THREAD

**Issue by Kipok** [uber/horovod#273]
In our use case we have a TensorFlow optimizer that explicitly defines `compute_gradients` and `apply_gradients` functions. The current version of `DistributedOptimizer` cannot be used in our case because it does not overwrite `apply_gradients` to use` self._optimizer.apply_gradients` and it calls (lines 178-179 of `horovod/tensorflow/__init__.py`)
```python
gradients = super(DistributedOptimizer, self).compute_gradients(*args, **kwargs)
```
instead of `gradients = self._optimizer.compute_gradients(*args, **kwargs)`.

Is it possible to update `DistributedOptimizer` to work in our use case and similar situations when `compute_gradients` and `apply_gradients` are redefined? As far as I can see simply changing lines 178-179 of `horovod/tensorflow/__init__.py` to 
```python
gradients = self._optimizer.compute_gradients(*args, **kwargs)
```
and adding additional method:
```python
  def apply_gradients(self, grads_and_vars, global_step=None, name=None):
    """Calls this same method on the underlying optimizer."""
    return self._optimizer.apply_gradients(grads_and_vars, global_step, name)
```
should make it work.

**Comment by alsrgv** [comment]
@Kipok, I've pushed the change to re-wrap optimizer in a way you proposed in the branch `wrapped_tf_optimizer`.  [The change](https://github.com/uber/horovod/commit/b4e1816649b7b0297f839b40e821e812e582c15a) should simplify the wrapping logic quite a bit.  Can you verify that it works for your use case?

You can install it via:
```
$ <flags> pip install -v git+https://github.com/uber/horovod@wrapped_tf_optimizer
```

**Comment by Kipok** [comment]
Yes, now everything works, thanks for the quick fix!
