### ISSUE TITLE
PyTorch MNIST example spawns multiple processes in the same GPU

### ISSUE THREAD

**Issue by Sroy20** [uber/horovod#287]
Hi,

Thanks for the awesome package. I was trying to play around with the PyTorch MNIST example. I have a server with 2 K80s i.e. 4 GPUs and previously I have successfully used Horovod to run Keras programs on them. 

However, when I ran the PyTorch program, it spawned 4 processes on GPU 0 and none on the other 3. Screenshots to explain things better:

1. First I ran "python main.py" and nvidia-smi shows that 23% of GPU 0 is being used:
<img width="535" alt="screen shot 2018-06-02 at 11 48 25 pm" src="https://user-images.githubusercontent.com/20379348/40877179-b9cd9618-66bf-11e8-9847-cf7f6af8b867.png">

2. Second I ran "mpirun -np 4 python main.py"  and this is the output of nvidia-smi. I reckon it started 4 processes on GPU 0.
<img width="536" alt="screen shot 2018-06-02 at 11 48 51 pm" src="https://user-images.githubusercontent.com/20379348/40877176-a8859a22-66bf-11e8-9671-8830bb3bfe64.png">

I have also ran the following but it shows similar output as above:

mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib python main.py

To confirm this hypothesis, I printed the value of hvd.local_rank() and it showed 0 four times on terminal. In contrast, printing hvd.local_rank() for the Keras example shows 0, 1, 2, and 3 in no particular order as expected.

I would appreciate any help with this. Thanks and cheers!

**Comment by alsrgv** [comment]
@Sroy20, this is fairly strange. The code path dealing with `hvd.local_rank()` is actually shared among Keras and PyTorch.

Do you see the same issue when running the https://github.com/uber/horovod/blob/master/examples/pytorch_mnist.py example?

What if you run this simple program, what is the output?
```
$ cat > test_local_rank.py
import horovod.torch as hvd
hvd.init()
print(hvd.local_rank())
$ mpirun -np 2 python test_local_rank.py
1
0
```

**Comment by Sroy20** [comment]
Hi @alsrgv 

Thanks for your quick reply. Yes, actually that was the example (pytorch_mnist.py) I was renamed. I just renamed it to main.py in my case.

I ran the simple program in my PyTorch environment and here is the output:
<img width="488" alt="screen shot 2018-06-03 at 11 29 03 am" src="https://user-images.githubusercontent.com/20379348/40882307-639630a4-6721-11e8-8f81-3637aaa56d87.png">

It shows two 0s. Moreover, I also tried to run this in my Keras environment by changing "import horovod.torch as hvd" to "import horovod.keras as hvd" and unlike the PyTorch output it shows 0 and 1. So this seems to be consistent with the issue I faced.

**Comment by alsrgv** [comment]
@Sroy20, what's the output of `pip freeze` in your PyTorch and Keras environments?

**Comment by Sroy20** [comment]
Hi @alsrgv 

Here is the output of pip freeze in the PyTorch environment:
<img width="538" alt="screen shot 2018-06-03 at 12 46 53 pm" src="https://user-images.githubusercontent.com/20379348/40882657-317bb340-672c-11e8-9bc9-9c7703c807b2.png">

And here is the output of the same command in my Keras environment:
<img width="541" alt="screen shot 2018-06-03 at 12 47 09 pm" src="https://user-images.githubusercontent.com/20379348/40882659-40713d66-672c-11e8-941f-4261a0346812.png">

Thanks,
Subhrajit

**Comment by Sroy20** [comment]
@alsrgv Thanks for helping out! Here you go:

For PyTorch environment:
<img width="522" alt="screen shot 2018-06-03 at 2 49 34 pm" src="https://user-images.githubusercontent.com/20379348/40883354-b3a09316-673d-11e8-8535-029aab25d769.png">
<img width="510" alt="screen shot 2018-06-03 at 2 50 22 pm" src="https://user-images.githubusercontent.com/20379348/40883355-bd892082-673d-11e8-8356-2d8ebf1526b0.png">

For Keras environment:
<img width="487" alt="screen shot 2018-06-03 at 2 49 47 pm" src="https://user-images.githubusercontent.com/20379348/40883358-c5d4c976-673d-11e8-9da3-3d4ea1e2c4c5.png">
<img width="482" alt="screen shot 2018-06-03 at 2 50 45 pm" src="https://user-images.githubusercontent.com/20379348/40883359-ce4575d8-673d-11e8-8363-f3f73c2a94d9.png">

**Comment by alsrgv** [comment]
@Sroy20, let's try the basics. What's the output of:
1. `ldd /path/to/conda/envs/pytorch/lib/python3.6/site-packages/horovod/common/mpi_lib.cpython-36m-x86_64-linux-gnu.so`
2. `ldd /path/to/conda/envs/tf_py36/lib/python3.6/site-packages/horovod/common/mpi_lib.cpython-36m-x86_64-linux-gnu.so`
3. `mpirun -np 4 bash -c 'echo $OMPI_COMM_WORLD_LOCAL_RANK'` (in both environments)

**Comment by alsrgv** [comment]
@Sroy20, now I see your problem and I was able to reproduce :-)

If you look at the list of libraries, you have `libmpi` pointing to MPICH.  However, when you run the script you're using Open MPI.  Since MPICH does not know about Open MPI, it thinks that you just start 4 separate "python main.py" processes, that's why each of them gets `rank` = 0.

Assuming `which mpicxx` points to `/usr/local/bin/mpicxx`,  can you just reinstall Horovod in PyTorch environment?

**Comment by Sroy20** [comment]
@alsrgv Yes, it works after reinstalling Horovod! You are a champ - thank you so much!

**Comment by hdubey** [comment]
I m having the same issue and re-installing horovod did not helped. In my case, I have conda installation in home directory and I do not use virtual enviroment. hvd.mpi_threads_supported() return false. I have horovod with pytorch and openmpi 1.10. Can we use intel-MPI for better/faster performance.

**Comment by discort** [comment]
@alsrgv 
Have exactly the same problem:

```
$ which mpirun
/usr/local/bin/mpirun

$ mpirun --version
mpirun (Open MPI) 4.0.1

$ mpirun -np 4 bash -c 'echo $OMPI_COMM_WORLD_LOCAL_RANK'
0
1
2
3
```

horovod==0.22.1 built with:
```
export HOROVOD_WITH_PYTORCH=1 
export HOROVOD_GPU_OPERATIONS=NCCL
```



Ran using:
```
horovodrun -np 4 python -m main.py
```

```
(.env) discort@cloud-4:~/package$ ldd .env/lib/python3.8/site-packages/horovod/torch/mpi_lib_v2.cpython-38-x86_64-linux-gnu.so
    linux-vdso.so.1 =>  (0x00007ffe093fc000)
    libmpi.so.40 => /usr/local/lib/libmpi.so.40 (0x00007fa3a2411000)
    libcudart.so.10.1 => /usr/local/cuda-10.1/lib64/libcudart.so.10.1 (0x00007fa3a2195000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa3a1f91000)
    libc10.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libc10.so (0x00007fa3a1cfa000)
    libtorch.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch.so (0x00007fa3a1ae6000)
    libtorch_cpu.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so (0x00007fa38f9ca000)
    libtorch_python.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_python.so (0x00007fa38e5e7000)
    libc10_cuda.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libc10_cuda.so (0x00007fa38e3b7000)
    libtorch_cuda.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libtorch_cuda.so (0x00007fa35289a000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa35267d000)
    libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa352299000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa351f90000)
    libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa351d78000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa3519ae000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fa3b0bc7000)
    libopen-rte.so.40 => /usr/local/lib/libopen-rte.so.40 (0x00007fa3516f1000)
    libopen-pal.so.40 => /usr/local/lib/libopen-pal.so.40 (0x00007fa3513dc000)
    librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa3511d4000)
    libgomp-a34b3233.so.1 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libgomp-a34b3233.so.1 (0x00007fa350faa000)
    libcudart-1b201d85.so.10.1 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libcudart-1b201d85.so.10.1 (0x00007fa350d2b000)
    libshm.so => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libshm.so (0x00007fa350b24000)
    libnvToolsExt-3965bdd0.so.1 => /home/discort/package/.env/lib/python3.8/site-packages/torch/lib/libnvToolsExt-3965bdd0.so.1 (0x00007fa35091a000)
    libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa350700000)
    libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fa3b0da4000)
    libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fa3504fd000)
```

However, 
<img width="650" alt="Screenshot 2021-07-14 at 13 04 18" src="https://user-images.githubusercontent.com/4944021/125604927-3aa66a4f-33dd-4710-89a1-4220d83cdcd4.png">

Any ideas how to tackle that?
