### ISSUE TITLE
mpirun error when running tensorflow_mnist.py with multiple processes

### ISSUE THREAD

**Issue by gtbai** [uber/horovod#298]
Hi all,

I was trying to run one of the example tensorflow script with multiple processes on my mbp, but met an mpirun error when I do that. Here is the error message I got:

```
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node tw-mbp-gbai exited on signal 4 (Illegal instruction: 4).
--------------------------------------------------------------------------
```

 The bash script I run is as follows:
```bash
mpirun -np 2 \
    --output-filename output \
    -H localhost:2 \
    -bind-to none -map-by slot \
    python tensorflow_mnist.py
```
And after the job terminated, there is nothing in the ```stdout``` and ```stderr``` file of all ranks.

The version of Open MPI I have on my mbp (returned by running ```mpirun --version```) is:
```
mpirun (Open MPI) 3.1.0
```
And version of tensorflow and horovod are (returned by running ```pip show tensorflow horovod```):
```
Name: tensorflow
Version: 1.8.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: astor, protobuf, gast, tensorboard, six, wheel, absl-py, backports.weakref, termcolor, enum34, numpy, grpcio, mock
Required-by:
---
Name: horovod
Version: 0.13.3
Summary: Distributed training framework for TensorFlow, Keras, and PyTorch.
Home-page: https://github.com/uber/horovod
Author: Uber Technologies, Inc.
Author-email: UNKNOWN
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: cffi
Required-by:
``` 

There is no NVIDIA GPUs on my mbp, so no CUDA/cuDNN/NCCL are installed.

In addition, I made sure that I could do ```ssh localhost``` without any password prompt, and when I run ```python tensorflow_mnist.py```, no issues are found.

Any suggestion or help is greatly appreciated.

**Comment by gtbai** [comment]
To follow up, I modified the ```tensorflow_mnist.py``` script a bit by adding some debug print statements in ```main()```, before and after ```hvd.init()```, like follows:

```python
def main(_):
    
    print "in main()"

    # Horovod: initialize Horovod.
    hvd.init()
    
    print "after init()"

    # Download and load MNIST dataset.
    mnist = learn.datasets.mnist.read_data_sets('MNIST-data-%d' % hvd.rank())

    ...
```

And "in main()" did get printed twice in the terminal, while "after init()" never got printed. Seems like there is some issue with the "hvd.init()" statement.

Did I miss something with my installation?

**Comment by alsrgv** [comment]
@gtbai, try running with `-mca btl ^tcp`. For some reason, Open MPI TCP fails on MBP.

**Comment by gtbai** [comment]
@alsrgv Thanks a lot, that works!

By the way, does this happen for Linux/Ubuntu as well?

**Comment by alsrgv** [comment]
@gtbai, no - on Linux it works fine.  I'm not sure why it fails, but I'm quite confident that Open MPI folks would be super happy to take a PR that would fix it :-)

**Comment by gtbai** [comment]
I see ;-).
Thanks for the help, and I would close this issue.

**Comment by lgarithm** [comment]
I did some investigation in the openmpi source code, and found the line that crashed. 
@alsrgv do you have an issue against https://github.com/open-mpi/ompi where I can share my findings.

**Comment by alsrgv** [comment]
@lgarithm, great!  I see that it got traction already.
