### ISSUE TITLE
clipping norm of compute_gradients

### ISSUE THREAD

**Issue by ankurhanda** [uber/horovod#303]
```
self.trainer = tf.train.AdamOptimizer(learning_rate=self.adam_lr, epsilon=self.adam_epsilon)

self.hvd_trainer = hvd.DistributedOptimizer(self.trainer)

self._grads = self.hvd_trainer.compute_gradients(self.total_loss, self.var_list)

self.adam_grads_and_vars = [zip([tf.clip_by_norm(mygrad, clip_norm=clip_norm) for mygrad in grad], var)
                                        for (grad, var) in self._grads]

self.adam_op = self.hvd_trainer.apply_gradients(self.adam_grads_and_vars)
```

This gives me error ```File "/home/libs/pyenv/versions/3.5.5/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 400, in __iter__
    "Tensor objects are not iterable when eager execution is not "
TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.```

I'd like to average gradients but clip the gradients (computed via compute_gradients) by norm as well. Could you please help me with it? I guess I'm wondering if there a way to clip every element of the list in grad - `tf.gradients` returns list of grads while horovod `compute_gradient` returns list of `(grad, var)` but this grad is further a tensor not a list so it cannot be iterated. 

On a single GPU I do it this way 
```
 _grads = tf.gradients(self.total_loss, var_list)
 
grads = [tf.clip_by_norm(grad, clip_norm=clip_norm) for grad in _grads]

self.adam_grads_and_vars = list(zip(self.cur_grads, var_list))

self.trainer = tf.train.AdamOptimizer(learning_rate=self.adam_lr, epsilon=self.adam_epsilon)

self.adam_op = self.trainer.apply_gradients(self.adam_grads_and_vars)

```
I'd like to do exactly this over multiple GPUs. 

BTW, this has an example but it is `tf.clipping_by_global_norm` but I want `tf.clipping_by_norm` https://github.com/uber/horovod/issues/141#issuecomment-356852801

**Comment by alsrgv** [comment]
@ankurhanda, the way your code is structured, you'll first average gradients, and then clip the result - would that work for you?

I believe your code can be fixed by replacing:
```python
self.adam_grads_and_vars = [zip([tf.clip_by_norm(mygrad, clip_norm=clip_norm) for mygrad in grad], var)
                                 for (grad, var) in self._grads]
```

With:
```python
self.adam_grads_and_vars = [(tf.clip_by_norm(grad, clip_norm=clip_norm), var)
                            for (grad, var) in self._grads]
```
