### ISSUE TITLE
Something unexpected in timeline

### ISSUE THREAD

**Issue by roastduck** [uber/horovod#316]
I think each Allreduce op in the timeline should have exactly 2 lines: NEGOTIATE_ALLREDUCE or ALLREDUCE above, and specific operations below. But I got 4 lines from time to time. See the image.

![image](https://user-images.githubusercontent.com/6522983/41496575-748ca268-7175-11e8-844e-efb7aa4069ff.png)

There's a NEGOTIATE_ALLREDUCE phase inside ALLREDUCE phase. Is it normal or a bug? Running with v0.13.4.

**Comment by alsrgv** [comment]
@roastduck, this is quite interesting. Could you share your timeline?  I'm surprised to see next negotiation to start before the last iteration ended, are you trying to do 1-late SGD or something along those lines?

**Comment by roastduck** [comment]
[timeline_decomp.zip](https://github.com/uber/horovod/files/2108635/timeline_decomp.zip)

Here's the timeline file.

I'm doing data parallelism with strong consistency, not 1-late SGD.

Please don't be confused with that `v0/tower_0/HorovodAllreduce_v0_tower_0_HorovodAllgather_v0_tower_0_cg_Reshape_0_0` op. I'm just doing allgather using allreduce (padding 0 then perform allreduce), because there's no NCCL support for allgather.

**Comment by roastduck** [comment]
Plus: I merged `fp16_divide_before_sum` branch to use fp16 allreduce.

**Comment by alsrgv** [comment]
@roastduck, do you get better performance with this padded allreduce than a simple MPI allgather that is supported?  Since allgather is focused on data transmission rather than computing sum, I think there should be less benefit of running it on GPU.

**Comment by roastduck** [comment]
As described in `docs/running.md`, if I use RDMA for allreduce (with NCCL), I cannot use RDMA for allgather (with MPI) then. So I think this padded allreduce is better, because it's using RDMA. Am I right?

**Comment by alsrgv** [comment]
@roastduck, it's not entirely true - while MPI will not do GPU-to-GPU RDMA, it can still do GPU->CPU->RDMA->CPU->GPU which is still offloading the data transfer to NIC.  Which MPI & NIC are you using?

Regardless, you are still likely to get a lot of benefit from using allgather because of its simplicity.  Did you try to compare the performance of both approaches?

**Comment by roastduck** [comment]
@alsrgv, I'm confused with the word

> `-mca pml ob1` and `-mca btl ^openib` flags force the use of TCP for MPI communication. This avoids many multiprocessing issues that Open MPI has with RDMA which typically result in segmentation faults. Using TCP for MPI does not have noticeable performance impact since most of the heavy communication is done by NCCL, which will use RDMA via RoCE or InfiniBand if they're available

in `docs/running.md`. Is MPI truly uses RDMA in this scenario?

**Comment by alsrgv** [comment]
@roastduck, can you share how much is padded NCCL allreduce over RDMA numerically better than MPI allgather over TCP? 5%, 10%, 50%?

Instructions we have for Open MPI indeed disable RDMA for MPI.  The reason for that is that default OpenIB BTL doesn't work with multi-threading.  I've just pushed a branch / PR that includes a flag that allows you to disable threading: https://github.com/uber/horovod/pull/324

If you merge that PR in your working copy, you can use MPI RDMA by removing `-mca btl ^openib` and adding `-x HOROVOD_MPI_THREADS_DISABLE=1`.  Can you try that and report whether that improves MPI allgather performance?

**Comment by roastduck** [comment]
@alsrgv, Sorry for saying padded allreduce gains some performance, which was wrong. This result came from testing a complete DNN model, where there are too many influence factors for performance.

This time, I did a dedicated test for allgather. I performed allgather on 10^9 float32 items, using EDR IB. See below:

Method| Negotiation (ms) | Transmission (ms) | Total (ms) 
--|--|--|--
Original | 1121.820 | 12314.193 | 13436.013
Padded allreduce | 1641.637 | 21470.863 | 23112.500 
PR #324 | 1049.802 | 4173.146 | 5222.948

Padded allreduce is actually slower, and MPI RDMA is much faster.

**Comment by alsrgv** [comment]
@roastduck, how many allgathers did you do for this test?  The first operation can have an overhead of setting things up, especially in case of NCCL.  Can you quantify how much your own model training is faster with padded allreduce?

**Comment by alsrgv** [comment]
@roastduck, can you start measuring time after the first iteration completes?  Otherwise, variability during startup can cause these numbers to be very random.

You can also try playing with `-x HOROVOD_CYCLE_TIME=[...]` environment variable which dictates delay between Horovod cycles, as described in https://github.com/uber/horovod/blob/master/docs/tensor-fusion.md.  The default value is `5`, which means 5 millisecond delay.  I suspect that padded allreduce may simply make one of the cycles longer.  You can try increasing and decreasing the value to find potentially better performance.

**Comment by roastduck** [comment]
@alsrgv, I made a mistake. I forgot to enable RDAM in MPI before performing the 3rd test above. Now it's fixed.

Here's the timing of the last 9 of the 10 allgathers in previous experiments. It doesn't vary much.

Method | Total negotiation + transmission time (ms) 
---|---
Original | 12266.511
Padded allreduce | 34251.899
PR #324 | 2465.120

I did the measurement by summing up all the bars in the timeline result.

**Comment by roastduck** [comment]
Since you mentioned fusion, I guess my model might benefit from fuse the allgathers, which are actually padded allreduces, with other normal allreduces. I observed that this type of fusion really happened. This might explain why padded allreduce performs better in my model.

**Comment by alsrgv** [comment]
@roastduck, ah - these new numbers are much better.  What if you try disabling fusion for your real model, do you see performance degradation of the padded allreduce?  Sounds like we should add fused allgather.

**Comment by alsrgv** [comment]
@roastduck, sounds like what you're doing is best for your model then :-)

**Comment by anpark** [comment]
very interesting discuss.

why not try ncclallgather? i'll try it

**Comment by roastduck** [comment]
@anpark, I found [snuspl's fork](https://github.com/snuspl/horovod) tried to add NCCL allgather support, but it doesn't perform well. You may take a look.

**Comment by anpark** [comment]
@roastduck  i'm doing this now.

by timeline i found two big performance problem:

new/delete for large buffer not efficiency, for example allgather, 300M buffer new/delete will cost much time, so should use buffer pool
mpi_allgather should change to ncclallgather, in my test, mpi_allgather too slow for large buffer
