### ISSUE TITLE
horovod crashes on OSX

### ISSUE THREAD

**Issue by lgarithm** [uber/horovod#319]
Hi, I'm trying to run a simple hello world program `horovod-helloworld.py` on OSX

```python
#!/usr/bin/env python3
import horovod.tensorflow as hvd
hvd.init()
```

and it crashed immediately 

```
mpiexec -np 2 ./horovod-helloworld.py
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node matrix exited on signal 4 (Illegal instruction: 4).
```

I found that this is caused by calling `MPI_Init_thread` in a thread, which happened in `InitializeHorovodOnce`.

The following program could be used to reproduced the bug:
```cpp
#include <thread>

#include <mpi.h>

static void BackgroundThreadLoop()
{
    int provided;
    MPI_Init_thread(nullptr, nullptr, MPI_THREAD_MULTIPLE, &provided);
}

int main(int argc, char *argv[], char *envp[])
{
    bool use_thread = true;
    if (use_thread) {
        // crashed
        auto th = std::thread(BackgroundThreadLoop);
        th.join();
    } else {
        // not crash
        BackgroundThreadLoop();
        // MPI_Init(nullptr, nullptr);
    }
    MPI_Finalize();
    return 0;
}
```

**Comment by alsrgv** [comment]
@lgarithm, can you try running your test with `-mca btl ^tcp`?  #298 covers similar (if not identical) issue.

**Comment by lgarithm** [comment]
@alsrgv, I've tested with `-mca btl ^tcp` and it worked.
I'm sure that this is identical to #298.

**Comment by GwinSalbor** [comment]
Hi, i have no idea, but your solution didn't solve my problem
![image](https://user-images.githubusercontent.com/28218333/54439530-06475180-474a-11e9-9235-31fd44f5c12b.png)

**Comment by alsrgv** [comment]
@GwinSalbor, can you try the latest version of Open MPI 4.0.0?  It should work without `-mca btl ^tcp`.

**Comment by GwinSalbor** [comment]
I already use the latest version of MPI 
![image](https://user-images.githubusercontent.com/28218333/54522955-768ae880-497f-11e9-870b-f5b30a9a0b27.png)

**Comment by alsrgv** [comment]
@GwinSalbor, is that a Mac? This question is specifically about OSX.

**Comment by GwinSalbor** [comment]
oh sorry,  i'm working with ubuntu.

**Comment by alsrgv** [comment]
@GwinSalbor, could you open a new question ticket and fill out questionnaire about your environment?

**Comment by GwinSalbor** [comment]
https://github.com/horovod/horovod/issues/926
