### ISSUE TITLE
Question about FP16 data to do the hvd.allreduce?

### ISSUE THREAD

**Issue by hewei1990102** [uber/horovod#326]
We have a question when using FP16 to do hvd.allreduce in our experiment. As number of GPU increasing, the scaling efficiency of resnet50 decreases significantly from 91% (32 GPU) to 52% (256 GPU).

But if cast the data from FP16 to FP32:
`hvd.allreduce(tf.cast(grad,tf.float32), device_dense=horovod_device)`
The scaling efficiency will remain at around 90%, no matter how many GPU.

Our Environment：
GPU：P40
NVIDIA：390.46
Cuda：9.0
Cudnn：7.0
TensorFlow：1.8
NCCL：2.2.12
Openmpi：3.0.1

**Comment by alsrgv** [comment]
@hewei1990102, are you using branches from https://github.com/uber/horovod/issues/278, or vanilla installation?

**Comment by alsrgv** [comment]
@cberner, could you try divide-before-sum and share whether convergence rate is different?  Once you hit Inf, there's no way back :-)

**Comment by cberner** [comment]
@alsrgv sure. Will have results from it later tonight / tomorrow

**Comment by cberner** [comment]
@alsrgv no meaningful difference, so I think either version is fine. Can always use `allreduce(average=False)` for people that need to customize which they want

**Comment by alsrgv** [comment]
@cberner, thanks!  That's great.  I'm leaning towards divide-before-sum version because it should be safer.

@hewei1990102, did you make progress with your experiments?

**Comment by hewei1990102** [comment]
@alsrgv The cause of the problem is some GPU machine's PCIe which has bug, we change a new PCI board then the speed is ok.
