### ISSUE TITLE
pytorch_imagenet_resnet50.py gives Possibly corrupt EXIF data.  Expecting to read 2555904 bytes but only got 0. Skipping tag 0

### ISSUE THREAD

**Issue by bapriddy** [uber/horovod#333]
When running pytorch_imagenet_resnet50 (or resnet18) I'm getting the infamous Pillow error

'''1394872 STDOUT (Last Update 2018-06-25 09:15):
Train Epoch     #1:  17% 3438/20019 [26:40<1:59:26,  2.31it/s, loss=6.22, accuracy=1.82] ~.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:739: UserWarning: Possibly corrupt EXIF data.  Expecting to read 2555904 bytes but only got 0. Skipping tag 0
  " Skipping tag %s" % (size, len(data), tag))
Train Epoch     #1:  21% 4270/20019 [33:05<1:56:13,  2.26it/s, loss=6.1, accuracy=2.26] ~.local/lib/python3.6/site-packages/PIL/TiffImagePlugin.py:756: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
  warnings.warn(str(msg))
Train Epoch     #1:  30% 6077/20019 [47:05<1:35:51,  2.42it/s, loss=5.9, accuracy=3.23] 
1394872 STDERR:
(NO STDERR)'''
  Is this because I have a corrupt image in my imagenet data set or some other reason? This seems to be a common issue going back for sometime which has yet to be resolved.

**Comment by alsrgv** [comment]
@bapriddy, those are warnings and can be ignored.  However, in [this thread](http://forums.fast.ai/t/help-needed-pil-corrupt-exif-data/3497/2) there's a bit of discussion about cleaning them up.

**Comment by bapriddy** [comment]
Thanks!!

**Comment by bapriddy** [comment]
One user claims the following about the EXIF issue

This sounds like a compatibility issue between pillow, numpy, etc
I solved the issue by downgrading to Pillow version 4 by below command on anaconda

conda install pillow=4.0.0

My python version is 3.5. This would solve the issue.

It's here
https://github.com/codelucas/newspaper/issues/542

Not sure if this works.

**Comment by bapriddy** [comment]
This is an example of the line of code that fails in TiffImagePlugin.py ...

`if len(data) != size:
                    warnings.warn("Possibly corrupt EXIF data.  "
                                  "Expecting to read %d bytes but only got %d."
                                  " Skipping tag %s" % (size, len(data), tag))
                    continue`

**Comment by KaiyuYue** [comment]
The best solution for this is https://www.kaggle.com/c/intel-mobileodt-cervical-cancer-screening/discussion/31558 .

**Comment by maraoz** [comment]
In case this helps anyone in the future, here's how I removed EXIF data from my dataset:

```
from PIL import Image

file_names = get_image_files(path)

def remove_exif(image_name):
    image = Image.open(image_name)
    exif = image.getexif()
    if (exif):
        print("exif found!", exif)
    else:
        return
    data = list(image.getdata())
    image_without_exif = Image.new(image.mode, image.size)
    image_without_exif.putdata(data)

    image_without_exif.save(image_name)

for file in file_names:
    print('removing EXIF from', file, '...')
    remove_exif(file)
```
