### ISSUE TITLE
Multiple hvd process on same GPUs hang with NCCL enabled

### ISSUE THREAD

**Issue by gongzg** [uber/horovod#335]
Actually the hang is as expected as by default we can't make the multiple kernels to run concurrently on the same GPU device thus it hangs. I just want to know is it possible to still use NCCL in this situation？Thanks.

**Comment by alsrgv** [comment]
@gongzg, I'm afraid you'd have to use MPI in this case.

**Comment by gongzg** [comment]
@alsrgv Thanks for your reply. I did a test on both P100 and M40 which bind multiple tensorflow ranks on the same GPU. And P100 works fine but M40 hangs. Anyway, this issue should be a Nvidia related rather than horovod, I'm going to close it now.
