### ISSUE TITLE
horovod in single node Multi-GPU training

### ISSUE THREAD

**Issue by giranntu** [uber/horovod#34]
Hi professional team,

Is there any possible to use horovod distributed training in Single node Multiple GPU training?

Thanks for the kindly support.

**Comment by alsrgv** [comment]
Hi, @giranntu,

Sure thing! Just follow installation instructions [here](https://github.com/uber/horovod/blob/master/docs/gpus.md) and usage instructions [here](https://github.com/uber/horovod/blob/master/README.md#usage).

Thanks,
Alex

**Comment by alsrgv** [comment]
@giranntu I'll close this issue since it seems that your question was answered.  Please feel free to re-open if you have more questions on this subject or open a new issue for a different subject.
