### ISSUE TITLE
Horovod with NCCL2 and Intel MPI

### ISSUE THREAD

**Issue by msalvaris** [uber/horovod#340]
Hi,

I am currently trying to run the benchmarks using Intel MPI+NCCL2. 

My dockerfile can be found here [https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/mat_dev/Horovod-intel/Docker/dockerfile ](https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/mat_dev/Horovod-intel/Docker/dockerfile ) is based on the Horovod dockerfile except that it installs intel mpi rather than open mpi. At the moment the process seems to hang with the final output being:
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] misc/ibvwrap.cu:235 WARN Call to ibv_query_gid failed with error Unknown error -1
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] INFO transport/net_ib.cu:453 -> 2
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] INFO include/net.h:32 -> 2 [Net]
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] INFO transport/net.cu:266 -> 2
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] INFO init.cu:475 -> 2
4c9d2659524a436086fb2f14ff1bd1cd000001:862:969 [3] INFO init.cu:536 -> 2

4c9d2659524a436086fb2f14ff1bd1cd000002:831:938 [3] misc/ibvwrap.cu:235 WARN Call to ibv_query_gid failed with error Unknown error -1
4c9d2659524a436086fb2f14ff1bd1cd000002:831:938 [3] INFO transport/net_ib.cu:453 -> 2
4c9d2659524a436086fb2f14ff1bd1cd000002:831:938 [3] INFO include/net.h:32 -> 2 [Net]
4c9d2659524a436086fb2f14ff1bd1cd000002:831:938 [3] INFO transport/net.cu:266 -> 2
4c9d2659524a436086fb2f14ff1bd1cd000002:831:938 [3] INFO init.cu:475 -> 2

I was able to run Horovod with OpenMPI+NCCL and Intel MPI(infiniband) without NCCL. When trying to use NCCL and Intel MPI it just hangs and searches using the last few messages don't seem to bring up any relevant results.

The command I am executing is:
mpirun -n 8 -ppn 4 -hosts $AZ_BATCH_HOST_LIST \
      -env I_MPI_FABRICS=dapl \
      -env I_MPI_DAPL_PROVIDER=ofa-v2-ib0 \
      -env I_MPI_DYNAMIC_CONNECTION=0 \
      -env I_MPI_DEBUG=6 \
      -env I_MPI_HYDRA_DEBUG=on \
      -env NCCL_DEBUG=INFO \
      -env NCCL_IB_HCA=mlx4_0 \
      -env NCCL_SOCKET_IFNAME=eth0 \
      -genvall \
      python /benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet50 --batch_size 64 --variable_update horovod

The debug outputs from NCCL etc. can be found here  [https://gist.github.com/msalvaris/671fde2b95899c05db2ef7ee61c7da4d](https://gist.github.com/msalvaris/671fde2b95899c05db2ef7ee61c7da4d)

**Comment by msalvaris** [comment]
After some more investigation it seems that Intel MPI is not CUDA aware so can not be used with NCCL.

**Comment by alsrgv** [comment]
@msalvaris, what if you try to disable IB in Intel MPI?  CUDA-aware MPI is not required to use NCCL.

**Comment by msalvaris** [comment]
@alsrgv Ah ok, good point. If I disabled IB it works but the performance is significantly worse than just using Intel MPI on it's own. Do you think that shouldn't be the case?

**Comment by alsrgv** [comment]
@msalvaris, do you see IB-MPI + no NCCL performing better than TCP-MPI + IB-NCCL?  Can you share the numbers?

**Comment by msalvaris** [comment]
So here is the configuration:
2 Nodes with 4 V100s each
No GPUDirect No NVLink

nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    CPU Affinity
GPU0     X      NODE    NODE    NODE    0-11
GPU1    NODE     X      NODE    NODE    0-11
GPU2    NODE    NODE     X      NODE    0-11
GPU3    NODE    NODE    NODE     X      0-11

Tensorflow 1.8 CUDA 9
Network: ResNet 50 
Batch size: 64 (per GPU)

OpenMPI + NCCL2 [(dockerfile)](https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/dev_automated/Horovod/Docker/dockerfile)
1229.81 images/sec

IntelMPI + NCCL2 with IB disabled
1215.50 images/sec

IntelMPI [(dockerfile)](https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/dev_automated/Horovod-intel/Docker/dockerfile)
1807.16 images/sec

**Comment by alsrgv** [comment]
@msalvaris, makes sense - if there's no P2P connectivity, MPI over CPU is the way to go.

**Comment by msalvaris** [comment]
@alsrgv Perfect, thanks for the help.

**Comment by fightbob** [comment]
> @alsrgv Sure
> Here is the configuration:
> 2 Nodes with 4 V100s each
> No GPUDirect No NVLink
> 
> nvidia-smi topo -m
> GPU0 GPU1 GPU2 GPU3 CPU Affinity
> GPU0 X NODE NODE NODE 0-11
> GPU1 NODE X NODE NODE 0-11
> GPU2 NODE NODE X NODE 0-11
> GPU3 NODE NODE NODE X 0-11
> 
> Tensorflow 1.8 CUDA 9
> Network: ResNet 50
> Batch size: 64 (per GPU)
> 
> OpenMPI + NCCL2 [(dockerfile)](https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/dev_automated/Horovod/Docker/dockerfile)
> 1229.81 images/sec
> 
> IntelMPI + NCCL2 with IB disabled
> 1215.50 images/sec
> 
> IntelMPI [(dockerfile)](https://github.com/msalvaris/BatchAIHorovodBenchmark/blob/dev_automated/Horovod-intel/Docker/dockerfile)
> 1807.16 images/sec

@msalvaris @alsrgv IntelMPI performance is better than "IntelMPI/OpenMPI + NCCL2", is really? That's strange.

**Comment by msalvaris** [comment]
@fightbob With IntelMPI  we are able to use Infiniband but with OpenMPI we weren't.

**Comment by fightbob** [comment]
> @fightbob With IntelMPI we are able to use Infiniband but with OpenMPI we weren't.

@msalvaris Why OpenMPI can't use Infiniband? OpenMPI seems to spupport Infiniband.

**Comment by bleirdalag** [comment]
Hi @msalvaris , I'm also trying to use Intel MPI instead of Open MPI. Did you run Horovod in Docker? If so, how did you specify the port number to mpirun to correctly SSH into the Docker container? Thanks for any help!
