### ISSUE TITLE
Is the indices and values of tf.IndexedSlices merged after the ALLGATHER operation?

### ISSUE THREAD

**Issue by zuowang** [uber/horovod#341]
@alsrgv 
Hi Alex Sergeev,
For example, rank 0 has gradient:
indices [0, 1]
values [[1,1,1],[1,1,1]]
rank 1 has gradient:
indices [0, 2]
values [[1,1,1],[1,1,1]]

After the ALLGATHER operation, the averaged gradient is
indices [0, 1,0,2]
values [[0.5,0.5,0.5],[0.5,0.5,0.5],[0.5,0.5,0.5],[0.5,0.5,0.5]]

I went through the code, and didn't find anywhere the indices and values are merged. Is it a bug or can you show me where? Thanks so much!

**Comment by alsrgv** [comment]
@zuowang, TensorFlow should merge indices and values when you execute an operation using tf.IndexedSlices, e.g. convert it to a dense tensor or apply as a gradient to an embedding matrix.

**Comment by zuowang** [comment]
They might be merged in _apply_sparse_duplicate_indices. Thanks a lot!
