### ISSUE TITLE
Listing tf local devices makes horovod go bananas.

### ISSUE THREAD

**Issue by TimZaman** [uber/horovod#35]
See title.

Add this to the top of fe. the keras-example script, and it will allocate a ton of processors and go OOM when using multiple devices.

```python
from tensorflow.python.client import device_lib
LOCAL_DEVICES = device_lib.list_local_devices()
```

Release 🍌 with:

```bash
mpirun -np 4 python keras_mnist.py
```

**Comment by alsrgv** [comment]
Hi @TimZaman,

The problem is that when TensorFlow lists devices, it also allocates all the memory on them. So, when you have multiple processes doing the same, you get OOM.

Is there any particular reason you need to list devices in your script?  Horovod scripts are usually coded with the assumption of having a single GPU pinned by `hvd.local_rank()`:

```python
# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
K.set_session(tf.Session(config=config))
```

Thanks,
Alex

**Comment by TimZaman** [comment]
Afaik, it's the only way to check which GPUs are visible to tensorflow. This then can be used to scope whether or not a GPU is available at all. That then can be used for various tasks; in my specific case to guess some soft-device placement for tensorflow. This line of code is also in Keras: https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L53

**Comment by TimZaman** [comment]
Before I forget: congratulations on this cool repo! I just got linear scaling with 4 devices, which is suspiciously amazing.

**Comment by alsrgv** [comment]
Thanks!

Basically, the premise is that you'd want to forget you have multiple GPUs in the script :-)  You should know how many GPUs you have per host when you do an `mpirun` - but that can be done with an `nvidia-smi` query.

Thanks,
Alex

**Comment by TimZaman** [comment]
Yeah so there's no way around it: https://stackoverflow.com/questions/46734796/how-to-list-visible-tensorflow-devices-without-allocation?noredirect=1#comment80443635_46734796

Thanks!
