### ISSUE TITLE
keras_imagenet_resnet50.py only runs on 1 or 2 nodes...Hangs on 4 or more.

### ISSUE THREAD

**Issue by bapriddy** [uber/horovod#366]
Installed with openmpi and uses CPU memory MPI_Allreduce() across nodes.  Works with MPICH on 1,2,4,8,16 and uses GPU memory for MPI_Allreduce() across nodes.  In both cases batch-size was 32.  
Also, tf_cnn_benchmarks.py was much faster.

**Comment by tgaddair** [comment]
Hey @bapriddy, could you try running with 1strace -f -e 'trace=!poll' mpirun ...` and uploading it into a gist as suggested in #280?

Also, are you up to date with version 0.13.8?  As @alsrgv mentioned in the other thread, there were some recent changes that may affect this issue.

**Comment by bapriddy** [comment]
@tgaddair We'll update to version 0.13.8.  If it hangs again, I'll run the stack trace and provided output...
