### ISSUE TITLE
`module 'horovod.torch' has no attribute 'broadcast_object' `

### ISSUE THREAD

**Issue by bapriddy** [uber/horovod#376]
@tgaddair 
I just ran the new pytorch_imagnet_resnet50.py and got the error below.  Is this because I have not installed horovod 0.13.8?

` Traceback (most recent call last):
  File "resnet.py", line 132, in <module>
    state_dict = hvd.broadcast_object(optimizer.state_dict(), root_rank=0)
AttributeError: module 'horovod.torch' has no attribute 'broadcast_object' `

Was this feature already in previous versions of Horovod??

Thanks

**Comment by tgaddair** [comment]
Hey @bapriddy, this was added in #371, which was merged to master earlier today.  It has not been included in a release yet.

Are you building from source, and did you pull from master earlier today?  If so, you'll need to rebuild Horovod from the project root to get the new changes:

```
rm -rf build
rm -rf dist
python setup.py install
python setup.py build
```

Let me know if that works.

**Comment by alsrgv** [comment]
@bapriddy, we actually retracted 0.13.9 due to optimizer broadcasting taking way too long and pushed out 0.13.10 with #379.  It has a new API for broadcasting optimizer state which should be intuitive to use:
```python
# Horovod: broadcast parameters & optimizer state.
hvd.broadcast_parameters(model.state_dict(), root_rank=0)
hvd.broadcast_optimizer_state(optimizer, root_rank=0)
```

**Comment by bapriddy** [comment]
@tgaddair @alsrgv 
WoW!!  You guys are moving fast!  Okay I'll run the old code for now.  No problem. We will install updated code soon.  Thanks for the help.

**Comment by tgaddair** [comment]
Glad the problem was resolved!
