### ISSUE TITLE
What is the necessary network bandwidth to run Horovod?

### ISSUE THREAD

**Issue by TimYuenior** [uber/horovod#387]
I set up Horovod and altered a Keras/Tensorflow reinforcement learning program so that it runs on 1 machine with Horovod. This works fine, however I'm fairly new to this and I'm worrying about this: https://github.com/uber/horovod/issues/301#issuecomment-396689740
Would using a 1 Gbps LAN connection between 4 machines with 2 GTX1080s yield any speedup at all? Would the use of WAN connections be feasible at all?

Extra: I also don't know how to see if NCCL 2 is being used. I have followed the steps on github on installing it and put -x NCCL_DEBUG=INFO in the mpirun command. However, I don't see any output.

**Comment by alsrgv** [comment]
@TimYuenior, the speeds in the comment you referenced are correct.  As a rule of thumb, P100 needs 25-50Gbps, V100 needs 100Gbps.  GTX1080 would be fine with 25Gbit, but with the lower speed, you start to lose efficiency.

In order to use NCCL, can you uninstall Horovod and reinstall with:
```
$ HOROVOD_GPU_ALLREDUCE=NCCL [maybe other flags] pip install --no-cache-dir -v horovod
```

**Comment by TimYuenior** [comment]
Thanks for the response.
For the bandwidth, I suppose we'll just have to try using 1 Gbps. 
For NCCL, I used the command before to install horovod again when moving on to using multiple GPUs. Do you need to specify `HOROVOD_GPU_ALLREDUCE=NCCL` every time you restart the terminal?

I have noticed that I get the following when running the tf_cnn benchmark:

`dnn3:19699:19749 [0] INFO NET/IB : Using interface enp0s31f6 for sideband communication
dnn3:19699:19749 [0] INFO Using internal Network Socket
dnn3:19699:19749 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
dnn3:19699:19749 [0] INFO NET : Using interface enp0s31f6:192.168.1.220<0>
dnn3:19699:19749 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.1.15+cuda9.1
dnn3:19700:19746 [1] INFO NET : Using interface enp0s31f6:192.168.1.220<0>
dnn3:19700:19746 [1] INFO NET/IB : Using interface enp0s31f6 for sideband communication
dnn3:19700:19746 [1] INFO Using internal Network Socket
dnn3:19700:19746 [1] INFO Using NCCL Low-latency algorithm for sizes below 16384
2018-07-20 09:21:15.342727: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.32GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-07-20 09:21:15.419580: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.26GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-07-20 09:21:15.424639: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.32GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
dnn3:19700:19746 [1] INFO NET : Using interface enp0s31f6:192.168.1.220<0>
dnn3:19700:19746 [1] INFO NET/Socket : 1 interfaces found
dnn3:19699:19749 [0] INFO Using 256 threads
dnn3:19699:19749 [0] INFO Min Comp Cap 6
dnn3:19699:19749 [0] INFO NCCL_SINGLE_RING_THRESHOLD=131072
dnn3:19699:19749 [0] INFO Ring 00 :    0   1
dnn3:19700:19746 [1] INFO Ring 00 : 1[1] -> 0[0] via P2P/IPC
dnn3:19699:19749 [0] INFO Ring 00 : 0[0] -> 1[1] via P2P/IPC
dnn3:19699:19749 [0] INFO Launch mode Parallel
`

I DO see lines stating the use of NCCL, but only when running this benchmark. Does this mean NCCL works? Do you only see the INFO lines at the start of the program? 
However, I still can't see anything about NCCL when I run my own program for 2 local GPUs with: `mpirun -np 2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO python3 main.py`

**Comment by TimYuenior** [comment]
Another different issue we ran into is that our program loops over several stages. The training is the middle stage. Running with horovod seems to distribute the whole pipeline (which is fine, but we'll have to tinker with the code). 
My question is how exactly horovod distributes the work. Does it run the same python file for every device? Is there a possibility to only distribute the execution during the middle stage while running the whole pipeline?

**Comment by alsrgv** [comment]
@TimYuenior, yes, it does run the same python file for every device. You can omit certain parts of the code by checking `if hvd.rank() == 0` - which will only get executed on the first device.

Since you see NCCL output in the benchmark, your installation should be correct.

Did you make modifications to your program `main.py` - add `hvd.init()`, wrap optimizer with `hvd.DistributedOptimizer()`, etc, as described in the [README](https://github.com/uber/horovod/blob/master/README.md)?

**Comment by TimYuenior** [comment]
Right, the IF-statement should definitely help.

Ah, so the NCCL only works for the DistributedOptimizer? I thought I checked it during training, but maybe I didn't and only checked during the first stage, which doesn't use the optimizer. When I only check the second stage, the INFO statements do print before training. I followed the keras mnist example for my train.py.

I also noticed that during the first stage, the speeds of the 2 GPUs seem to be different. One tends to process by 0.20 units/sec and the other at 0.08 units/sec. Using `if hvd.rank() == 0` and `if hvd.rank() == 1` I figured out that the GPU at rank 0 is the slow one. Would you have any idea if it has to do anything with the rank, other GPU settings, or that it is simply a hardware issue?

**Comment by TimYuenior** [comment]
The difference in speed seems to be present when running the keras mnist example distributed using `mpirun --prefix /usr/local -np 2 -H localhost:1,dnn:1 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python3 keras_mnist.py`. Basically, the local GPU finishes completely before the remote GPU even finishes 1 epoch. This leads to an error where allreduce is called while the local GPU is already finished. Done over 1 Gbps LAN.

**Comment by alsrgv** [comment]
@TimYuenior, unless you specifically modify batch size per GPU to be smaller because of Horovod, it will use the same batch size 128 as it did before.

It's likely that they print the same # of iterations as before because you did not partition the dataset, like we do in [vanilla MNIST example](https://github.com/uber/horovod/blob/master/examples/keras_mnist.py).  That is fine - your model should converge in 3x less epochs if you train on 3 GPUs.

Alternatively, you can consider adjusting # of iterations per epoch to be N / 3, like we do in [advanced MNIST example](https://github.com/uber/horovod/blob/master/examples/keras_mnist_advanced.py#L117).

As for performance - you mentioned that your original model takes 8 seconds per epoch on a single GPU.  If your batch size is 128 and you have 60000 images, it means that you're processing ~60 batches per second. This is a very high # and it will be hard to scale.

The model seems rather simple - you can get more benefits of distributed training if you make your model more complex, and, hopefully - get a better accuracy in return.

**Comment by TimYuenior** [comment]
Ah, ok, so all machines generate their own training data and do what model.fit would do in independent programs, but the batch updates are synchronized. This means every machine needs a copy of the dataset, right? In terms of communication only the weights of the model are broadcasted once at the start and the gradients with every batch.

Are there ways to allreduce other data? For example evaluation is a different but long process and can easily be parallelized. We need some of the statistics of each evaluation process though.

**Comment by TimYuenior** [comment]
What metric averages does horovod keep track of? I'm using a different evaluation method which simulates a bunch of games and keeps track of a winrate. I just want the winrates of the different machines at the end and average them and ideally send messages to the other machines again. Would I need to look into ompi to do this effectively?

**Comment by alsrgv** [comment]
`MetricAverageCallback` averages all the metric that Keras keeps track of.  If you want to average a custom metric, you can simply use `hvd.allreduce()` of metrics computed on every worker.

**Comment by TimYuenior** [comment]
Alright, I'll look into that. I'm closing this issue now before it contains too many of my arbitrary problems. Thanks for the help!
