### ISSUE TITLE
Download examples url in Dockerfile file

### ISSUE THREAD

**Issue by kimbaol** [uber/horovod#391]
The last pass of the Dockerfile [Download example](https://github.com/uber/horovod/blob/6c4287c519b99dcb7e3cd4e3f27a2cef0931822c/Dockerfile#L93) seems pointing to an unreachable url.

**Comment by alsrgv** [comment]
@kimbaol, it does not work with the browser, but it should work with `svn checkout https://github.com/uber/horovod/trunk/examples`.

**Comment by kimbaol** [comment]
I see, it's due to my proxy setting, I usually use "export http_proxy=***" and "export https_proxy=***" to connect Internet on my server, but it doesn't work with svn.
Thanks for your quick reply!
