### ISSUE TITLE
ModuleNotFoundError: No module named 'horovod.torch.mpi_lib_impl._mpi_lib_impl'

### ISSUE THREAD

**Issue by srams2018** [uber/horovod#409]
Hi, iam getting below error while horovod with torch.
# python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from horovod.torch.mpi_ops_impl import allreduce, allreduce_async, allreduce_, allreduce_async_
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/__init__.py", line 31, in <module>
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 23, in <module>
    from horovod.torch import mpi_lib_impl
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl/__init__.py", line 18, in <module>
    from ._mpi_lib_impl import ffi as _ffi
ModuleNotFoundError: No module named 'horovod.torch.mpi_lib_impl._mpi_lib_impl'

=====================

/data/anaconda/4.3.1/3/bin/python: No module named import
# python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.torch as hvd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/__init__.py", line 31, in <module>
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/mpi_ops.py", line 23, in <module>
    from horovod.torch import mpi_lib_impl
  File "/data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl/__init__.py", line 18, in <module>
    from ._mpi_lib_impl import ffi as _ffi
ModuleNotFoundError: No module named 'horovod.torch.mpi_lib_impl._mpi_lib_impl'
>>> quit()

**Comment by alsrgv** [comment]
@srams2018, can you reinstall Horovod and make a [gist](https://gist.github.com/) with the log of installation?  Make sure to run `pip install` with `-v --no-cache-dir` flags.

**Comment by srams2018** [comment]
Here is the log  @alsrgv 
https://gist.github.com/srams2018/ba594502c0cd749409d7f37f027c74a9#file-horovod-logs

**Comment by alsrgv** [comment]
@srams2018, everything looks ok - do you still get an error trying to import?  If you do, can you share the output of `find /data/anaconda/4.3.1/3/lib/python3.6/site-packages/horovod`?

**Comment by srams2018** [comment]
thanks @alsrgv. its working fine now.
# python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import horovod.torch as hvd
>>>

**Comment by FrancisLeeHa** [comment]
@srams2018 I have the same problem as you

python3 pytorch_synthetic_benchmark.py 
Traceback (most recent call last):
  File "pytorch_synthetic_benchmark.py", line 9, in <module>
    import horovod.torch as hvd
  File "/usr/local/python3/lib/python3.6/site-packages/horovod/torch/__init__.py"
    from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, all
  File "/usr/local/python3/lib/python3.6/site-packages/horovod/torch/mpi_ops.py",
    from horovod.torch import mpi_lib_impl
  File "/usr/local/python3/lib/python3.6/site-packages/horovod/torch/mpi_lib_impl
    from ._mpi_lib_impl import ffi as _ffi
ModuleNotFoundError: No module named 'horovod.torch.mpi_lib_impl._mpi_lib_impl'

Could you please tell me how you solve this problem? thanks!

our pytorch version is 0.4.1

**Comment by alsrgv** [comment]
@FrancisLeeHa, can you try reinstalling latest Horovod with `-v --no-cache-dir`, and attach installation log?

**Comment by luzhilin19951120** [comment]
The very interesting thing is that:
If I install horovod with `--user` argument, installing it in `/home/$USER/.local`, I can not import it correctly with a certain conda environment. But if I choose to install in within the environment everything is fine.

I know the aforementioned phenomenon is not clear enough. __Actually I merely has a question:__

I didn't find `ffi` in the directory `horovod/torch/mpi_lib_impl`. How can python carry out
``` python
from ._mpi_lib_impl import ffi as _ffi
```
in `horovod/torch/mpi_lib_impl/__init__.py` correctly? 

I guess that has something to do with the library `mpi_lib_v2.cpython-36m-x86_64-linux-gnu.so`, but I don't know for sure. The reason why it works is beyond my personal understanding of python import mechanism.

May you explain it, I mean, briefly if you are busy? Thank you very much. @alsrgv

**Comment by alsrgv** [comment]
@luzhilin19951120, you get this error most likely because we first try to import v2 library, and if that fails import v1 library ([code](https://github.com/horovod/horovod/blob/master/horovod/torch/__init__.py#L22)).  The error of v2 library import is swallowed.

I believe we can remove v1 support soon, as users migrate off PyTorch 0.4.0, or at least print out v2 import error explicitly and attempt fallback to v1.  I've raised #1080 to track this.
