### ISSUE TITLE
Syncing metrics between processes.

### ISSUE THREAD

**Issue by TimZaman** [uber/horovod#41]
In the context of some job that reports a loss, each process reports the loss of the batch they have just processed. Does horovod, or can you suggest a best way of aggregating/syncing metrics or loss values across processes for reporting those somewhere?

**Comment by alsrgv** [comment]
The simplest way for many metrics would be just to average them using `hvd.allreduce()`.  You can also do `hvd.allgather()` of metric value to do custom aggregation.  Does either of those two options solve your need?

**Comment by TimZaman** [comment]
Thanks mate.
