### ISSUE TITLE
Error with running on multiple machines

### ISSUE THREAD

**Issue by itsogkyc** [uber/horovod#414]
Hi. 

I'm testing horovod on our system with docker.  I have two server centos1(2gpu), centos2(2gpu)
I have some thing wrong with running on multiple machines.
When I run it on a single machine , it has no problem ( even i can run process from coneos1 to centos2)
But, when i try to run on multiple machine in centos1 server , it going to hang out and no log can see.
I typed command as below
"mpirun -np 4 -H centos01:2,centos02:2 -mca plm_rsh_args "-p 12345" python keras_mnist_advanced.py"

log as below
![image](https://user-images.githubusercontent.com/36907071/43509431-a173694a-95ad-11e8-864a-0e0abf039dba.png)

ps. sometimes i meet the log message like below : 

[centos01][[32355,1],2][btl_tcp_endpoint.c:796:mca_btl_tcp_endpoint_complete_connect] connect() to 192.168.122.1 failed: Connection refused (111)

[centos01][[31589,1],2][btl_tcp_endpoint.c:638:mca_btl_tcp_endpoint_recv_connect_ack] received unexpected process identifier [[31589,1],3]

or i just freeze without any log

**Comment by itsogkyc** [comment]
now i resolved above error
but , i meet a new error now
log as below

`/lib/docker/overlay2/l/43OACZ6DWYUUQWWZYNIX5FQWVE:/var/lib/docker/overlay2/l/UGL6IHPGFTW7U4Q7YOYHSMU3VE:/var/lib/docker/overlay2/l/QVMXNFGL534AFXYHBCY4HGZF7S:/var/lib/docker/overlay2/l/B2IVOYDCQPWKB54SOHMHK4KHAS:/var/lib/docker/overlay2/l/YQN6XBYAEIMMIHDYQNZJKTI5CQ:/var/lib/docker/overlay2/l/LQKXF7XULJ7UZJPPCTTOSMWWVR:/var/lib/docker/overlay2/l/PITYLRAWF4FSN'
Unexpected end of /proc/mounts line `QV4F3DX5I5HM3:/var/lib/docker/overlay2/l/DTKGXP44CHXIY5U6TP34MDFNZI:/var/lib/docker/overlay2/l/SRUZNRNMY5V6J3ETSJDQZRX3E2:/var/lib/docker/overlay2/l/HZ3IJUDQG2ZUYHF3BSRSKDGSF6:/var/lib/docker/overlay2/l/3P4TVP5KNDMZ3Y3FCSVRH7EOQD:/var/lib/docker/overlay2/l/TGTJNUG3ZQDIPIU2MLCJNQUMJ3:/var/lib/docker/overlay2/l/V2C36CK6SODEXVPERHXTN6Z35X:/var/lib/docker/overlay2/l/MCQRAHIZCVP7DD6GKTUQMJSI2X:/var/lib/docker/overlay2/l/5JCMK4UKIAG3H5J4VWNZARMQBA:/var/lib/docker/overlay2/l/YYFXJA5V4PDZ5JAEQYDI76YKSF:/var/lib/do'
Unexpected end of /proc/mounts line `cker/overlay2/l/SEWLEOMDRFARJ4LQRW4WIX6M2E:/var/lib/docker/overlay2/l/AMJAXLM22673CJKWEWQ2UMVGOS:/var/lib/docker/overlay2/l/BJJZAX73MVPO6MFFVRKN66SNYU:/var/lib/docker/overlay2/l/OQ5K26R4L2Z3QEHQAXBN66JBCC:/var/lib/docker/overlay2/l/WUL5T45H3JS4IFXFSUXZJWX5WJ:/var/lib/docker/overlay2/l/TKBSWFRROTJAVHPQSBOBRCXWUK:/var/lib/docker/overlay2/l/DVEGCES5DLB5DAU7W5WVEPI2XL,upperdir=/var/lib/docker/overlay2/1bf26f38359d50b92d30f4be3fdc3108e35bf39fc78a9548b8eb5afe6d41f906/diff,workdir=/var/lib/docker/overlay2/1bf26f3'
Unexpected end of /proc/mounts line `overlay / overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/PZLX3FKY4IX4IGWZVPCDETOBQH:/var/lib/docker/overlay2/l/HVLIKSSTLBBIINVXK4BRHMJ7VV:/var/lib/docker/overlay2/l/43OACZ6DWYUUQWWZYNIX5FQWVE:/var/lib/docker/overlay2/l/UGL6IHPGFTW7U4Q7YOYHSMU3VE:/var/lib/docker/overlay2/l/QVMXNFGL534AFXYHBCY4HGZF7S:/var/lib/docker/overlay2/l/B2IVOYDCQPWKB54SOHMHK4KHAS:/var/lib/docker/overlay2/l/YQN6XBYAEIMMIHDYQNZJKTI5CQ:/var/lib/docker/overlay2/l/LQKXF7XULJ7UZJPPCTTOSMWWVR:/var/lib/docker/overlay2/l/PITYLRAWF4FSN'
Unexpected end of /proc/mounts line `QV4F3DX5I5HM3:/var/lib/docker/overlay2/l/DTKGXP44CHXIY5U6TP34MDFNZI:/var/lib/docker/overlay2/l/SRUZNRNMY5V6J3ETSJDQZRX3E2:/var/lib/docker/overlay2/l/HZ3IJUDQG2ZUYHF3BSRSKDGSF6:/var/lib/docker/overlay2/l/3P4TVP5KNDMZ3Y3FCSVRH7EOQD:/var/lib/docker/overlay2/l/TGTJNUG3ZQDIPIU2MLCJNQUMJ3:/var/lib/docker/overlay2/l/V2C36CK6SODEXVPERHXTN6Z35X:/var/lib/docker/overlay2/l/MCQRAHIZCVP7DD6GKTUQMJSI2X:/var/lib/docker/overlay2/l/5JCMK4UKIAG3H5J4VWNZARMQBA:/var/lib/docker/overlay2/l/YYFXJA5V4PDZ5JAEQYDI76YKSF:/var/lib/do'
Unexpected end of /proc/mounts line `cker/overlay2/l/SEWLEOMDRFARJ4LQRW4WIX6M2E:/var/lib/docker/overlay2/l/AMJAXLM22673CJKWEWQ2UMVGOS:/var/lib/docker/overlay2/l/BJJZAX73MVPO6MFFVRKN66SNYU:/var/lib/docker/overlay2/l/OQ5K26R4L2Z3QEHQAXBN66JBCC:/var/lib/docker/overlay2/l/WUL5T45H3JS4IFXFSUXZJWX5WJ:/var/lib/docker/overlay2/l/TKBSWFRROTJAVHPQSBOBRCXWUK:/var/lib/docker/overlay2/l/DVEGCES5DLB5DAU7W5WVEPI2XL,upperdir=/var/lib/docker/overlay2/1bf26f38359d50b92d30f4be3fdc3108e35bf39fc78a9548b8eb5afe6d41f906/diff,workdir=/var/lib/docker/overlay2/1bf26f3'
centos02:9582:9781 [0] INFO comm 0x7f0ed0253fe0 rank 0 nranks 4
centos02:9583:9778 [1] INFO comm 0x7f57e4286970 rank 1 nranks 4
centos01:21030:21226 [1] INFO comm 0x7fc434280230 rank 3 nranks 4
centos02:9583:9778 [1] INFO NET : Using interface virbr0:192.168.122.1<0>
centos02:9583:9778 [1] INFO NET : Using interface docker0:172.17.0.1<0>
centos02:9583:9778 [1] INFO NET : Using interface flannel.1:10.244.0.0<0>
centos02:9583:9778 [1] INFO NET : Using interface cni0:10.244.0.1<0>
centos02:9583:9778 [1] INFO NET : Using interface veth5d5a8c4e:fe80::3404:83ff:fe0a:a9d2%veth5d5a8c4e<0>
centos02:9583:9778 [1] INFO NET : Using interface vethac1f844a:fe80::4476:51ff:febd:3dc0%vethac1f844a<0>
centos02:9583:9778 [1] INFO NET : Using interface veth3358f286:fe80::50:1ff:febe:d0c1%veth3358f286<0>
centos02:9583:9778 [1] INFO NET/Socket : 7 interfaces found
centos01:21030:21226 [1] INFO NET : Using interface docker0:172.17.0.1<0>
centos01:21030:21226 [1] INFO NET : Using interface virbr0:192.168.122.1<0>
centos01:21030:21226 [1] INFO NET : Using interface flannel.1:10.244.1.0<0>
centos01:21030:21226 [1] INFO NET : Using interface cni0:10.244.1.1<0>
centos01:21030:21226 [1] INFO NET/Socket : 4 interfaces found
centos01:21029:21225 [0] INFO comm 0x7f5b0028aa60 rank 2 nranks 4
centos01:21029:21225 [0] INFO NET : Using interface docker0:172.17.0.1<0>
centos01:21029:21225 [0] INFO NET : Using interface virbr0:192.168.122.1<0>
centos01:21029:21225 [0] INFO NET : Using interface flannel.1:10.244.1.0<0>
centos01:21029:21225 [0] INFO NET : Using interface cni0:10.244.1.1<0>
centos01:21029:21225 [0] INFO NET/Socket : 4 interfaces found

centos01:21030:21226 [1] include/socket.h:360 WARN Call to connect timeout : Connection refused
centos01:21030:21226 [1] INFO transport/net_socket.cu:118 -> 2
centos01:21030:21226 [1] INFO bootstrap.cu:28 -> 2 [Net]
centos01:21030:21226 [1] INFO bootstrap.cu:238 -> 2
centos01:21030:21226 [1] INFO init.cu:409 -> 2
centos01:21030:21226 [1] INFO init.cu:536 -> 2`


My command line is it on server1
`mpirun -np 4 -H centos01:2,centos02:2 -mca plm_rsh_args "-p 12345" -mca btl_tcp_if_exclude cni0,docker0,em1,em2,em4,flannel.1,lo,p7p1,p7p2,veth3358f286,veth5d5a8c4e,vethac1f844a,virbr0,virbr0-nic -x NCCL_SOCKET_IFNAME=cni0,docker0,em1,em2,em4,flannel.1,lo,p7p1,p7p2,veth3358f286,veth5d5a8c4e,vethac1f844a,virbr0,virbr0-nic  python keras_mnist_advanced.py`

**Comment by alsrgv** [comment]
@itsogkyc, you're on the right track.  Can you add `^` in your `NCCL_SOCKET_IFNAME`.  Either `-x NCCL_SOCKET_IFNAME=^cni0,docker0,em1,em2,em4,flannel.1,lo,p7p1,p7p2,veth3358f286,veth5d5a8c4e,vethac1f844a,virbr0,virbr0-nic` or `-x NCCL_SOCKET_IFNAME=^cni0,^docker0,^em1,^em2,^em4,^flannel.1,^lo,^p7p1,^p7p2,^veth3358f286,^veth5d5a8c4e,^vethac1f844a,^virbr0,^virbr0-nic`.

Alternatively, you can actually just specify an interface to **include**: `-mca btl_tcp_if_include em3 -x NCCL_SOCKET_IFNAME=em3`.

**Comment by itsogkyc** [comment]
@alsrgv, thank your reply
I tried all what u said , but it still not work 

When i type `mpirun -np 4 -H centos01:2,centos02:2 -mca plm_rsh_args "-p 12345" -mca btl_tcp_if_include em3 -x NCCL_SOCKET_IFNAME=em3 python keras_mnist_advanced.py`
I meet new error as below 
```
Two mutually-exclusive MCA variables were specified.  This can result
in undefined behavior, such as ignoring the components that the MCA
variables are supposed to affect.

  1st MCA variable: btl_tcp_if_include
    Source of value: environment
  2nd MCA variable: btl_tcp_if_exclude
    Source of value: file (/usr/local/etc/openmpi-mca-params.conf:61)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[30969,1],2]) is on host: centos01
  Process 2 ([[30969,1],0]) is on host: centos02
  BTLs attempted: self vader

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
Error in MPI_Isend(140546833576768, 1, 0x7fd3a2235f00, 0, -26, 140546935077504) (-12)
Error in NBC_Start_round() (-12)
Error in NBC_Start_round() (-1)
[centos02:01679] 3 more processes have sent help message help-mca-var.txt / mutually-exclusive-vars
[centos02:01679] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```

**Comment by alsrgv** [comment]
Since you're using provided Dockerfile, can you edit `/usr/local/etc/openmpi-mca-params.conf` and comment out `btl_tcp_if_exclude = lo,docker0`, and then try again?

**Comment by itsogkyc** [comment]
Finally it worked after comment out `btl_tcp_if_exclude ` option
Just add one '^' at first . When I add all '^' in NCCL_SOCKET_IFNAME , It occured the error ) 
My command line like below

`
mpirun -np 4 -H centos01:2,centos02:2 -mca plm_rsh_args "-p 12345" -mca btl_tcp_if_exclude cni0,docker0,em1,em2,em4,flannel.1,lo,p7p1,p7p2,veth3358f286,veth5d5a8c4e,vethac1f844a,virbr0,virbr0-nic -x NCCL_SOCKET_IFNAME=^cni0,docker0,em1,em2,em4,flannel.1,lo,p7p1,p7p2,veth3358f286,veth5d5a8c4e,vethac1f844a,virbr0,virbr0-nic python keras_mnist_advanced.py
`
