### ISSUE TITLE
Error: 'TFOptimizer' object has no attribute 'lr'

### ISSUE THREAD

**Issue by shinechou** [uber/horovod#42]
Thanks a lot for this great framework. I got this error message "'TFOptimizer' object has no attribute 'lr'" when I was using ReduceLROnPlateau callback from Keras, could you please help me to find a way to solve this with horovod? Thank you very much in advance.

**Comment by shinechou** [comment]
@alsrgv:+1: Thank you very much. However, I got the error message as below,

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[Node: Variable/_0 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", _device="/job:localhost/replica:0/task:0/gpu:0"](Variable)]]
	 [[Node: Variable/_1 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_Variable", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Could you please help me again? Thanks in advance.

**Comment by alsrgv** [comment]
@shinechou, couple of questions:
1. Did it work before if you don't use `ReduceLROnPlateau`?
2. The error like that is very hard to diagnose without seeing the code. Can you publish relevant part of the code somewhere?

**Comment by shinechou** [comment]
@alsrgv: Really appreciate your help.
(1) Yes, it works well without using ReduceLROnPlateau (even I use your "MetricAverageCallback" callback) although when I wanna save the weights I got "_UserWarning: TensorFlow optimizers do not make it possible to access optimizer attributes or optimizer state after instantiation. As a result, we cannot save the optimizer as part of the model save file.You will have to compile your model again after loading it. Prefer using a Keras optimizer instead (see keras.io/optimizers).
  'TensorFlow optimizers do not_ '" 

(2) I paste the relevant code as below,

`
class MetricAverageCallback(keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    logs = logs or {}
    for metric in logs:
      avg_op = hvd.allreduce(K.constant(logs[metric]))
      logs[metric] = K.get_session().run(avg_op)

# Initialize Horovod.
hvd.init()

# Pin GPU to be used to process local rank (one GPU per process)
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
K.set_session(tf.Session(config=config))

#read data
...
#build NN model
...
# Adjust learning rate based on number of GPUs (naive approach).
learning_rate = K.variable(1.0 * hvd.size())
print('\n\n learning_rate: ', learning_rate)
tf_opt = tf.train.AdadeltaOptimizer(learning_rate)

# Add Horovod Distributed Optimizer.
tf_opt = hvd.DistributedOptimizer(tf_opt)

# Wrap with TF optimizer with Keras optimizer, pass learning rate.
opt = keras.optimizers.TFOptimizer(tf_opt)
opt.lr = learning_rate

model = Model(outputs=out, inputs=x)
model.compile(loss=keras.losses.categorical_crossentropy,
			  optimizer=opt,
			  metrics=['accuracy'])
print(model.summary())
keras.utils.plot_model(model, to_file='FCN.png', show_shapes=False, show_layer_names=True, rankdir='TB') 

# Broadcast variables from rank 0 to all other processes.
K.get_session().run(hvd.broadcast_global_variables(0))

reduce_lr = keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=5, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0.001)
#checkpoint
filepath = "weights.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=True, mode='max')
curTime = datetime.now().strftime('%Y%m%d_%H%M%S')
fig_filename = 'training_acc_loss_' + curTime + '.png'
plotter = AccLossPlotter(graphs=['acc', 'loss'], save_graph=True, file_name=fig_filename)

hist = model.fit(x_train, Y_train, batch_size=batch_size, epochs=nb_epochs, shuffle=True, verbose=1, validation_data=(x_val, Y_val), callbacks=[MetricAverageCallback(),reduce_lr, checkpoint, plotter])
`

Thanks again.

**Comment by shinechou** [comment]
@alsrgv: Thank you. I think I  found the reason, because I should put "model = Model(outputs=out, inputs=x)" before "learning_rate = K.variable(1.0 * hvd.size())". Sorry for my mistake and I'm really grateful for your kind help. Hope to see the new examples or updated one.

**Comment by alsrgv** [comment]
@shinechou, glad you resolved the issue!

**Comment by TimZaman** [comment]
@alsrgv I don't think your callback does anything.

This does:
```python
# Optionally, add this callback to combine metrics from all processes.
class ProcessHistory(keras.callbacks.Callback):
  def on_train_begin(self, logs={}):
    self.history = []
  def on_epoch_end(self, epoch, logs=None):
    """Update the log by averaging the logged metrics from each process."""
    print('end!')
    logs = logs or {}
    for metric in logs:
      avg_op = hvd.allreduce(K.constant(logs[metric]))
      logs[metric] = K.get_session().run(avg_op)
    self.history.append(logs)

process_history = ProcessHistory()

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          callbacks=[process_history],
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

print(process_history.history)
```

**Comment by alsrgv** [comment]
@TimZaman aren't those equivalent except for `self.history`? It will be doing useful stuff if every worker processes a different slice of validation data, i.e. `x_test`/`y_test` are slices of full validation data set.  I'll make a bigger example with this and publish shortly.

**Comment by TimZaman** [comment]
Yeah I was going to make a PR and decided you might not want this as it got a bit too involved, and not very "add 5 lines for horovod".
Functionally the same, but the result from your callback would not be saved or shown anywhere.

**Comment by alsrgv** [comment]
@TimZaman It's supposed to modify `logs` which is passed to all the callbacks, and my understanding was that the modified value in `logs` would be propagated to the next callback, which would be `ReduceLROnPlateau` in the example.

**Comment by alsrgv** [comment]
Short-term, I think I'll create one more example with callbacks that would do validation data partitioning & automatic learning rate adjustments.

Long-term, I'm quite open to adding useful Keras code to `horovod/keras/callbacks.py` and collaborating with Keras on making API easy to use. One specific issue I had is that it's not possible to use native Keras optimizers with Horovod because gradient computation and updates are not decoupled. This is something that could be improved to help integration with Horovod.

**Comment by alsrgv** [comment]
This is now fully supported by the `horovod.keras` package. See an example code [here](https://github.com/uber/horovod/blob/master/examples/keras_mnist_advanced.py).

**Comment by TimZaman** [comment]
Very cool, @alsrgv .

**Comment by zippeurfou** [comment]
It seems to be more a keras issue btw than horovod.

**Comment by KushalDave** [comment]
I am trying to use the TF optimizers instead of the keras due to the Dense conversion in Keras optimizers. Here is the solution that I am following: keras-team/keras#4365

But when I do this with Horovod (code taken from here #42 )-
learning_rate = K.variable(1.0 * hvd.size())
print('\n\n learning_rate: ', learning_rate)
tf_opt = tf.train.AdadeltaOptimizer(learning_rate)

#Add Horovod Distributed Optimizer.
tf_opt = hvd.DistributedOptimizer(tf_opt)

#Wrap with TF optimizer with Keras optimizer, pass learning rate.
opt = keras.optimizers.TFOptimizer(tf_opt)
opt.lr = learning_rate

print("HVD size: " + str(hvd.size()))

#Horovod: add Horovod Distributed Optimizer.
mymod.compile(optimizer=opt, loss='categorical_crossentropy')

I get the following error:
2019-07-13T01:09:12.881Z: [1,1]:Traceback (most recent call last):
2019-07-13T01:09:12.881Z: [1,1]: File "TrainGen_Attention.py", line 363, in 
2019-07-13T01:09:12.881Z: [1,1]: tf_opt = hvd.DistributedOptimizer(tf_opt)
2019-07-13T01:09:12.881Z: [1,1]: File "python3.5/site-packages/horovod/keras/init.py", line 59, in DistributedOptimizer
2019-07-13T01:09:12.881Z: [1,1]: sparse_as_dense)
2019-07-13T01:09:12.881Z: [1,1]: File "python3.5/site-packages/horovod/_keras/init.py", line 70, in create_distributed_optimizer
2019-07-13T01:09:12.881Z: [1,1]: optimizer.get_config())
2019-07-13T01:09:12.881Z: [1,1]:AttributeError: 'AdadeltaOptimizer' object has no attribute 'get_config'

**Comment by wuliytTaotao** [comment]
> Great question, @shinechou!
> 
> I found that an example code below allows you to use ReduceLROnPlateau callback. The key element of that code is the manual creation of `learning_rate` variable that is passed to TF optimizer and Keras TFOptimizer wrapper.
> 
> ```python
> # Adjust learning rate based on number of GPUs (naive approach).
> learning_rate = K.variable(1.0 * hvd.size())
> tf_opt = tf.train.AdadeltaOptimizer(learning_rate)
> 
> # Add Horovod Distributed Optimizer.
> tf_opt = hvd.DistributedOptimizer(tf_opt)
> 
> # Wrap with TF optimizer with Keras optimizer, pass learning rate.
> opt = keras.optimizers.TFOptimizer(tf_opt)
> opt.lr = learning_rate
> 
> model.compile(loss=keras.losses.categorical_crossentropy,
>               optimizer=opt,
>               metrics=['accuracy'])
> ```
> 
> Adding verbosity to the callback also helps to see that it's actually working:
> 
> ```python
> model.fit(x_train, y_train,
>           batch_size=batch_size,
>           epochs=epochs,
>           callbacks=[keras.callbacks.ReduceLROnPlateau(verbose=1)],
>           verbose=1,
>           validation_data=(x_test, y_test))
> ```
> 
> **Note.** One caveat for using adaptive learning rate in a distributed setting is to make sure that your validation loss will be the same for all the workers, otherwise, different workers may end up reducing LR at different points in time. The easiest option is to run validation on full data set for all workers.
> 
> If you wish to run validation in a distributed way by partitioning the data, you should make sure that metrics are averaged across all workers. You can do that by adding another callback:
> 
> ```python
> class MetricAverageCallback(keras.callbacks.Callback):
>   def on_epoch_end(self, epoch, logs=None):
>     logs = logs or {}
>     for metric in logs:
>       avg_op = hvd.allreduce(K.constant(logs[metric]))
>       logs[metric] = K.get_session().run(avg_op)
> ```
> 
> And add it to the `model.fit()` call:
> 
> ```python
> model.fit(x_train, y_train,
>           batch_size=batch_size,
>           epochs=epochs,
>           callbacks=[MetricAverageCallback(), 
>                      keras.callbacks.ReduceLROnPlateau(verbose=1)],
>           verbose=1,
>           validation_data=(x_test, y_test))
> ```
> 
> Please let us know if this helped and whether you are using distributed validation, we will add new examples or update existing ones accordingly.

Set the `opt.lr = learning_rate` actually do nothing to the optimizer's true learning rate `opt._lr`, and when you do learning rate decay or ReduceLROnPlateau, the true learning rate `opt._lr` is actually not changed. (tensorflow 1.14)

When we need do learning rate decay, we should use the optimzers of tf.keras not tf.train.
