### ISSUE TITLE
Undefined symbol in mpi_lib for pytorch with Cray MPICH

### ISSUE THREAD

**Issue by sparticlesteve** [uber/horovod#423]
Hello,

I'm trying to install horovod+pytorch on a Cray system and having some trouble.

I have pytorch-cpu 0.4.1 in a python3.6 conda environment (with also TF 1.9). I cloned horovod v0.13.11, loaded gcc 7.2 (with a Cray compiler wrapper), and set HOROVOD_MPICXX_SHOW to link against the Cray MPI libraries. This builds seemingly fine with `python setup.py bdist_wheel`, and I pip install the wheel into my conda env.

This procedure generally works for our TensorFlow installations and we run TF+Horovod just fine, and here still I can import horovod.tensorflow without trouble, but in this case now when trying to use it with pytorch I get a missing symbol in the torch mpi_lib:
```
In [2]: import horovod.torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-bcaa67063378> in <module>()
----> 1 import horovod.torch

/global/cscratch1/sd/sfarrell/conda/pytorch-horovod/lib/python3.6/site-packages/horovod/torch/__init__.py in <module>()
     30                 __file__, 'mpi_lib', '_mpi_lib')
     31
---> 32 from horovod.torch.mpi_ops import allreduce, allreduce_async, allreduce_, allreduce_async_
     33 from horovod.torch.mpi_ops import allgather, allgather_async
     34 from horovod.torch.mpi_ops import broadcast, broadcast_async, broadcast_, broadcast_async_

/global/cscratch1/sd/sfarrell/conda/pytorch-horovod/lib/python3.6/site-packages/horovod/torch/mpi_ops.py in <module>()
     22
     23 from horovod.torch import mpi_lib_impl
---> 24 from horovod.torch import mpi_lib
     25 from horovod.torch import rank, size
     26

/global/cscratch1/sd/sfarrell/conda/pytorch-horovod/lib/python3.6/site-packages/horovod/torch/mpi_lib/__init__.py in <module>()
     16 from torch.utils.ffi import _wrap_function
     17 from horovod.common import get_ext_suffix as _get_ext_suffix
---> 18 from ._mpi_lib import ffi as _ffi
     19 import os as _os
     20

ImportError: /global/cscratch1/sd/sfarrell/conda/pytorch-horovod/lib/python3.6/site-packages/horovod/torch/mpi_lib/_mpi_lib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z45horovod_torch_allgather_async_torch_IntTensorP8THTensorS0_Pc
```

I'm happy to provide more details as necessary, but maybe someone already has a clue as to what the problem could be. I appreciate any help.

Thanks,
Steve

**Comment by alsrgv** [comment]
@sparticlesteve, sorry for a delayed reply.  Could you reinstall Horovod with `-v --no-cache-dir` and provide a full installation log (preferably in [gist](https://gist.github.com/))?

**Comment by sparticlesteve** [comment]
Hi @alsrgv,

Thanks for the reply, and sorry for my own slow response.

I've been playing with things a fair bit and have a slightly modified setup from above. Same issue, though, so I'll just describe the new setup.

I reverted to pytorch v0.4.0, with python 3.6, horovod v0.13.11, without TensorFlow.
The compiler is gcc 7.3.0 with a Cray wrapper, which I guess complicates things.
I've trimmed down the showMPI command to just print the libs I think it should use (below).

My pytorch build instructions are here:
https://gist.github.com/sparticlesteve/d3fbb9ba338dfd85a22115aeecd5d24b

Then my horovod build instructions are here:
https://gist.github.com/sparticlesteve/a1222e1c51800a3c148af542a2c65ffc
The showMPI.sh script contains just:
```bash
#!/bin/bash
flags="-L/opt/cray/pe/mpt/7.7.0/gni/mpich-gnu/51/lib -lmpich_gnu_51_mt"
flags="$flags -L/opt/cray/pe/mpt/7.7.0/gni/mpich-gnu/51/lib -lmpichcxx_gnu_51_mt"
echo $flags
```

Now, the output of the horovod build commands. I'm building with `python setup.py -v` and don't see a `--no-cache-dir` option so if this is for a specific build script let me know. Otherwise I just use the verbose option.
Here is the full output of building pytorch (long):
https://gist.github.com/sparticlesteve/8e8c24317a423bddac9f85645f6132a2

Here is the full output of building horovod. Not a lot here, though:
https://gist.github.com/sparticlesteve/e43bdf651ab35cf010291273aa59afb7

**Comment by alsrgv** [comment]
@sparticlesteve, I think the issue is that you're using C++ compiler for C compilation.  Horovod currently using legacy CFFI PyTorch bindings which are done in C.  Replacing `export CC=CC` with `export CC=cc` in your Horovod build may fix this.

**Comment by sparticlesteve** [comment]
Hi @alsrgv, thanks a lot for spotting that typo. I do believe you were correct!
