### ISSUE TITLE
What is the batchsize when test for scaling efficiency ?

### ISSUE THREAD

**Issue by YuJingBaoBao** [uber/horovod#425]
I see “Horovod achieves 90% scaling efficiency for both Inception V3 and ResNet-101, and 68% scaling efficiency for VGG-16.” in README.md
Is the batchsize equal to 64 or as large as possible when test tensorflow benchmark?

**Comment by tgaddair** [comment]
Hey @YuJingBaoBao, per [this paper](https://arxiv.org/pdf/1706.02677.pdf) we keep the number of examples per worker constant at 32 for all our benchmarks.  This results in an effective minibatch size of **32 * k**, where k is the number of workers.

**Comment by YuJingBaoBao** [comment]
Thanks @tgaddair , so the scaling efficiency in README.md is for reference. If we set batchsize  as large as possible, we may get higher scaling efficiency, right ?

**Comment by tgaddair** [comment]
It's mostly about making sure the GPUs are being fully-utilized.

Large batch sizes will help ensure that you're using all of your available GPU memory.  At a certain point, the batch size may become so large that you're over the GPU memory limit, and that will not improve scaling efficiency.  

If the batch size is too small, then the GPU will not be taking full advantage of its hardware.

In general, we keep the number of examples per worker constant to scale the batch size linearly with the number of workers.  That way, if you're fully utilizing a single GPU with a given batch size on a single worker, and your cluster setup is consistent, then you should get close to linear scaling efficiency.

**Comment by YuJingBaoBao** [comment]
@tgaddair  Thank you very much. You made things really clear.
