### ISSUE TITLE
Pytorch example fails with OSError

### ISSUE THREAD

**Issue by rahul003** [uber/horovod#427]
This might not be a Horovod issue but I run into `OSError: Too many files open` when I try to run the [Horovod Pytorch Imagenet example](https://github.com/uber/horovod/blob/master/examples/pytorch_imagenet_resnet50.py). I also tried just running on a single GPU, it still crashes. I don't run into this issue when I use the Pytorch [example for training Imagenet](https://github.com/pytorch/examples/blob/master/imagenet/main.py). I was wondering if anyone faced this? I looked for this error in Pytorch forums, but none of the discussed solutions worked for me.

**Comment by tgaddair** [comment]
Hey @rahul003, have you tried increasing the maximum number of open files allowed on your system?  You can see an example of how to do this [here](https://www.tecmint.com/increase-set-open-file-limits-in-linux/).

**Comment by rahul003** [comment]
Not sure why, can't reproduce it today.
