### ISSUE TITLE
How to do transfer learning with tensorflow and use horovod

### ISSUE THREAD

**Issue by sumedhvdatar** [uber/horovod#428]
I am able to do transfer learning with tensorflow, I need a way to use horovod to integrate with existing code and the example code is not very helpful.

**Comment by tgaddair** [comment]
Hey @sumedhvdatar, can you give an example of what you're trying to do?  Even in a transfer learning setting, you'll typically have an optimizer that you can wrap with the `HorovodDistributedOptimizer`.

**Comment by sumedhvdatar** [comment]
Something like tensorflow for poets or tensorflow hub

**Comment by tgaddair** [comment]
There's retrain script for that example you can modify.  [Here](https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py#L796) is the section that initializes the optimizer.  You should be able to wrap that as shown in the Horovod examples:

```
hvd.init()

with tf.name_scope('train'):
    optimizer = tf.train.GradientDescentOptimizer(FLAGS.learning_rate)
    optimizer = hvd.DistributedOptimizer(optimizer)
    train_step = optimizer.minimize(cross_entropy_mean)
```

**Comment by sumedhvdatar** [comment]
Hi Travis

Thanks for letting me know I ll try that, also is der a way to use horovod
with spark and keras?

**Comment by tgaddair** [comment]
There is!  We have some docs on Keras [here](https://github.com/uber/horovod#keras).  As for Spark, there is some [experimental work ](https://docs.azuredatabricks.net/applications/deep-learning/distributed-deep-learning/horovod-estimator.html) that's been done, but not sure how far along it is (I haven't tried it yet).

**Comment by sumedhvdatar** [comment]
@tgaddair Uhmm! thats not very helpful. Can I use something hyperas to perform hyperparameter optimization on Horovod?

**Comment by alsrgv** [comment]
@sumedhvdatar, can you clarify what specifically you do not understand from the examples?  As for hyperas support, I made an example for you - https://gist.github.com/alsrgv/48cf1fe8552212e6b5131e8ae48e8c66.

**Comment by sumedhvdatar** [comment]
@alsrgv Hey thank you so much, I was looking for something like this. Thanks!
