### ISSUE TITLE
Question: when to use BroadcastGlobalVariablesHook?

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#440]
When calling hvd.BroadcastGlobalVariablesHook(0), should we call this once for the first epoch or calling for each epoch?

My current code looks like below. Should I call bcast_hook only for the first epoch index?

```
bcast_hook=hvd.BroadcastGlobalVariablesHook(0)
for epoch in range(100):
     ...
     transformer.train(train_input_fn, hooks=[bcast_hook], steps=10000)
     ...
```

**Comment by alsrgv** [comment]
@LiweiPeng, what is `transformer` in this example? Usually, you can call the broadcast hook only once.

**Comment by LiweiPeng** [comment]
Sorry, I should make it clear. 'transformer' is a wrapper around the google Transformer model for machine translation model.

**Comment by alsrgv** [comment]
In that case calling the broadcast once should be fine.
