### ISSUE TITLE
Question: should each process read a portion of the full input dataset?

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#441]
When using N processes in horovod, should each process read the full input dataset, or each process read 1/N input dataset? 

Will the following hvd code work properly?
```
# single process mode:
      src_dataset = tf.data.TextLineDataset(src_file)
# using hvd, I changed the above code to below
      src_dataset = tf.data.TextLineDataset(src_file).shard(hvd.size(), hvd.rank())
```

**Comment by alsrgv** [comment]
@LiweiPeng, it should read 1/Nth and your example is perfect!
