### ISSUE TITLE
Redundant ALLGATHER right after ALLREDUCE operations?

### ISSUE THREAD

**Issue by theJiangYu** [uber/horovod#445]
Hi, is there anyone could help with this issue? 
I am training a Transformer model using Horovod on multiple nodes. The ALLGATHER operation happens every batch, right after all ALLREDUCE operations. 
Is the ALLGATHER operation redundant, since we all ready have ALLREDUCE operations? 
The growing time spending on ALLGATHER with the number of nodes makes the distributed training unable to scale. 
Attached is the timeline for the ALLREDUCE and ALLGATHER operations. 
  
Thanks a lot! 
![image](https://user-images.githubusercontent.com/9773863/44125405-3f98f9a8-9fe7-11e8-9524-0c5307fd6f64.png)

**Comment by anpark** [comment]
that's ok. see #

**Comment by theJiangYu** [comment]
@anpark Thank you so much for your swift reply and the great info! 
Looking forward to the new method!
