### ISSUE TITLE
Is mpirun a necessary to launch distributed training?

### ISSUE THREAD

**Issue by weixsong** [uber/horovod#46]
Hi, 

Is distributed training with Horovod must use mpirun to distribute the training process?

I mean, could me run each process on local machine by manually and then Horvorod could find the cluster or peer node to do distributed computation?

Such as, 
In machine 1, I run "python train.py"
In machine 2, I also run "python train.py"

Is this OK?

**Comment by alsrgv** [comment]
Hi @weixsong,

At this point, Horovod uses MPI to coordinate what tensors should be reduced, gathered or broadcasted and in which order, so it's necessary to use `mpirun` to launch distributed training.

**Comment by weixsong** [comment]
@alsrgv , thanks very much.

**Comment by alsrgv** [comment]
I'll close this issue. Please re-open if you have any additional questions on the subject.
