### ISSUE TITLE
Recompiling modified Horovod inside pre-built docker container

### ISSUE THREAD

**Issue by aaron276h** [uber/horovod#463]
If we are using the uber/horovod pre-built container, and want to make custom modifications to Horovod and then recompile it, how would we go about doing that? So far we have been manually modifying ```/usr/local/lib/python2.7/dist-packages/horovod``` which doesn't seem to be a very clean solution.

**Comment by tgaddair** [comment]
Hey @aaron276h, this is how I usually do it.

First create a virtual environment:

```
virtualenv --system-site-packages env
source env/bin/activate
```

Clone Horovod:

```
git clone https://github.com/uber/horovod.git
```

Run these commands to rebuild Horovod:

```
pip uninstall -y horovod
cd horovod
rm -rf build/ dist/
HOROVOD_WITH_PYTORCH=1 HOROVOD_WITH_TENSORFLOW=1 \
HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/usr/local/nccl python \ 
setup.py install
cd -
```

**Comment by aaron276h** [comment]
@tgaddair Thanks that worked for me.
