### ISSUE TITLE
AttributeError: 'module' object has no attribute 'broadcast_optimizer_state'

### ISSUE THREAD

**Issue by czhang96** [uber/horovod#464]
https://github.com/uber/horovod/blob/68f525c64cdd5a31536f5485448960fbb00d19fc/examples/pytorch_imagenet_resnet50.py#L136

I'm getting `AttributeError: 'module' object has no attribute 'broadcast_optimizer_state'` for this line. Is the example outdated?

**Comment by tgaddair** [comment]
Hey @czhang96, what version of Horovod are you running?  The function `broadcast_optimizer_state` was added in the most recent build: `v0.13.11`.

**Comment by czhang96** [comment]
Thanks! It was me, not the example that was outdated :)
