### ISSUE TITLE
mpirun crashes without any error codes

### ISSUE THREAD

**Issue by andreynikk** [uber/horovod#469]
Hi,

I've installed everything successfully and verified its all configured successfully (passed all NCCL Tests).
I'm running a single host with 8 GPUs.
I'm running keras code with tensorflow backend.

this is the command I am running:
    /usr/loc/bin/mpirun -np 8 \
        -H localhost:8 \
        -bind-to none -map-by slot \
        -x NCCL_DEBUG=DEBUG -x PATH \
        -mca pml ob1 -mca btl ^openib \
        python train_multi_gpu.py

from the output it looks like all the GPUs are assigned correctly and I see a slight gpu usage on all gpus, and when reaching the epochs output part of keras:
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
(1 for each GPU)

this is the error I get:
/-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
/-------------------------------------------------------

/--------------------------------------------------------------------------
mpirun noticed that process rank 7 with PID 0 on node HOSTNAME exited on signal 9 (Killed).
/--------------------------------------------------------------------------

without any additional errors.

How can I see the errors from keras/tensorflow or is there a way to increase mpirun verbosity?

**Comment by alsrgv** [comment]
@andreynikk, the message `mpirun noticed that process rank 7 with PID 0 on node HOSTNAME exited on signal 9 (Killed).` indicates that somebody or something has killed your training script with `kill -9 <pid>` command or its equivalent.  Are you the only user on the system?  Are there any messages in `dmesg`?

**Comment by andreynikk** [comment]
@alsrgv I've managed to get it to work with lower batch size, which is good.
Yes I'm the only user on the system, it looks like it was going OOM.
what I dont understand is why TF goes OOM, a V100 card has 16GB of memory and the issue occurs on 1024 batch size:
OOM when allocating tensor with shape[1024,42,32704] and type float
this tensor should allocate 11GB...

but this is not a horovod issue, thanks for your reply, you can close the issue.
