### ISSUE TITLE
I am working on a 3-node system with 8 GPUs/ node. I was wondering if its possible to specify the GPUs you want to use across an arbitrary number of nodes??   

### ISSUE THREAD

**Issue by Braigns** [uber/horovod#470]

**Comment by tgaddair** [comment]
Hey @Braigns, yes, if I understand your question correctly, you can specify which GPU you want to use for each process.

For TensorFlow we specify the visible device list for each process:

```
config.gpu_options.visible_device_list = str(hvd.local_rank())
```

You can change `str(hvd.local_rank())` to a specific if GPU you'd like.  Is that what you're trying to achieve?

**Comment by Braigns** [comment]
@tgaddair Great thank you.
