### ISSUE TITLE
Does it need to specify the cpu device, when use the tf.train.batch function

### ISSUE THREAD

**Issue by LittleDonkey1203** [uber/horovod#479]
If yes, how to do this in horovod?
If not, is it automatically identifies which device need to be used in horovod?

**Comment by tgaddair** [comment]
Hey @LittleDonkey1203, could you provide some example code of what you're trying to achieve?

In general, you can restrict Horovod/Tensorflow to using a specific CPU with `tf.device`:

```
with tf.device("/cpu:0"):
    tensor = ...
```

The more common approach in Horovod is to pin each process to a single GPU:

```
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
config.gpu_options.visible_device_list = str(hvd.local_rank())
```

If you don't specify, Tensorflow will make use of both GPUs and CPUs where available.  If you want to know which device a particular tensor is placed on, you can set `config.log_device_placement = True`.

**Comment by LittleDonkey1203** [comment]
Got it! I'll close the issue, Thank U.:)
