### ISSUE TITLE
FYI, BatchAI added a demo of running Horovod on a gpu cluster

### ISSUE THREAD

**Issue by AlexanderYukhanov** [uber/horovod#48]
FYI, we have added a demo on how to run horovod on Azure Batch AI. https://github.com/Azure/BatchAI/tree/master/recipes/Horovod

Thanks,
Alex

**Comment by alsrgv** [comment]
Hi @AlexanderYukhanov, this is great!

Thanks for the reminder, let's use this issue as a tracking issue until this gets added to the README upon next docs update.
