### ISSUE TITLE
AlexNET pytorch with Horovod

### ISSUE THREAD

**Issue by abidmalikwaterloo** [uber/horovod#485]
Does anyone try pytorch with Horovod? especially AlexNET?

Thanks

**Comment by bapriddy** [comment]
@alsrgv  @tgaddair  -- I ran resnet50 with pytorch horovod.  They have an example code.  You don't need to do much to get it running.  I'd say it's impressive and probably getting better...

**Comment by tgaddair** [comment]
Hey @abidmalikwaterloo, here's the [PyTorch example](https://github.com/uber/horovod/blob/master/examples/pytorch_imagenet_resnet50.py) @bapriddy was referring to.

I'm going to close this for now, but feel free to open a new issue if you have any follow-up questions.
