### ISSUE TITLE
device_dense

### ISSUE THREAD

**Issue by tickleliu** [uber/horovod#496]

**Comment by tgaddair** [comment]
Hey @tickleliu, did you have a question, or can I close this issue?

**Comment by tickleliu** [comment]
sorry for my wrong operation，just delete it


| |
刘明录
邮箱：tickleliu@163.com
|

签名由 网易邮箱大师 定制

On 09/14/2018 09:44, Travis Addair wrote:

Hey @tickleliu, did you have a question, or can I close this issue?
