### ISSUE TITLE
Quick questions: feeding images to GPUs

### ISSUE THREAD

**Issue by experiencor** [uber/horovod#50]
Thanks for a great library.

I have 2 quick questions.

In the context of the Keras example, each GPU reads the same set of images in each epoch, possibly in different orders. 

So the time it takes to make an epoch is independent of the number of GPUs. Is this understanding correct? 

It may happen that different GPUs may read a few same images in a batch. Is there any easy way to make sure that each GPU reads a different set of images?

**Comment by alsrgv** [comment]
Hi @experiencor,

You are right, the Keras example provided makes it possible for an occasional batch with the same image repeated twice to happen.  I don't believe such rare occasions would have any substantial negative effect on the training.  Did you have an experience where that was not the case?

**Comment by experiencor** [comment]
@alsrgv I have not encountered this issue in my code.

**Comment by alsrgv** [comment]
@experiencor I may have had rare batches with duplicate examples, but I really doubt they can have a noticeable impact.

**Comment by alsrgv** [comment]
I'll close this issue. Please feel to re-open if you have additional questions.
