### ISSUE TITLE
Running horovod on LSTM network

### ISSUE THREAD

**Issue by sumedhvdatar** [uber/horovod#500]
I am running a LSTM network with Horovod and I see that after ~75 epochs, training hangs.

**Comment by tgaddair** [comment]
Hey @sumedhvdatar, is there any output when it hangs?  Are you able to resume from a previous checkpoint without hanging at the same spot?

**Comment by sumedhvdatar** [comment]
@tgaddair Looks like i figured out the tensorboard problem as well. Horovod+Keras does not require log_dir as a parameter in tensorboard. This is a slight deviation from Keras tensorboard documentation. When I removed log_dir parameter from Tensorboard, code started working and I got the required visualizations.

Let me know if the issue has to be closed.

**Comment by sumedhvdatar** [comment]
@tgaddair Sure, thanks for your support.
