### ISSUE TITLE
Horovod error: Read -1, expected .....

### ISSUE THREAD

**Issue by UditGupta10** [uber/horovod#503]
Upon running example tensorflow_word2vec.py on 4 gpus single node, getting the error: [1f02ee14cb12:02020] Read -1, expected 150528, errno = 1.
The training completes but does not print the mentioned lines in code.
Why does this error occur?
What are the implication and how severe is this error?
What can be done to resolve it?

Thanks

**Comment by tgaddair** [comment]
Hey @UditGupta10, per #243 those messages are typical in Docker and considered harmless.  Which lines aren't being printed?

**Comment by UditGupta10** [comment]
The print statement inside code works fine for 1 process, but for multiple gpus I get Read -1, expected 150528, errno = 1 until the end of training. This is for tensorflow_word2vec.py example run in docker (built using Dockerfile provided).

**Comment by tgaddair** [comment]
One option to remove those messages is to filter them out.  When you run your training command:

```
mpirun ... |& grep -v "Read -1"
```

**Comment by UditGupta10** [comment]
This helped. Thanks

**Comment by austinmw** [comment]
@tgaddair  Hi, why does docker produce these stderr and why is it considered harmless?

**Comment by tgaddair** [comment]
Hey @austinmw, there's some more context here: https://github.com/open-mpi/ompi/issues/4948.

My understanding is that if you run your container in privileged mode, then these messages should go away.

**Comment by austinmw** [comment]
@tgaddair You don't happen to know if there's a way to run SageMaker in privileged mode do you? 
I was able to remove these messages by specifying `os.environ['OMPI_MCA_btl_vader_single_copy_mechanism']='none'` at the top of my script, however I'm concerned that this will lead to degraded performance.

**Comment by tgaddair** [comment]
Hey @austinmw, not sure about SageMaker, unfortunately.  

Regarding the env variable, that's a good find!  Assuming you're using GPUs / NCCL as well, this should not have a major impact on performance (MPI involvement is pretty minimal in Horovod when using NCCL).
