### ISSUE TITLE
question: what's horovod's plan for FP16 support?

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#512]
Horovod has branches to support FP16 (e.g. fp16_divide_before_sum). What's the plan to merge FP16 support into master? Thanks,

**Comment by LiweiPeng** [comment]
@alsrgv Yes, I tried the fp16_divide_before_sum branch for a nmt transformer model. I got about 17% throughput speedup with batch size 4096. When I doubled the batch size to be 8192, the throughput speedup is about 6.5%. This can be explained by more time is spent on computation with bigger batch size.

**Comment by tgaddair** [comment]
#529 merges these changes into master (sum before divide).  Let me know if anything unexpected comes up!

**Comment by LiweiPeng** [comment]
Thanks.

**Comment by terrykong** [comment]
Does Horovod plan on supporting the bfloat16 format for Tensorflow?

**Comment by alsrgv** [comment]
@LiweiPeng, Horovod 0.15.0 with FP16-on-GPU support has been released just now.  We've also observed ~15% improvements on ImageNet training task.

@terrykong, not immediately, but it's an interesting future direction & integration point!
