### ISSUE TITLE
Still ask for password for root with ssh-keygen configured 

### ISSUE THREAD

**Issue by zhimengfan1990** [uber/horovod#514]
Hi, I configured the ssh-keygen for root account, and put the keys in `/mnt/share/ssh`. Then I run docker and mount `/mnt/share/ssh`(in host) to `/root/.ssh`(in docker). Then I launched the ssh daemon on the slave machine, and finally I run `ssh root@my_slave_machine -p 12345` on my host machine. But It still ask me for the password for root of the slave machine. How can I solve this issue? Thanks!

**Comment by tgaddair** [comment]
Hey @zhimengfan1990, there are a number of possible causes here.  I'd suggest taking a look at [this](https://unix.stackexchange.com/questions/36540/why-am-i-still-getting-a-password-prompt-with-ssh-with-public-key-authentication) thread on the Unix StackExchange and let me know if any of those suggestions work in your case.

**Comment by zhimengfan1990** [comment]
Thanks @tgaddair , this is a ssh key file/folder ownership and mode issue, fixed it now! Thanks!

**Comment by tgaddair** [comment]
Great!  Glad you got it sorted out.
