### ISSUE TITLE
Compare with vanilla tensorflow

### ISSUE THREAD

**Issue by UditGupta10** [uber/horovod#517]
For 1 GPU, I observed that horovod (with 1 process) takes 40% more time as compared to normal tensorflow program, why is that the case? What causes the overhead ?

**Comment by tgaddair** [comment]
Hey @UditGupta10, could you share the benchmark you're running to arrive at that 40%?  I just ran a quick experiment on a single GPU with the `tensorflow_mnist.py` example.  It took about the same amount of time with `mpirun python ...`, `python ...`, and removing all Horovod code.
