### ISSUE TITLE
Got similar error when installing Horovod under Ubuntu 16.04 (as I got under Windows 10)

### ISSUE THREAD

**Issue by shinechou** [uber/horovod#53]
@alsrgv: I got similar error as I got under windows 10, could you please help me? Thanks a lot in advance. I´ve installed tensorflow-gpu (version1.3.0) and Cuda 8/CudNN 6, it works well with python 2.7 when I run the script without horovod, and I also installed openmpi-3.0/NCCL2.0.

$sudo -H HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod -v
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Collecting horovod
  1 location(s) to search for versions of horovod:
  * https://pypi.python.org/simple/horovod/
  Getting page https://pypi.python.org/simple/horovod/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/horovod/ HTTP/1.1" 200 915
  Analyzing links from page https://pypi.python.org/simple/horovod/
    Found link https://pypi.python.org/packages/07/bb/f2edeee902a6c5e345f5cc6d8ba3f5b6805506489da4bb6cf35665cccd95/horovod-0.9.5.tar.gz#md5=a883937ed44f95a98b434a3c13178aa0 (from https://pypi.python.org/simple/horovod/), version: 0.9.5
    Found link https://pypi.python.org/packages/11/48/e56cb33974a7fc24252e304e7e60b7b892eb7c1093099493913880b6f4ce/horovod-0.9.8.tar.gz#md5=e981a37f7ee6c1f4ba5dcac637184e7a (from https://pypi.python.org/simple/horovod/), version: 0.9.8
    Found link https://pypi.python.org/packages/2c/c4/cd8d9d1136465e6f23a535cc4c49fad24da92982f1275d7c38a564d5417b/horovod-0.9.9.tar.gz#md5=1d680e9ffe37552f4510c29e0fcfefc3 (from https://pypi.python.org/simple/horovod/), version: 0.9.9
    Found link https://pypi.python.org/packages/58/8d/6a84cd3fa9bdeb96e6c162d26d05c6e594c38f788005f2d2f42ed2bfcfe5/horovod-0.9.1.tar.gz#md5=277e9c1bc7b459a49eb1aca7731ca5bd (from https://pypi.python.org/simple/horovod/), version: 0.9.1
    Found link https://pypi.python.org/packages/7f/78/3c42b58fa37d5811eb2178e6d8f0e586b18fd883f8575a2da8a7bce9b02b/horovod-0.9.4.tar.gz#md5=d436ab4b0efa0734f270f4ba24d1d665 (from https://pypi.python.org/simple/horovod/), version: 0.9.4
    Found link https://pypi.python.org/packages/8a/82/085978898e51938791c35949fb757905e746503369e898074f76f6044d32/horovod-0.9.3.tar.gz#md5=4f4dd52b7763ec7d2da0da55ad04aeff (from https://pypi.python.org/simple/horovod/), version: 0.9.3
    Found link https://pypi.python.org/packages/8c/91/91495a609f7b4077ba4eeb00c8494bf29eb94de76e5a7a458cf57add7f0e/horovod-0.9.0.tar.gz#md5=1cd031e8d892cab8e2cf05cfe2caba55 (from https://pypi.python.org/simple/horovod/), version: 0.9.0
    Found link https://pypi.python.org/packages/9c/62/3d37b3697a06e0c5ef97fd01f690f4b94509486df4f5401a65461e110d1c/horovod-0.9.7.tar.gz#md5=42c02e8e117303e35744fdce39d79ac5 (from https://pypi.python.org/simple/horovod/), version: 0.9.7
    Found link https://pypi.python.org/packages/9c/be/5aebe7ecd7024e0ad12196127d22488a73defa3c1b6fac0eea20d7aa6115/horovod-0.9.6.tar.gz#md5=bc4ae17e261dffef0b9ce1e125336a75 (from https://pypi.python.org/simple/horovod/), version: 0.9.6
    Found link https://pypi.python.org/packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz#md5=694ca17e718cd3d62831e23dbf1f5437 (from https://pypi.python.org/simple/horovod/), version: 0.9.10
    Found link https://pypi.python.org/packages/fc/53/314d19c558f726e480489e97d576883b6bd79b7d811913216b30d7849b8b/horovod-0.9.2.tar.gz#md5=804dbcd20c1de82c7adb5213c4d0363c (from https://pypi.python.org/simple/horovod/), version: 0.9.2
  Using version 0.9.10 (newest of versions: 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10)
  "GET /packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz HTTP/1.1" 200 64842
  Downloading horovod-0.9.10.tar.gz (64kB)
  Downloading from URL https://pypi.python.org/packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz#md5=694ca17e718cd3d62831e23dbf1f5437 (from https://pypi.python.org/simple/horovod/)
    100% |████████████████████████████████| 71kB 11.9MB/s 
  Running setup.py (path:/tmp/pip-build-wrtVwH/horovod/setup.py) egg_info for package horovod
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/horovod.egg-info
    writing pip-egg-info/horovod.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/horovod.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/horovod.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/horovod.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-wrtVwH/horovod has version 0.9.10, which satisfies requirement horovod from https://pypi.python.org/packages/b1/83/ac3d9499fdf9173a5870d6fff0a58a4e35240a9c17ce556c3c59cb1a4533/horovod-0.9.10.tar.gz#md5=694ca17e718cd3d62831e23dbf1f5437
Installing collected packages: horovod
  Running setup.py install for horovod ...     Running command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wrtVwH/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7mUT3A-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/local/lib/python2.7/dist-packages/tensorflow/core -ltensorflow_framework -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    /usr/bin/ld: cannot find -ltensorflow_framework
    collect2: error: ld returned 1 exit status
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/local/lib/python2.7/dist-packages/tensorflow/core -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/local/lib/python2.7/dist-packages/tensorflow/include -I/usr/local/lib/python2.7/dist-packages/tensorflow/include/external/nsync/public -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o -L/usr/local/lib/python2.7/dist-packages/tensorflow/core -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.so
    mpicxx: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory
    error: mpicxx -show failed (see error below), is MPI in $PATH?
    Note: If your version of MPI has custom command to show compilation flags, please specify it via HOROVOD_MPICXX_SHOW environment variable.

    Traceback (most recent call last):
      File "/tmp/pip-build-wrtVwH/horovod/setup.py", line 107, in get_mpi_flags
        shlex.split(show_command), universal_newlines=True).strip()
      File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    CalledProcessError: Command '['mpicxx', '-show']' returned non-zero exit status 127

error
Cleaning up...
  Removing source in /tmp/pip-build-wrtVwH/horovod
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wrtVwH/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7mUT3A-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wrtVwH/horovod/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 886, in install
    spinner=spinner,
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 736, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-wrtVwH/horovod/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-7mUT3A-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-wrtVwH/horovod/
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)

**Comment by alsrgv** [comment]
Hi @shinechou,

Seems like you error is `mpicxx: error while loading shared libraries: libopen-pal.so.40: cannot open shared object file: No such file or directory`.

I've seen this error happen before when I had two versions of Open MPI installed in the system or had it installed in a non-standard location.

There are a couple of things you can try:
1. `export LD_PRELOAD=$YOUR_MPI_LOCATION/lib/libmpi.so`
2. Compile Open MPI with `--enable-orterun-prefix-by-default`.

**Comment by shinechou** [comment]
Hi @alsrgv: thank you very much. I could try your possible solutions tomorrow when I go to office.
However, I think the problem comes earlier than this MPI problem, have you seen the error message "/usr/bin/ld: cannot find -ltensorflow_framework"? It seems that the setp script coudln't find tensorflow lib. Or I should install tensorflow instead of tensorflow-gpu? Thanks in advance.

**Comment by alsrgv** [comment]
@shinechou, you can ignore "-ltensorflow_framework" error and just look at the last error. The reason is that over time build instructions for TensorFlow plugins have changed, and we just try all possible options for TensorFlow 1.1.0+ - so there could be errors from unsuccessful attempts, which can be ignored. Only the last error is relevant.

**Comment by shinechou** [comment]
@alsrgv: thank you so much. I'll try this out tomorrow and let you know if it works.

**Comment by shinechou** [comment]
@alsrgv: both your solutions didn´t work for me,  but ´**sudo ldconfig**´ works.

**Comment by alsrgv** [comment]
@shinechou, great!  I'll add this to the troubleshooting docs in the next doc update round.
