### ISSUE TITLE
pytorch example raise OSError: [Errno 24] Too many open files with 0.4.1

### ISSUE THREAD

**Issue by tonysy** [uber/horovod#540]
When I run `python pytorch_mnist.py`, it will raise error "OSError: [Errno 24] Too many open files". after the first epoch training finished.  And my pytorch version is "0.4.1", horovod version is "0.15.0".

If I use pytorch with 0.4.0, it will run success. Hope the team will support 0.4.1 soon. Thanks.

**Comment by alsrgv** [comment]
@tonysy, can you try rebooting your server?

**Comment by tonysy** [comment]
Ok, it works

**Comment by lemairecarl** [comment]
Rebooting does not fix the issue for me. I need to raise the limit for the number of open files of Ubuntu.

**Comment by alsrgv** [comment]
@lemairecarl, you can follow this guide - https://underyx.me/2015/05/18/raising-the-maximum-number-of-file-descriptors

**Comment by lemairecarl** [comment]
I don't have access to sudo on that machine. My workaround is to reduce the number of DataLoader workers.
