### ISSUE TITLE
Can't install horovod on power8 machine

### ISSUE THREAD

**Issue by ghltshubh** [uber/horovod#541]
I am facing issue installing horovod on power8. I am getting the following error:

```
/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/compiler_compat/ld: skipping incompatible /autofs/nccs-svm1_home1/shubhankar/nccl-2.1/lib/libnccl_static.a when searching for -lnccl_static
/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/compiler_compat/ld: skipping incompatible /autofs/nccs-svm1_home1/shubhankar/nccl-2.1/lib//libnccl_static.a when searching for -lnccl_static
/ccs/home/shubhankar/miniconda3/envs/tf_p3.5/compiler_compat/ld: cannot find -lnccl_static
collect2: error: ld returned 1 exit status
error: NCCL 2.0 library or its later version was not found (see error above).
Please specify correct NCCL location with the HOROVOD_NCCL_HOME environment variable or combination of HOROVOD_NCCL_INCLUDE and HOROVOD_NCCL_LIB environment variables.
    
    HOROVOD_NCCL_HOME - path where NCCL include and lib directories can be found
    HOROVOD_NCCL_INCLUDE - path to NCCL include directory
    HOROVOD_NCCL_LIB - path to NCCL lib directory

```
Already have the path set in .bashrc as well as tried the following:

`(tf_p3.5) -bash-4.2$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/autofs/nccs-svm1_home1/shubhankar/nccl-2.1 HOROVOD_NCCL_INCLUDE=/autofs/nccs-svm1_home1/shubhankar/nccl-2.1/include HOROVOD_NCCL_LIB=/autofs/nccs-svm1_home1/shubhankar/nccl-2.1/lib pip install --no-cache-dir horovod
`

**Comment by tgaddair** [comment]
Hey @ghltshubh, can you provide the full `pip install` command you ran, along with the complete output in a gist?  Also, can you verify that you went through the [Horovod on GPU](https://github.com/uber/horovod/blob/master/docs/gpus.md) docs?

**Comment by ghltshubh** [comment]
Yes I did. Btw I am using IBMs spectrum MPI and not sure if I should use the bottom command or not.

**Comment by tgaddair** [comment]
My best guess at the moment is that there's a system incompatibility with your version of NCCL similar to #107.  It might also be an issue with your conda environment.

A couple things to try would be: reinstall Horovod in a fresh conda environment, and try a different version of NCCL (2.2 or 2.3).

**Comment by ghltshubh** [comment]
I found a glitch that I have glibc 2.17 whereas NCCL 2 works for glibc >2.19. Can this be a real issue?

**Comment by tgaddair** [comment]
Quite possibly.  Can you try updating your version of glibc?

**Comment by ghltshubh** [comment]
I am still getting the same error. I am on a shared machine can't do much on that end.

**Comment by alsrgv** [comment]
@ghltshubh, NVIDIA recently has open sourced NCCL 2, so you can try building your own version.  Can you try:
```
$ git clone https://github.com/NVIDIA/nccl && cd nccl
$ make -j $(nproc)
$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_NCCL_HOME=/path/to/nccl/build pip install --no-cache-dir horovod
```

**Comment by ghltshubh** [comment]
@alsrgv Is $(nproc) required here?

**Comment by alsrgv** [comment]
@ghltshubh, can you upgrade to TensorFlow 1.11.0?

**Comment by ghltshubh** [comment]
I was able to build and install horovod using nccl 2.3 by running:

`cp -r /ccs/home/shubhankar/tensorflow/tensorflow/compiler/ /ccs/home/shubhankar/miniconda3/envs/tf_p3.5/lib/python3.5/site-packages/tensorflow/include/tensorflow/`
