### ISSUE TITLE
Dockerfile TF ver 1.11.0 not 0.11.0

### ISSUE THREAD

**Issue by bapriddy** [uber/horovod#558]
@alsrgv  The heading for the docker file is wrong

Upgrade Dockerfile to TensorFlow 0.11.0, PyTorch 0.4.1 and Open MPI 3…

https://github.com/uber/horovod/blob/master/Dockerfile

It's clear when you glance at the code (obviously).

Nice code! Everything works SO FAR...

**Comment by alsrgv** [comment]
@bapriddy, thanks!  Very good observation, I guess I'm still living in the past :-)  I've updated PRs, but the commit title will stay the same until we update again - which should be pretty soon, TF 1.12.0 is around the corner!
