### ISSUE TITLE
To run on 4 machines with 1 GPUs each using Open MPI

### ISSUE THREAD

**Issue by saikishor** [uber/horovod#56]
To run on 4 different machine that has 1 GPU and connected by LAN, do I need to use the following command in any one of the system or use it on every computer changing the position of server IP's?

> mpirun -np 4 -x LD_LIBRARY_PATH -H server1:4,server2:4,server3:4,server4:4 python train.py

**Comment by ydp** [comment]
I have the same question, I have 4 machine with 1 gpu,
run command:
mpirun -np 4 -x LD_LIBRARY_PATH -H server1:1,server2:1,server3:1,server4:1 python train.py
will fail with server1:1 name or service cannot resolved
so I have to use 
mpirun -np 4 -x LD_LIBRARY_PATH -H server1,server2,server3,server4 python train.py
then, how do I specifiy the GPU number for each machine.
my Openmpi version is:
mpirun (Open MPI) 3.0.0
and I run mpirun as root user

**Comment by ydp** [comment]
plus, I run the tensorflow_mnist.py on multiple node, the process just block, maybe it's because I did not specify GPU number?

**Comment by alsrgv** [comment]
@saikishor, no, you can run the mpirun command once on any of those servers.

@ydp, I remember seeing `server1:1 name or service cannot resolved` with very old Open MPI, definitely not 3.0.0. Do you happen to have two versions of MPI installed in your system? This may explain process blocking, too.

I that's the case, you can fix this by making sure `$PATH` points to Open MPI 3.0.0 first, e.g.:
```
$ export PATH=/path/to/openmpi-3.0.0/bin:$PATH
```

Then, to be on the safe side, reinstall Horovod and re-run, as it may have compiled against wrong version of MPI:
```
$ pip uninstall -y horovod
$ <HOROVOD FLAGS YOU SPECIFIED BEFORE> pip install horovod --no-cache-dir
<replicate to other servers>
$ mpirun -np 4 -x LD_LIBRARY_PATH -H server1:1,server2:1,server3:1,server4:1 python train.py
```

If you see messages about mismatch versions, etc, you may need to explicitly provide path to mpirun:
```
$ mpirun --prefix /path/to/openmpi-3.0.0 -np 4 -x LD_LIBRARY_PATH -H server1:1,server2:1,server3:1,server4:1 python train.py
```

**Comment by ydp** [comment]
@alsrgv  thanks for your help, I can run the program now, but get other error, I will open a new issue.

as for my problem, I first download openmpi-3.0.0.tar.gz on local machine, setup env, then I start to run on kubernetes, so I make a docker image, in the dockerfile I write apt-get install ..., which is not 3.0.3, but 1.10.0, so it is version problem, I rebuild the docker with tar.gz compiled, and this problem solved.

Also I think we should include the version in document for someone like me not familiar with mpi.

**Comment by saikishor** [comment]
@alsrgv Thank you for your comments. I have one more question based on your comment. As you said, I can run the command once on any of those systems connected by LAN. Will this still work even the tensorflow is not installed on other system on LAN(The systems whose GPU we are using for running training).

@ydp from your previous comment I see that you are using docker for this purpose. It's a very good move, but how did you manage to communicate between docker containers on different hosts to enable this kind of training. Your guidelines would be really helpful.

**Comment by shinechou** [comment]
what does "server1:1" mean in the command line? "server1" is the ip-address/name of your first server or just use "server1"? ":1" means you have 1 GPU for this node?

**Comment by ydp** [comment]
@saikishor  I run a kubernetes cluster with flannel installed

@shinechou  I think you are right

**Comment by alsrgv** [comment]
@saikishor, you need to have TensorFlow, MPI and NCCL installed on every server. The source code of your model should be available on every server as well.

Docker can be a good idea to simplify management of TensorFlow, MPI, NCCL and source code. You can do `docker run --network=host your-container` to map all the host network interfaces inside the container.

Additionally, if you're running Docker, you should add `-mca btl_tcp_if_exclude docker0,lo` to your `mpirun` command to make sure that MPI will not try to communicate via `docker0` or `lo` interfaces, which is not going to work.

@shinechou, yes - `:1` means that one process would be launched on that server, corresponding to one GPU.  You should use `-H <hostname>:<n-gpus>,<hostname>:<n-gpus>` to launch an appropriate number of workers since each worker uses one GPU.

**Comment by saikishor** [comment]
@alsrgv Thank you for your useful information.

**Comment by shinechou** [comment]
@ydp, @alsrgv: thank both of you. I've figured it out by looking into openmpi documentation.

**Comment by alsrgv** [comment]
Closing this issue. Feel free to reopen if you have more questions.

**Comment by whr94621** [comment]
> @saikishor, you need to have TensorFlow, MPI and NCCL installed on every server. The source code of your model should be available on every server as well.
> 
> Docker can be a good idea to simplify management of TensorFlow, MPI, NCCL and source code. You can do `docker run --network=host your-container` to map all the host network interfaces inside the container.
> 
> Additionally, if you're running Docker, you should add `-mca btl_tcp_if_exclude docker0,lo` to your `mpirun` command to make sure that MPI will not try to communicate via `docker0` or `lo` interfaces, which is not going to work.
> 
> @shinechou, yes - `:1` means that one process would be launched on that server, corresponding to one GPU. You should use `-H <hostname>:<n-gpus>,<hostname>:<n-gpus>` to launch an appropriate number of workers since each worker uses one GPU.

If I want to specify which GPU to use on each remote node, how could I do this?

**Comment by alsrgv** [comment]
@whr94621, you can specify it when you pin GPU.  By default, [we pin to local rank of the process](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist_estimator.py#L143), but you can pin to a different GPU as well:
```python
    # map process rank (0 .. N-1) to GPU ID to use
    map_rank_to_gpu = {
        0: '2',
        1: '3',
        2: '0,
        ...
    }

    # Horovod: pin GPU to be used to process local rank (one GPU per process)
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.visible_device_list = map_rank_to_gpu[hvd.rank()] # GPU that you want to use on this process
```

P.S. Please open new issues for unrelated questions.
