### ISSUE TITLE
tensorflow_mnist.py hangs at hvd.init(). Already tried password less ssh authentication and removing non-routed network

### ISSUE THREAD

**Issue by samyam** [uber/horovod#561]
When I try to run tensorflow_mnist.py in the examples, I cannot get past hvd.init(). It just hangs there. I can ssh into localhost without any prompt, and I have removed the non-routed network. 

Can someone please help? I have been stuck here for the last two days

I am attaching a log from strace -f -e 'trace=!poll'
[tensorflow-mnist-strace.log.zip](https://github.com/uber/horovod/files/2475004/tensorflow-mnist-strace.log.zip)

Below are some information that may be relevant:

I have installed Cuda 9.0, NCCL 2, Tensorflow 1.11, OpenMPI 3.1.2 with Horovod. 

Execution command: 
mpirun -np 2 \
       -H localhost:2 \
       -bind-to none -map-by slot \
       -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
       -x NCCL_SOCKET_IFNAME=^eno1 \
       -mca pml ob1 -mca btl ^openib \
       -mca btl_tcp_if_exclude lo,eno1 \
           python tensorflow_mnist.py

(venv) samyam@HP-Z840-DL-Opt:~/Applications/horovod/examples$ ifconfig
eno1      Link encap:Ethernet  HWaddr 40:b0:34:44:53:3e  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:20 Memory:f5300000-f5320000 

enp5s0    Link encap:Ethernet  HWaddr 40:b0:34:44:53:3f  
          inet addr:10.125.164.70  Bcast:10.125.167.255  Mask:255.255.252.0
          inet6 addr: fe80::df0a:4cec:a57a:37cf/64 Scope:Link
          inet6 addr: 2001:4898:200:5:7837:ce40:f0a8:3fff/64 Scope:Global
          inet6 addr: 2001:4898:200:5:6728:425b:3950:2628/64 Scope:Global
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:63392 errors:0 dropped:0 overruns:0 frame:0
          TX packets:22587 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:18323831 (18.3 MB)  TX bytes:4234996 (4.2 MB)
          Memory:f5100000-f517ffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5865 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5865 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:561806 (561.8 KB)  TX bytes:561806 (561.8 KB)

nvidia-smi

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN V             Off  | 00000000:03:00.0 Off |                  N/A |
| 29%   43C    P8    N/A /  N/A |      0MiB / 12036MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  TITAN Xp            Off  | 00000000:04:00.0  On |                  N/A |
| 23%   30C    P8    14W / 250W |    311MiB / 12192MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1      1533      G   /usr/lib/xorg/Xorg                           172MiB |
|    1      3351      G   compiz                                       137MiB |
+-----------------------------------------------------------------------------+

**Comment by alsrgv** [comment]
@samyam, can you check if you can `ssh 10.125.164.70`?  Strace gets stuck right around:
```
[pid 27419] <... accept resumed> {sa_family=AF_INET, sin_port=htons(58688), sin_addr=inet_addr("10.125.164.70")}, [16]) = 26
```

**Comment by samyam** [comment]
It gave me a yes/no prompt. I said yes. I re ran the tensorflow-mnist, but its still hanging. I am attaching the log of the run after fixing the above ssh. 
[tensorflow-mnist-strace-2.log.zip](https://github.com/uber/horovod/files/2475025/tensorflow-mnist-strace-2.log.zip)
The last few lines from the log before running into the infinte nanosleep loop are 

[pid 37000] read(9, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 37000] socket(PF_INET, SOCK_STREAM, IPPROTO_IP <unfinished ...>
[pid 36999] <... nanosleep resumed> NULL) = 0
[pid 37000] <... socket resumed> )      = 10
[pid 36999] nanosleep({0, 100000},  <unfinished ...>
[pid 37000] fcntl(10, F_GETFD <unfinished ...>
[pid 36997] <... nanosleep resumed> NULL) = 0
[pid 37000] <... fcntl resumed> )       = 0
[pid 36997] nanosleep({0, 100000},  <unfinished ...>
[pid 37000] fcntl(10, F_SETFD, FD_CLOEXEC) = 0
[pid 37000] connect(10, {sa_family=AF_INET, sin_port=htons(55203), sin_addr=inet_addr("10.125.164.70")}, 16 <unfinished ...>
[pid 36841] <... nanosleep resumed> NULL) = 0
[pid 36841] nanosleep({0, 1000000},  <unfinished ...>
[pid 36999] <... nanosleep resumed> NULL) = 0
[pid 37000] <... connect resumed> )     = 0
[pid 36999] nanosleep({0, 100000},  <unfinished ...>
[pid 36997] <... nanosleep resumed> NULL) = 0
[pid 36840] <... select resumed> )      = 1 (in [20], left {3599, 873521})
[pid 37000] sendto(10, "Ho\0\1\0\0\0\0Ho\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0171.10"..., 43, 0, NULL, 0 <unfinished ...>
[pid 36997] nanosleep({0, 100000},  <unfinished ...>
[pid 36840] accept(20,  <unfinished ...>
[pid 37000] <... sendto resumed> )      = 43
[pid 36840] <... accept resumed> {sa_family=AF_INET, sin_port=htons(42100), sin_addr=inet_addr("10.125.164.70")}, [16]) = 26
[pid 37000] recvfrom(10,  <unfinished ...>
[pid 36840] write(19, "\1\0\0\0\0\0\0\0", 8) = 8
[pid 36999] <... nanosleep resumed> NULL) = 0
[pid 36840] accept(20,  <unfinished ...>
[pid 36999] nanosleep({0, 100000},  <unfinished ...>
[pid 36840] <... accept resumed> 0x7fbcd8000f40, 0x7fbce67b4e7c) = -1 EAGAIN (Resource temporarily unavailable)
[pid 36997] <... nanosleep resumed> NULL) = 0
[pid 36840] select(22, [20 21], NULL, NULL, {3600, 0} <unfinished ...>
[pid 36997] nanosleep({0, 100000},  <unfinished ...>
[pid 36999] <... nanosleep resumed> NULL) = 0
[pid 36999] nanosleep({0, 100000},  <unfinished ...>
[pid 36997] <... nanosleep resumed> NULL) = 0
[pid 36842] <... nanosleep resumed> NULL) = 0
[pid 36997] nanosleep({0, 100000},  <unfinished ...>
[pid 36842] nanosleep({0, 1000000},  <unfinished ...>
[pid 36999] <... nanosleep resumed> NULL) = 0
[pid 36999] nanosleep({0, 100000},  <unfinished ...>

**Comment by samyam** [comment]
Can anyone please help me debug this issue?

@alsrgv: Any further suggestions?

**Comment by alsrgv** [comment]
@samyam, could you try doing the same with `ssh 127.0.0.1` and `ssh localhost`.  If those don't help, can you run `mpirun` with `-mca plm_rsh_args "-vvvv"` and share the output?

**Comment by samyam** [comment]
I  can log into 127.0.0.1 and localhost without any promt for password. But its didn't help. I tried using the horovod docker, and that seems to work. Closing the issue for now.
