### ISSUE TITLE
Not working with tensorflow estimator API

### ISSUE THREAD

**Issue by yncxcw** [uber/horovod#565]
Environment: Python 2.7, Horovod 0.15.0, tensorflow 1.11, CUDA 9.2, Cudnn 7

It works fine if I only 
```
hooks=[hvd().BroadcastGlobalVariablesHook(0)]
estimator.train(input_fn=train_input_fn,
                        max_steps=train_steps,
                        hooks=hooks)
```

But not works when do eval and train likes this:
````
hooks=[hvd().BroadcastGlobalVariablesHook(0)]
for epoch in range(epochs):
    if hvd().rank() == 0:
        estimator.evaluate(validate_input_fn, steps=train_steps)
     estimator.train(input_fn=train_input_fn,
                                    max_steps=eval_steps,
                                    hooks=hooks)

````

Looks like the second epoch of train always fails to syn.

Is there anyway to work this out  ?

**Comment by alsrgv** [comment]
@yncxcw, what messages do you see after second epoch starts and fails to sync?

**Comment by yncxcw** [comment]
@alsrgv Please close this issue. It turns out a bug in my code. Thanks
