### ISSUE TITLE
Severely limited performance. Error: errno 38 

### ISSUE THREAD

**Issue by samyam** [uber/horovod#566]
I see almost no performance gain running tensorflow_mnist.py on 1 GPU vs 2 GPU using Horovod (logs for both runs attached) on a single node. I suspect, maybe there is some configuration issue.

I see the following message repeated hundreds of times when running on more that 1 GPU (please see the log) :

[gcrgpu1172:04092] Read -1, expected 102400, errno = 38
 
For some of my own models, I see this line repeated constantly through out the training. Can you provide suggestions on what might be the issue here? 

I am running horovod using the docker image built using the dockfile provided through this repo ( https://raw.githubusercontent.com/uber/horovod/master/Dockerfile) . My host OS is CoreOS which does not support nvidia-docker, so I am using the following command to run the image file

sudo docker run --privileged --cap-add=SYS_PTRACE --net=host --name=$container_name --device=/dev/nvidia0 --device=/dev/nvidia1 --device=/dev/nvidia2 --device=/dev/nvidia3 --device=/dev/nvidia4 --device=/dev/nvidia5 --device=/dev/nvidia6 --device=/dev/nvidia7 --device=/dev/nvidiactl --device=/dev/nvidia-uvm -v /var/drivers/nvidia/current:/usr/local/nvidia:ro -v /home/core/samyamr:/home/samyamr -v /tmp/hdfs-mount-dummy/:/hdfs/ -e PHILLY_CLUSTER=gcr -d -it horovod-python35:latest

[1-GPU-log-tensorflow-mnist.txt](https://github.com/uber/horovod/files/2485454/1-GPU-log-tensorflow-mnist.txt)
[2-GPU-log-tensorflow-mnist.txt](https://github.com/uber/horovod/files/2485455/2-GPU-log-tensorflow-mnist.txt)

**Comment by alsrgv** [comment]
@samyam, MNIST model is there just to learn the ropes, it's too small to see any performance gain.  Do you see any gains on your model training?

As for error, it is pretty harmless but should be removable by running in privileged mode.  I see that you already specify `--privileged` to docker, but it may get overwritten by `--cap-add=SYS_PTRACE`.  Can you try removing `--cap-add=SYS_PTRACE`?

**Comment by samyam** [comment]
I am not seeing any gains on my model either. On 1 GPU I see 2.7 batches/sec, while on 2 GPUs I see 2.8 batches/sec combined (1.45 batch/sec per GPU). On more than 4 GPUs the training crashes with these messages: The log is attached.

**It appears as if there is not enough space for /dev/shm/vader_segment.gcrgpu1172.b9000001.2 (the shared-memory backing
file). It is likely that your MPI job will now either abort or experience
performance degradation.

  Local host:  gcrgpu1172
  Space Requested: 4194312 B
  Space Available: 122880 B


OP_REQUIRES failed at mpi_ops.cc:424 : Aborted: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.** 

Do you know what is the shared-memory backing file, where is MPI trying to create the file? Is this why Horovod is crashing?

[4-GPU-log-deep-scan.txt](https://github.com/uber/horovod/files/2485536/4-GPU-log-deep-scan.txt)

**Comment by alsrgv** [comment]
@samyam, to resolve shared memory issue, can you try increasing docker shared memory limit, e.g. via `--shm-size=1g`?

After that, could you try capturing the timeline (https://github.com/uber/horovod/blob/master/docs/timeline.md), so we could look into communication pattern of your model?

**Comment by alsrgv** [comment]
I see that allgather is aggregating quite a significant chunk of sparse tensors, which makes me think they're not very sparse.

![image](https://user-images.githubusercontent.com/16640218/47108122-cfebc180-d1ff-11e8-9047-311dd4e6d1bf.png)

Do you think it's the same issue as #554?
