### ISSUE TITLE
how much training speed improvement should I expect from fp16 compression

### ISSUE THREAD

**Issue by scotthuang1989** [uber/horovod#578]
I just try fp16 compression with tensorflow， in terms of training speed, I got around 10% speed up. is this normal? what level of improvement should I expect?

**Comment by tgaddair** [comment]
Hey @scotthuang1989, it will depend greatly on where the bottleneck is in your network and model.  For simple models with slow networks, we expect fp16 to help a lot, but for fast networks and complex models, it might not help as much.

In our trials, we've generally seen around a 10% speedup (resnet50, 32 workers, 4 nodes), but we've also has users report increases as high as 17%.

**Comment by scotthuang1989** [comment]
ok, your result align with mine, I think I set a too high expectation on this feature..... BTW, I test it with a CudnnLSTM network which is optimized for GPU and memory usage.

**Comment by tgaddair** [comment]
Hey @Jeffwan, to clarify, there are two things we could be talking about when we say "fp16 compression": compression in the model, or compression during allreduce.  If you're running the `tf_cnn_benchmarks.py` script, then what they refer to is compression in the model.  For Horovod, I was referring to compression during allreduce, which you can enable with: 

```
opt = hvd.DistributedOptimizer(opt, compression=Compression.fp16)
```

Usually, compression in the model will give speedups like the kind you saw (2x).  Compression during the allreduce will depend on network latency, but improvements can be as high as 20%.

**Comment by Jeffwan** [comment]
Thanks for clarification, now I get it! This is super helpful. @tgaddair  Thanks!

**Comment by scotthuang1989** [comment]
@Jeffwan, where Can I find tf_cnn_benchmarks.py? I check repository of tensorflow and horovod, can't find it.

**Comment by tgaddair** [comment]
@scotthuang1989, you can find the TensorFlow benchmarks [here](https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks).  Horovod also provides its own TensorFlow benchmark using synthetic data [here](https://github.com/uber/horovod/blob/master/examples/tensorflow_synthetic_benchmark.py) if you prefer to use that.

**Comment by scotthuang1989** [comment]
thanks. these example made the problem very clear.
