### ISSUE TITLE
hvd.allreduce() is not reducing tensors

### ISSUE THREAD

**Issue by rohskopf** [uber/horovod#6]
In the Horovod source, in `mpi.ops.py` under the `_allreduce` function, it says:

```
   """An op which sums an input tensor over all the Horovod processes.
    The reduction operation is keyed by the name of the op. The tensor type and
    shape must be the same on all Horovod processes for a given name. The reduction
    will not start until all processes are ready to send and receive the tensor.
    Returns:
      A tensor of the same shape and type as `tensor`, summed across all
      processes.
    """
```

I made a minimum example to reproduce this description, by reducing a tensor called `const` on each process to a tensor called `reduced`:

```
import tensorflow as tf
import horovod.tensorflow as hvd

# Initialize Horovod
hvd.init()

config = tf.ConfigProto()

# Rank
rank = hvd.rank()

# Constant tensor to reduce
const = tf.constant([1.,2.])
reduced = hvd.allreduce(const)

# Monitored session
hooks = [hvd.BroadcastGlobalVariablesHook(0)]
sess = tf.train.MonitoredTrainingSession(config=config, hooks=hooks)

# I expect a summed tensor -> [2,4]
print("rank: %d" % (rank), sess.run(reduced))
```

Saving this in a file called `test.py`, I run with the following:
`mpirun -np 2 python allreduce.py`

The result is:
```
('rank: 0', array([ 1.,  2.], dtype=float32))
('rank: 1', array([ 1.,  2.], dtype=float32))
```

This is just returns the original tensor [1., 2.] that was supposed to be reduced. I expected the following:
```
('rank: 0', array([ 2.,  4.], dtype=float32))
('rank: 1', array([ 2.,  4.], dtype=float32))
```

Am I using this function incorrectly? I'm running on my laptop with 4 available processing units, and I'm using CPUs.

EDIT: Wow, I thought allreduce() returns the sum of tensors but it returns the average. It's working as expected now. Sorry for my foolishness.

**Comment by alsrgv** [comment]
@rohskopf no worries!  If you desire to get a sum, you can do:

```python
hvd.allreduce(const, average=False)
```
