### ISSUE TITLE
Do I run the validation metrics on just hvd.rank 0?

### ISSUE THREAD

**Issue by tonyreina** [uber/horovod#600]
I've got a Keras/Horovod script that runs well when I don't include the validation steps at the end of the epoch. However, when I try to do the validation metrics, it gives me:

```
Epoch 1/30
3/3 [==============================] - 561s 187s/step - loss: 1.5641 - dice_coef: 0.2316 - acc: 0.7010 - sensitivity: 0.8237 - specificity: 0.1463 - val_loss: 2.5166 - val_dice_coef: 0.0830 - val_acc: 0.0441 - val_sensitivity: 1.0000 - val_specificity: 0.0441

Epoch 00001: val_loss improved from inf to 2.51658, saving model to ./saved_model/3d_unet_brats2018.hdf5
Epoch 2/30
3/3 [==============================] - 552s 184s/step - loss: 1.2288 - dice_coef: 0.2952 - acc: 0.8842 - sensitivity: 0.9770 - specificity: 0.1875 - val_loss: 2.5166 - val_dice_coef: 0.0830 - val_acc: 0.0441 - val_sensitivity: 1.0000 - val_specificity: 0.0441
WARNING: One or more tensors were submitted to be reduced, gathered or broadcasted by subset of ranks and are waiting for remainder of ranks for more than 60 seconds. This may indicate that different ranks are trying to submit different tensors or that only subset of ranks is submitting tensors, which will cause deadlock.
Stalled ops:
MetricAverageCallback_10/HorovodAllreduce_MetricAverageCallback_10_lr_0 [missing ranks: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
MetricAverageCallback_3/HorovodAllreduce_MetricAverageCallback_3_sensitivity_0 [missing ranks: 0]
```

I'm using the Horovod callbacks:

```
hvd_callbacks = [
        hvd.callbacks.BroadcastGlobalVariablesCallback(0),
        hvd.callbacks.MetricAverageCallback(),
        hvd.callbacks.LearningRateWarmupCallback(warmup_epochs=5, verbose=1)
    ]
```

but only doing the checkpoint and TensorBoard callbacks on the hvd.rank 0.

Do I need to add the validation on all ranks or just rank 0?

For example, on rank 0:

```
model.fit_generator(training_generator,
                            steps_per_epoch=len(
                                trainList)//(args.bz*hvd.size()),
                            epochs=args.epochs, verbose=1,
                            validation_data=(imgs_test,msks_test),
                            callbacks=callbacks_list)

```
and on the other ranks:

```
model.fit_generator(training_generator,
                            steps_per_epoch=len(
                                trainList)//(args.bz*hvd.size()),
                            epochs=args.epochs, verbose=0,
                            callbacks=callbacks_list)
```

Thanks!

-Tony

**Comment by tgaddair** [comment]
Hey @tonyreina, the problem here appears to be that MetricAverageCallback is submitting tensors to be allreduced during validation, but since only rank 0 does validation, the process stalls waiting for the other ranks to submit tensors.

In general, we recommend running validation on all workers to simplify the code (see [this](https://github.com/uber/horovod/blob/master/examples/keras_mnist_advanced.py) example).

**Comment by tgaddair** [comment]
No problem.  I'll go ahead and close this issue for now.

**Comment by MrWangg1992** [comment]
> Hey @tonyreina, the problem here appears to be that MetricAverageCallback is submitting tensors to be allreduced during validation, but since only rank 0 does validation, the process stalls waiting for the other ranks to submit tensors.
> 
> In general, we recommend running validation on all workers to simplify the code (see [this](https://github.com/uber/horovod/blob/master/examples/keras_mnist_advanced.py) example).

Hi, the example link is 404, would you mind send another one again?
