### ISSUE TITLE
GPU Memory leak when XLA is activated

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [uber/horovod#602]
Hi everyone,

I am working using Horovod with various models using XLA. We have identified a problem when Horovod is used with XLA activated.

To keep it short, if you enable XLA, each Horovod process will allocate a little memory on each GPU.
When using DGX1 (8 GPUs) or even worse DGX2 (16 GPUs) this becomes a **huge** issue.

Each horovod thread takes between 250-500MB of VRAM on all GPUs + Network Memory (this time only on the correct GPU).

I have been able to reproduce this issue with:
- TF: 1.8 1.9 1.10 1.11 and 1.12rc2
- Horovod 0.12 0.13 0.14 and 0.15

Here is the command I use to launch the code on an 8 GPUs machine (DGX1):
```bash
#!/usr/bin/env bash

mpirun \
    -np 8 \
    -H localhost:8 \
    -bind-to none \
    -map-by slot \
    -x NCCL_DEBUG=INFO \
    -x LD_LIBRARY_PATH \
    -x PATH \
    -mca pml ob1 -mca btl ^openib \
    --allow-run-as-root \
    python horovod_issue.py
```

And the minimalistic python file `horovod_issue.py` to reproduce:

```python
import time

import tensorflow as tf
import horovod.tensorflow as hvd

if __name__ == '__main__':

    USE_XLA = True

    # Horovod: initialize Horovod.
    hvd.init()

    input_plh = tf.placeholder(tf.float32, [100, 32, 32, 3])

    net = tf.layers.conv2d(
        inputs=input_plh, filters=32, kernel_size=[5, 5], padding="same", activation=tf.nn.relu
    )

    def configure_tf_session(use_xla=False):

        config = tf.ConfigProto(
            allow_soft_placement=False,
            log_device_placement=False
        )

        config.gpu_options.allow_growth = True
        config.gpu_options.visible_device_list = str(hvd.local_rank())

        # Turns on XLA JIT compilation.
        if use_xla:
            jit_level = tf.OptimizerOptions.ON_1
            print("XLA is ACTIVATED")
        else:
            jit_level = tf.OptimizerOptions.OFF
            print("XLA is DEACTIVATED")

        config.graph_options.optimizer_options.global_jit_level = jit_level

        # config.intra_op_parallelism_threads = 1  # Setting this to `1` does not solve the issue
        # config.inter_op_parallelism_threads = 1  # Setting this to `1` does not solve the issue

        return config

    config = configure_tf_session(use_xla=USE_XLA)

    with tf.Session(config=config) as sess:

        sess.run(tf.global_variables_initializer())

        print("Sleeping for 30 sec ... Check `nvidia-smi` now ...")
        time.sleep(30)
```

During the sleep, launch `nvidia-smi` and look at the GPU processes section.

### Without XLA enabled - No Issue

![horovod_without_xla_issue](https://user-images.githubusercontent.com/10923599/47738248-6d70d780-dc7b-11e8-96cc-7493491b8671.png)

### With XLA enabled - 1 Process per Horovod Thread per GPU

![horovod_xla_issue](https://user-images.githubusercontent.com/10923599/47738276-7f527a80-dc7b-11e8-861d-d6370ea8d105.png)

*Disclaimer: The image has be truncated*

I hope this will be well enough explained.

If you need any more information, I'll be glad to help,

Thanks for the help

**Comment by DEKHTIARJonathan** [comment]
For some random reason, I find the symptom of issue #590 quite similar ... Even if #590 does not seem to involve XLA

**Comment by tgaddair** [comment]
Hey @DEKHTIARJonathan, thanks for raising this issue with such detailed repro steps!  I'll look into reproducing this in our environment.

**Comment by DEKHTIARJonathan** [comment]
@tgaddair any news ?

**Comment by tgaddair** [comment]
Hey @DEKHTIARJonathan, apologies I haven't gotten around to this yet.  I'll try to get around to this soon and get back to you.

**Comment by DEKHTIARJonathan** [comment]
@tgaddair any news ?

**Comment by tgaddair** [comment]
Hey @DEKHTIARJonathan, I believe I've been able to reproduce the memory leak, but no progress on fixing it on our end as of yet.  Sounds like this may be a TensorFlow issue according to your other issue.

**Comment by DEKHTIARJonathan** [comment]
Thanks for your answer @tgaddair. We actually have the same feeling at Nvidia. Tell me if we could be of any help. Not being able to use Horovod for multi gpu XLA is really negatively impacting all training at scale with Tensorflow...

I would be glad to talk with you about this if you happen to go at NeurIPS or by phone call if you want.

**Comment by DEKHTIARJonathan** [comment]
@tgaddair I'm closing this issue, TF merged yesterday a bug fix in XLA. I hope it will be cherrypicked for TF 1.13.
Thanks for your help.
