### ISSUE TITLE
Timeline file too big to load in chrome://tracing/

### ISSUE THREAD

**Issue by rashid0531** [uber/horovod#603]
Hi, 
The timeline file generated after training my model is around 3GB. Is there any way to set somewhere in Horovod framework to sample a few steps from training so that the size doesn't exceed a certain amount ?.

**Comment by tgaddair** [comment]
Hey @rashid0531, we don't currently support a way to sample events for the timeline, but you might look into slicing the timeline file as done [here](https://github.com/facebook/buck/blob/d609be052ddd49a746e185fadf6df08cc19af6d2/scripts/slice_trace.py).

**Comment by rashid0531** [comment]
@tgaddair Thank You for the direction.
