### ISSUE TITLE
Is there any way to intergrate horovod in tensorflow with Session instead of MonitoredTrainingSession?

### ISSUE THREAD

**Issue by haoransh** [uber/horovod#612]
I appreciate the provided tensorflow example (https://github.com/uber/horovod#usage) very much. But the usage of hooks and MonitoredTrainingSession seem not very flexible to me. 
What the codes should be if I want to use tf.Session() to create the session? The MonitoredTrainingSession seem not very flexible to me if I want to do evaluation periodically and save the model according to the evaluation performance when training. Could someone be so kind to tell me?

**Comment by UditGupta10** [comment]
The tensorflow word2vec example doesn't use MonitoredTrainingSession. So, You may refer to that. Also, in the usage section linked by you, its mentioned how to use without MonitoredTrainingSession.
