### ISSUE TITLE
[q] mpirun crash 

### ISSUE THREAD

**Issue by hpjeonGIT** [uber/horovod#62]
Hi,

We're testing HOROVOD on centos7.3, nccl2, cuda/8, cudnn6.0 but it keeps crashing. We tested openmpi 2.1.2, 3.0.0, and mvapich2.2. but all crashes with same error message shown below. 
NCCL2 has been confirmed working through nccl-tests. 

Could you comment about the issues? Other details are shown below.

Best regards,

Byoungseon

Install command: HOROVOD_NCCL_HOME=$NCCL_HOME HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI pip3 install --no-cache-dir horovod
Run command:  mpirun -n 2 python3 ./keras_mnist.py

Error message shown below:

2017-10-30 15:46:26.208991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:13:00.0, compute capability: 6.0)
[ava02:21329:1] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x0000000000068d1c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/util/debug/debug.c:641
 3 0x000000000006926c mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/util/debug/debug.c:616
 4 0x0000000000035250 killpg()  ??:0
 5 0x000000000014b9cc __memcpy_ssse3_back()  :0
 6 0x000000000038ad0e mv2_smp_fast_write_contig()  ??:0
 7 0x000000000036ac7f MPIDI_CH3_EagerContigShortSend()  ??:0
 8 0x000000000037518f MPID_Send()  ??:0
 9 0x000000000030dbaa MPIC_Send()  ??:0
10 0x000000000007c372 MPIR_Bcast_binomial.isra.1()  bcast.c:0
11 0x000000000007cd15 MPIR_Bcast_intra()  ??:0
12 0x00000000000e738a MPIR_Bcast_index_tuned_intra_MV2()  ??:0
13 0x00000000000e4eaf MPIR_Bcast_MV2()  ??:0
14 0x000000000007cfe8 MPIR_Bcast_intra()  ??:0
15 0x00000000000e738a MPIR_Bcast_index_tuned_intra_MV2()  ??:0
16 0x00000000000e4eaf MPIR_Bcast_MV2()  ??:0
17 0x000000000007d89b MPIR_Bcast_impl()  ??:0
18 0x000000000007dea9 MPI_Bcast()  ??:0
19 0x000000000001f1be _ZN7horovod10tensorflow12_GLOBAL__N_116PerformOperationERSt13unordered_mapISsNS1_16TensorTableEntryESt4hashISsESt8equal_toISsESaISt4pairIKSsS3_EEENS0_11MPIResponseE()  /tmp/pip-build-7bvx75z5/horovod/horovod/tensorflow/mpi_ops.cc:1131
20 0x0000000000021391 _ZN7horovod10tensorflow12_GLOBAL__N_120BackgroundThreadLoopERNS1_18HorovodGlobalStateE()  /tmp/pip-build-7bvx75z5/horovod/horovod/tensorflow/mpi_ops.cc:1431
21 0x0000000000021391 ~vector()  /usr/include/c++/4.8.2/bits/stl_vector.h:416
22 0x0000000000021391 ~MPIResponse()  /tmp/pip-build-7bvx75z5/horovod/horovod/tensorflow/mpi_message.h:93
23 0x0000000000021391 _ZN7horovod10tensorflow12_GLOBAL__N_120BackgroundThreadLoopERNS1_18HorovodGlobalStateE()  /tmp/pip-build-7bvx75z5/horovod/horovod/tensorflow/mpi_ops.cc:1431
24 0x00000000000b5230 _ZNSt11this_thread11__sleep_forENSt6chrono8durationIlSt5ratioILl1ELl1EEEENS1_IlS2_ILl1ELl1000000000EEEE()  ??:0
25 0x0000000000007dc5 start_thread()  pthread_create.c:0
26 0x00000000000f776d __clone()  ??:0

**Comment by alsrgv** [comment]
@hpjeonGIT, we've just updated GPU instructions [here](https://github.com/uber/horovod/blob/master/docs/gpus.md). In particular, you should only use `HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI` if you have RDMA and GPUDirect, you've installed `nv_peer_mem` driver and compiled MPI with CUDA support.

**Comment by hpjeonGIT** [comment]
Hi,

We double-checked the RDMA (from udaddy and rmda_server) and GPUDirect work. nv_peer_mem i s loaded (Centos 7.3). Also Cuda 8.0 enabled openmp 3.0.0 was used and we tested 0.9.11 but still same error comes. Could there be anything that we can check for any missing components or steps? Any comments are appreciated.

Best regards,

Byoungseon

PS.
$ service nv_peer_mem status
nv_peer_mem module is loaded.

- Install command: HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI  python3 setup.py install
-Running command:  mpirun -n 2 python3 keras_mnist.py 
$  HOROVOD_GPU_ALLGATHER=MPI   mpirun -n 2 python3 keras_mnist.py 
[1509482086.183172] [ava02:26027:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2190.00
[1509482086.199974] [ava02:26028:0]         sys.c:744  MXM  WARN  Conflicting CPU frequencies detected, using: 2190.00
[1509482086.230456] [ava02:26027:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
[1509482086.240480] [ava02:26028:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
[1509482086.247617] [ava02:26027:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
[1509482086.257407] [ava02:26028:0]         mxm.c:196  MXM  WARN  The 'ulimit -s' on the system is set to 'unlimited'. This may have negative performance implications. Please set the stack size to the default value (10240) 
2017-10-31 16:34:50.688260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:13:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2017-10-31 16:34:50.688324: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 1, name: Tesla P100-PCIE-16GB, pci bus id: 0000:13:00.0, compute capability: 6.0)
2017-10-31 16:34:50.689365: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285
pciBusID: 0000:0d:00.0
totalMemory: 15.89GiB freeMemory: 15.60GiB
2017-10-31 16:34:50.689400: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:0d:00.0, compute capability: 6.0)
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
[ava02:26027:0] Caught signal 11 (Segmentation fault)
==== backtrace ====
 2 0x0000000000068d1c mxm_handle_error()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/util/debug/debug.c:641
 3 0x000000000006926c mxm_error_signal_handler()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/util/debug/debug.c:616
 4 0x0000000000035250 killpg()  ??:0
 5 0x000000000014b9cc __memcpy_ssse3_back()  :0
 6 0x000000000005b383 mxm_proto_set_data_buf_inline()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/proto/proto_ops.c:271
 7 0x0000000000070932 mxm_shm_channel_send()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/tl/shm/shm_channel.c:306
 8 0x00000000000627c0 mxm_proto_conn_send_op()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/proto/proto_send.c:47
 9 0x00000000000627c0 mxm_req_send()  /var/tmp/OFED_topdir/BUILD/mxm-3.6.3102/src/mxm/proto/proto_send.c:469
10 0x0000000000004bec mca_pml_yalla_isend()  /usr/nic/src/mpi/openmpi/ompi_300/openmpi-3.0.0/ompi/mca/pml/yalla/pml_yalla.c:488
11 0x000000000007a86c ompi_coll_base_bcast_intra_generic()  /usr/nic/src/mpi/openmpi/ompi_300/openmpi-3.0.0/ompi/mca/coll/base/coll_base_bcast.c:88
12 0x000000000007ae77 ompi_coll_base_bcast_intra_binomial()  /usr/nic/src/mpi/openmpi/ompi_300/openmpi-3.0.0/ompi/mca/coll/base/coll_base_bcast.c:335
13 0x00000000000048cc ompi_coll_tuned_bcast_intra_dec_fixed()  /usr/nic/src/mpi/openmpi/ompi_300/openmpi-3.0.0/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:258
14 0x000000000005b151 PMPI_Bcast()  /usr/nic/src/mpi/openmpi/ompi_300/openmpi-3.0.0/ompi/mpi/c/profile/pbcast.c:111
15 0x0000000000019283 _ZN7horovod10tensorflow12_GLOBAL__N_116PerformOperationERSt13unordered_mapISsNS1_16TensorTableEntryESt4hashISsESt8equal_toISsESaISt4pairIKSsS3_EEENS0_11MPIResponseE()  /usr/nic/src/apps/horovod-0.9.11/horovod/tensorflow/mpi_ops.cc:1131
16 0x000000000001c54b _ZN7horovod10tensorflow12_GLOBAL__N_120BackgroundThreadLoopERNS1_18HorovodGlobalStateE()  /usr/nic/src/apps/horovod-0.9.11/horovod/tensorflow/mpi_ops.cc:1431
17 0x00000000000b5230 _ZNSt11this_thread11__sleep_forENSt6chrono8durationIlSt5ratioILl1ELl1EEEENS1_IlS2_ILl1ELl1000000000EEEE()  ??:0
18 0x0000000000007dc5 start_thread()  pthread_create.c:0
19 0x00000000000f776d __clone()  ??:0
===================
-------------------------------------------------------

**Comment by alsrgv** [comment]
Sounds like MXM / Yalla was not compiled with CUDA support or does not have it.  @bureddy, @jladd-mlnx - do you have any pointers for ^?

**Comment by bureddy** [comment]
@alsrgv @hpjeonGIT Currently MXM/Yalla do not have support for GPU transfers.  The GPU support is planned in future Mellanox UCX releases.

Currently,  OMPI supports GPU transfers only with the native IB transport (-mca pml ob1) when it compiled with GPU support.

**Comment by alsrgv** [comment]
@hpjeonGIT, I also noticed that your installation command doesn't have `HOROVOD_GPU_ALLREDUCE`.  That's the most important component - as *allreduce* gets much more used than *allgather* and *broadcast* (see [Concepts](https://github.com/uber/horovod/blob/master/docs/concepts.md)), and you will get the best performance if you install NCCL 2 ([guide](https://github.com/uber/horovod/blob/master/docs/gpus.md#advanced-have-gpus-and-networking-with-rdma-and-gpudirect)) and run setup with:

```
$ HOROVOD_GPU_ALLREDUCE=NCCL HOROVOD_GPU_ALLGATHER=MPI HOROVOD_GPU_BROADCAST=MPI python3 setup.py install
```

**Comment by hpjeonGIT** [comment]
Thanks for many advices.
I tried the recompilation but it yielded same errors.
However, I noticed that the error message is yielded at line 77: K.get_session().run(hvd.broadcast_global_variables(0)). I replaced it as hvd.BroadcastGlobalVariablesHook(0), as shown in HOROVOD guide, and it works (!?).
Therefore, I would like to ask consequential questions:

1) such replacement wouldn't affect the calculation?
2) 1gpu takes 67 sec while 4gpus run takes 50sec. Not much speed-up because mnist is small data set? Will there be any benchmark using large data set?

I appreciate your prompt helps, and any comments are appreciated.

Best regards,

Byoungseon

**Comment by hpjeonGIT** [comment]
Hi alsrgv and bureddy,

Thanks for the great help. After reverting the code, 
"mpirun  -mca pml ob1  -n 4 python3 keras_mnist.py" runs good.
Even "mpirun  -mca pml ob1   -mca btl_openib_receive_queues P,128,32:P,2048,32:P,
12288,32:P,131072,32   -n 4 python3 keras_mnist.py" shows 10-20% faster results, even with mnist set.

Just when I tried multiple nodes (2 or 3 nodes, total 8 or 12 GPUs), they hang at K.get_session().run(hvd.broadcast_global_variables(0)). No error message. Just hangs.  nccl-test is confirmed to work on multiple nodes/GPUs using the same openmpi. 
I tried:
mpirun  -mca pml ob1 -np 8 -x LD_LIBRARY_PATH -H server1:4,server2:4 python3  keras_mnist.py
or
mpirun  -mca pml ob1 -np 8 -x LD_LIBRARY_PATH -machinefile $PBS_NODEFILE python3  keras_mnist.py
but both of cases just hang or stall. I monitored python3's are loaded in the 4 GPUs of each node but they seem to be stalled.

I will update the results if I find a solution. Any comments are appreciated.

Best regards,

Byoungseon

**Comment by alsrgv** [comment]
@hpjeonGIT, can you try:
```
$ mpirun -mca pml ob1 -mca btl_openib_receive_queues P,128,32:P,2048,32:P,
12288,32:P,131072,32 -np 8 -x LD_LIBRARY_PATH -H server1:4,server2:4 python3 keras_mnist.py
```

I had seen broadcast get stuck before with wrong queue settings.  If that doesn't work, can you try to disable Open IB for MPI:
```
$ mpirun -mca btl ^openib -np 8 -x LD_LIBRARY_PATH -H server1:4,server2:4 python3 keras_mnist.py
```

**Comment by hpjeonGIT** [comment]
Hi, we installed horovod 0.10.2, and now  it works good for both of intra/inter nodes. Even without -mca pml ob1, it works good. Thanks for the support and the update.

Best regards,

Byoungseon

**Comment by ibaned** [comment]
@bureddy are there any plans for GPU support in MXM/Yalla ?

**Comment by bureddy** [comment]
@ibaned no plan for GPU support in MXM/Yalla because it is going to deprecated soon in favour of Mellanox's  UCX (https://github.com/openucx/ucx).   We are working on GPU support in UCX.
