### ISSUE TITLE
Installation issue with miniconda

### ISSUE THREAD

**Issue by mcuma** [uber/horovod#620]
This is probably a naive question but I can't figure it out, not knowing the internals of pip well.

I have miniconda installed, which lives in $HOME/software/pkg/miniconda3

pip install horovod is putting it to $HOME/python/3.6/site-packages, rather than $HOME/software/pkg/miniconda3/python3.6/site-packages, even if I set --target=$HOME/software/pkg/miniconda3/python3.6/site-packages. In fact, if I set the --target, horovod ends up being installed in $HOME/software/pkg/miniconda3/python3.6/site-packages/$HOME/python/3.6/site-packages

Any thought on this would be appreciated.

Thanks

**Comment by alsrgv** [comment]
@mcuma, I don't believe we're doing anything special, so it must be pip issue.  Sanity check - are you doing pip install while your conda environment is activated?

**Comment by mcuma** [comment]
Thanks for the quick reply. Yes, I am in the conda environment. I will fiddle with the pip to try to understand better what it's doing.
