### ISSUE TITLE
Running Horovod from within a Jupyter Notebook

### ISSUE THREAD

**Issue by EhsanM4t1qbit** [uber/horovod#622]
Hi, I was wondering if it is possible to use Horovod inside a Jupyter notebook? In particular with a Keras model?
Thanks

**Comment by alsrgv** [comment]
@EhsanM4t1qbit, yes.  There are two ways.  One way is to save Jupyter Notebook, run `! nbconvert` in a cell, and run `! mpirun`.  It's a bit cumbersome.

Another way is to use PySpark and upcoming [PySpark integration](https://github.com/uber/horovod/pull/606).  If you use PySpark way, you can define your training as a function in the Jupyter notebook, and then execute that function via `horovod.spark.run(fn)`.

**Comment by EhsanM4t1qbit** [comment]
Thanks for the reply. Can you please elaborate the first point ? I should use `nbconvert` to convert the notebook into some other file? What type? And then call `mpirun` from inside the same notebook with the name of the converted file?

**Comment by alsrgv** [comment]
E.g. [this example](https://github.com/jupyter/nbconvert#example-convert-a-notebook-to-html), but instead of `html` specify `py`.

**Comment by EhsanM4t1qbit** [comment]
That's a nice trick, thanks.

**Comment by denfromufa** [comment]
@alsrgv here is an approach from national labs using ipyparallel, which is the "built-in" way to run HPC cluster jobs interactively from jupyter notebooks:

https://drive.google.com/file/d/1-OFjrk1q3L1d3uakr2xkozrPn2c2VZpZ/view
https://indico.cern.ch/event/587955/contributions/2937509/attachments/1683970/2741752/CHEP2018_HEPGANs_Farrell.pdf

**Comment by denfromufa** [comment]
https://github.com/sparticlesteve/cori-intml-examples
