### ISSUE TITLE
why operations.cc comment out NCCL cleanup code?

### ISSUE THREAD

**Issue by LiweiPeng** [uber/horovod#628]
In horovod code, operations.cc:1635, it commented out the NCCL clean up code. What's the design logic for this?
```
  // TODO: init.cu:645 WARN Cuda failure 'driver shutting down'
  //#if HAVE_NCCL
  //  for (auto it = horovod_global.streams.begin();
  //       it != horovod_global.streams.end(); it++) {
  //    cudaStreamSynchronize(it->second);
  //  }
  //  for (auto it = horovod_global.nccl_comms.begin();
  //       it != horovod_global.nccl_comms.end(); it++) {
  //    ncclCommDestroy(it->second);
  //  }
  //#endif
```

**Comment by alsrgv** [comment]
@LiweiPeng, if we enable it, we see the warning `init.cu:645 WARN Cuda failure 'driver shutting down'`.  The reason for the warning is that in most case this code executes by finalization handler, and by that time CUDA has already terminated and released all the resources.

Do you have use cases where it's harmful?

**Comment by LiweiPeng** [comment]
Thanks @alsrgv . This is not harmful.

We are developing a low level communication library. We'd like to integrate our library with Horovod. So we'd like to follow the similar way that Horovod handles CUDA cleanup.
