### ISSUE TITLE
Running Horovod on 2 Nodes

### ISSUE THREAD

**Issue by salemmohammed** [uber/horovod#633]
Hi all,

I am having two AWS machines with Ubuntu 16.04 Ubuntu. I installed OpenMPI 4.0. I run the standard Tensorflow example with MNIST dataset. 

The output that I got from running the following command:

mpirun -np 2 \
    -H ip-address:1,ip-address:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python3 Horovod_Tensorflow.py

The output is the following:

[ip-000-00-00-000:25856] Warning: could not find environment variable "LD_LIBRARY_PATH"
the execution is hanging.

I changed the command for:
mpirun -np 1 \
    -H localhost:1 \
    -bind-to none -map-by slot \
    -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH \
    -mca pml ob1 -mca btl ^openib \
    python3 Horovod_Tensorflow.py

It's running with some warning. 

Could anybody point me any help?

**Comment by salemmohammed** [comment]
@tgaddair

**Comment by salemmohammed** [comment]
@UditGupta10

**Comment by salemmohammed** [comment]
I changed the command line but it's still the same problem.
mpirun -np 2 \
    -H ip:1,ip:1 \
    -bind-to none -map-by slot \
    -mca btl ^openib \
    python3 Horovod_Tensorflow.py

The execution is hanging without any response.

**Comment by alsrgv** [comment]
@salemmohammed, can you check if this guide helps you - https://github.com/uber/horovod/blob/master/docs/running.md#hangs-due-to-ssh-issues?

**Comment by salemmohammed** [comment]
@alsrgv 

It pointed me in the right direction.
First, the problem was not related to Horovod but to ssh authentication. 
These are the steps that I follow to overcome my problem.
1- eval `ssh-agent -s`
2- ssh-add <pem-key>
3- Set the StrictHostKeyChecking option to no
When I execute the mpirun .... it worked.


Thank you for your help.

**Comment by wyf0414** [comment]
Hello, I have a question similar to yours.
I encountered this issue while replicating bevfusion.
I have configured the environment and dataset according to the readme of bevfusion.
Could you tell me how you solved it?
Thanks very much!

Input:
torchpack dist-run -np 1 python tools/train.py configs/nuscenes/det/transfusion/secfpn/camera+lidar/swint_v0p075/convfuser.yaml --model.encoders.camera.backbone.init_cfg.checkpoint pretrained/swint-nuimages-pretrained.pth --load_from pretrained/lidar-only-det.pth

error:
Warning: could not find environment variable "-x"
mpirun was unable to find the specified executable file, and therefore
did not launch the job. This error was first reported for process
rank 0; it may have occurred for other processes as well.

NOTE: A common cause for this error is misspelling a mpirun command
line parameter option (remember that mpirun interprets the first
unrecognized command line token as the executable).

Node: autodl-container-e7f311abe8-00947946
Executable: AgentHost

![image](https://github.com/horovod/horovod/assets/137131028/9553718b-5a7a-4f7c-b8aa-ee686e078804)
