### ISSUE TITLE
can not `mpirun -H node1:2` while `mpirun -H node1,node2` is OK

### ISSUE THREAD

**Issue by wuminbin** [uber/horovod#635]
I am runing `examples/tensorflow_word2vec.py`, when on node1, I type `mpirun -H node1:2 ...` but it seems to block at [`broadcast_global_variables` method](https://github.com/uber/horovod/blob/9eaba164f99479d369477f6b50c74efbec2ffa80/examples/tensorflow_word2vec.py#L199), while `mpirun -H node1,node2` is OK, I want to know why. Both node can pass the [nccl test](https://github.com/NVIDIA/nccl) by typing `./build/all_reduce_perf -b 8 -e 256M -f 2 -g 2`

**Comment by wuminbin** [comment]
it is called by `bcast.run()` at line 214.

**Comment by wuminbin** [comment]
I use open-mpi-3.1.3 and the full commands are:
`mpirun -H gpu-25,gpu-25 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib ./test_horovod_mpi.py  # it hangs`
`mpirun -H gpu-25,gpu-26 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 -mca btl ^openib ./test_horovod_mpi.py  # this one is OK`
File `test_horovod_mpi.py` is the same as example except first line configuring the python interpreter.

**Comment by alsrgv** [comment]
@wuminbin, can you try specifying `-np 2` in both of those commands?

**Comment by alsrgv** [comment]
@wuminbin, according to #638 it may be an issue with Open MPI 3.1.3.  Could you try Open MPI 4.0.0 or 3.0.0?

**Comment by wuminbin** [comment]
I find out why. When I install OMPI, I'm using gcc-4.85, but later I'm using gcc-7.1.0, I reinstall and it runs well. I compare the two header file  /usr/local/include/mpi.h and in Line 51 I found `OPAL_BUILD_PLATFORM_COMPILER_VERSION` differs.
