### ISSUE TITLE
tensorflow allows only one process per node

### ISSUE THREAD

**Issue by tsmolcic** [uber/horovod#639]
Hi!

I have three nodes with 4 GPUs per node.  

System: centos7, cuda 10, nccl 2.3.5, horovod 0.15.1, tensorflow 1.12.0rc0 (built from source)

Whenever I try to run more than one TensorFlow process per single node, something like:

`mpirun -np 4 -H server1:2,server2:2 -bind-to none -map-by slot -x LD_LIBRARY_PATH -x PATH  python my_script.py`

I get

`unable to create StreamExecutor for CUDA:0: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_INVALID_DEVICE: invalid device ordinal`

repeated for every GPU on both nodes.

When I run:

`mpirun -np 2 -H server1:1,server2:1 -bind-to none --map-by slot -x LD_LIBRARY_PATH -x PATH  python my_script.py`

the job finishes without errors, however nvidia-smi always show that all GPUs on both nodes are taken by TF:

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    277256      C   python3.5                                    803MiB |
|    1    277256      C   python3.5                                    407MiB |
|    2    277256      C   python3.5                                    407MiB |
|    3    277256      C   python3.5                                    407MiB |
+-----------------------------------------------------------------------------+
```

As far as I can see, a single TF process takes all GPUs, and since they are set to exclusive process compute mode, the thing breaks trying to create the remaining processes... I'm using tensorflow examples from horovod git.

I know I can limit TF to use specific GPUs via CUDA_VISIBLE_DEVICES env variable, but it gets pretty messy real fast, as it's a shared system with multiple users, apps etc.

I realize this isn't necessarily a horovod issue, but this seemed like a good place to try and get at least some pointers...

Thanks!

**Comment by alsrgv** [comment]
@tschmidt3, does your training code has [this line](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist.py#L104) to pin GPUs to be used by each rank?  With that code, you should not need to set `CUDA_VISIBLE_DEVICES`.

**Comment by fxrcode** [comment]
Yes. I just used the given tests keras_mnist.py.
We are facing this issue too, might due to upgrade of openmpi 3.1.2 in latest horovod dockerfile? Cuz it works before.

**Comment by alsrgv** [comment]
@fxrcode, how does output of `nvidia-smi` look like in your case?

**Comment by fxrcode** [comment]
> @fxrcode, how does output of `nvidia-smi` look like in your case?

It looks alright. But it shows mpirun get into 1 container more times than I expect which leads to local_rank higher than it should be.

>  * Starting OpenBSD Secure Shell server sshd
   ...done.
Docker is ready on: [192.168.0.251].
Host novustar-6316 connected.
The peers are ready: novustar-6316
Tue Nov 20 22:12:01 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   60C    P0    61W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Host novustar-6317 connected.
The peers are ready: novustar-6317
Tue Nov 20 22:12:02 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   60C    P0    61W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Host novustar-6318 connected.
The peers are ready: novustar-6318
Tue Nov 20 22:12:03 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   60C    P0    61W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Host novustar-6319 connected.
The peers are ready: novustar-6319
Tue Nov 20 22:12:05 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.66       Driver Version: 410.66       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   60C    P0    61W / 250W |     10MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


Horovod IP: 192.168.0.251 ,Port: 6316 , size, 4 rank, 0 local rank, 0 
Horovod IP: 192.168.0.251 ,Port: 6316 , size, 4 rank, 1 local rank, 1   // This is the error part.
Horovod IP: 192.168.0.252 ,Port: 6318 , size, 4 rank, 2 local rank, 0 
Horovod IP: 192.168.0.252 ,Port: 6319 , size, 4 rank, 3 local rank, 0 


Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz
Downloading data from https://s3.amazonaws.com/img-datasets/mnist.npz

**Comment by alsrgv** [comment]
@fxrcode, ok - it may be a separate issue.  What's your `mpirun` command?

**Comment by tsmolcic** [comment]
> 
> 
> @tschmidt3, does your training code has [this line](https://github.com/uber/horovod/blob/master/examples/tensorflow_mnist.py#L104) to pin GPUs to be used by each rank? With that code, you should not need to set `CUDA_VISIBLE_DEVICES`.

I don't know if this was meant for me, similar usernames :)

Yes, the code I'm running, has that line, it's that exact script I'm trying to run. Could this be something similar to [this](https://github.com/keras-team/keras/pull/8377#issuecomment-341905128)?

**Comment by alsrgv** [comment]
@tsmolcic, sorry - autocomplete typo :-).  I tried TensorFlow 1.2.0 (official release) yesterday and it worked fine with TensorFlow MNIST example.  Are you using TensorFlow or Keras?  Can you try 1.2.0?

**Comment by tsmolcic** [comment]
@alsrgv, I'll try and let you know. However, I suspect I'll get a request by a user for a newer version of TensorFlow in a matter of hours :) 
If it's not too much trouble, can you try running 1.12 or some other newer version of TensorFlow so we can rule out if it's my system related or TensorFlow/Horovod issue?

**Comment by alsrgv** [comment]
Sorry - I meant 1.12.0.  Updated.

**Comment by tsmolcic** [comment]
@alsrgv it works with 1.12. However, with anything except `-np 1`, the tensorflow_mnist example now hangs after:

```
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into ./checkpoints/model.ckpt.
```

nvidia-smi shows that the process is running on a GPU, but GPU load stays 0%.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:1A:00.0 Off |                    0 |
| N/A   39C    P0    53W / 300W |   1338MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:1C:00.0 Off |                    0 |
| N/A   34C    P0    39W / 300W |     11MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  Off  | 00000000:1D:00.0 Off |                    0 |
| N/A   33C    P0    38W / 300W |     11MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:1E:00.0 Off |                    0 |
| N/A   37C    P0    40W / 300W |     11MiB / 16130MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     16050      C   python3.5                                   1327MiB |
+-----------------------------------------------------------------------------+
```

Furthermore, on a maybe unrelated issue, if there is a process running on say GPU with id0, and I try to run another process that wants 1 GPU, it doesn't work, even though there are 3 available GPUs. All GPUs are in exclusive process compute mode.

**Comment by alsrgv** [comment]
@tsmolcic, looks like your multi-node issue is related to the network.  Can you share the output of `ifconfig` and `ibv_devinfo -v`?

With regards to GPU usage, there's no logic to automatically find a free GPU.  You could conceivably program logic like that and use it when you're pinning GPU to be used by TensorFlow.

**Comment by tsmolcic** [comment]
I've been testing things further, decided to include the third node I have. Multiple processes work on that node, but when trying to run on nodes 2 and 3 together, I get this [error output](https://gist.github.com/tsmolcic/77f59344cb4b175278104353efbb2b31).

**Comment by tsmolcic** [comment]
This last problem made me look if all nodes have everything the same, seems like I had different nccl version on one of them. Everything seems to work right now. 

Does this look like a good NCCL_DEBUG log, after
`mpirun -np 3 -H c4140-01:1,c4140-02:1,c4140-03:1 -x LD_LIBRARY_PATH -x NCCL_DEBUG=INFO python3.5 tensorflow_mnist.py`

```
c4140-01:147406:148900 [0] NCCL INFO NET : Using interface ib0:192.168.1.35<0>
c4140-01:147406:148900 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
c4140-01:147406:148900 [0] NCCL INFO NET/IB: [0] mlx5_0:1/IB
c4140-01:147406:148900 [0] NCCL INFO Using internal Network IB
c4140-01:147406:148900 [0] NCCL INFO NET : Using interface ib0:192.168.1.35<0>
c4140-01:147406:148900 [0] NCCL INFO NET/Socket : 1 interfaces found
NCCL version 2.3.5+cuda10.0
c4140-01:147406:148900 [0] NCCL INFO rank 0 nranks 3
c4140-02:226881:226933 [0] NCCL INFO NET : Using interface ib0:192.168.1.36<0>
c4140-02:226881:226933 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
c4140-03:5345:5397 [0] NCCL INFO NET : Using interface ib0:192.168.1.37<0>
c4140-03:5345:5397 [0] NCCL INFO NET/IB : Using interface ib0 for sideband communication
c4140-02:226881:226933 [0] NCCL INFO NET/IB: [0] mlx5_0:1/IB
c4140-02:226881:226933 [0] NCCL INFO Using internal Network IB
c4140-02:226881:226933 [0] NCCL INFO rank 1 nranks 3
c4140-03:5345:5397 [0] NCCL INFO NET/IB: [0] mlx5_0:1/IB
c4140-03:5345:5397 [0] NCCL INFO Using internal Network IB
c4140-03:5345:5397 [0] NCCL INFO rank 2 nranks 3
c4140-02:226881:226933 [0] NCCL INFO comm 0x7fbb10e9b8e0 rank 1 nranks 3
c4140-02:226881:226933 [0] NCCL INFO NET : Using interface ib0:192.168.1.36<0>
c4140-02:226881:226933 [0] NCCL INFO NET/Socket : 1 interfaces found
c4140-03:5345:5397 [0] NCCL INFO comm 0x7f1208eb8c20 rank 2 nranks 3
c4140-02:226881:226933 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx5_0/1(SOC)
c4140-03:5345:5397 [0] NCCL INFO NET : Using interface ib0:192.168.1.37<0>
c4140-03:5345:5397 [0] NCCL INFO NET/Socket : 1 interfaces found
c4140-03:5345:5397 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx5_0/1(SOC)
c4140-01:147406:148900 [0] NCCL INFO comm 0x7f0514e4de80 rank 0 nranks 3
c4140-01:147406:148900 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx5_0/1(SOC)
c4140-01:147406:148900 [0] NCCL INFO Using 256 threads
c4140-01:147406:148900 [0] NCCL INFO Min Comp Cap 7
c4140-01:147406:148900 [0] NCCL INFO Ring 00 :    0   1   2
c4140-03:5345:5397 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx5_0 (not supported by GPU)
c4140-02:226881:226933 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx5_0 (not supported by GPU)
c4140-01:147406:148900 [0] NCCL INFO NET/IB : GPU Direct RDMA Disabled for GPU 0 / HCA mlx5_0 (not supported by GPU)
c4140-03:5345:5397 [0] NCCL INFO Ring 00 : 1 -> 2 via NET/IB/0
c4140-02:226881:226933 [0] NCCL INFO Ring 00 : 0 -> 1 via NET/IB/0
c4140-01:147406:148900 [0] NCCL INFO Ring 00 : 2 -> 0 via NET/IB/0
c4140-01:147406:148900 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 10367 mtu 5 LID 228
c4140-03:5345:5397 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 422 mtu 5 LID 230
c4140-02:226881:226933 [0] NCCL INFO NET/IB: Dev 0 Port 1 qpn 1926 mtu 5 LID 229
c4140-01:147406:148900 [0] NCCL INFO Launch mode Parallel
```
