### ISSUE TITLE
No traffic is being captured while running TF benchmarks.

### ISSUE THREAD

**Issue by taehyunkim1527** [uber/horovod#649]
I'm running TensorFlow benchmarks using two machines with 4 GPUs each.
I want to measure network traffic btw two machines. But I could see some traffic only at the very first moment and after the training starts, I couldn't capture any traffic.
I captured the traffic using `ethtool` and I verified that this works by running TensorFlow benchmarks with `distributed_replicated` mode.

And I executed Tensorflow benchmarks code with the following command.

    mpirun -np 8 \
    --allow-run-as-root \
    -H 10.0.1.1:4,10.0.1.2:4,\
    -bind-to none -map-by slot \
    -mca btl ^openib \
    -mca btl_tcp_if_exclude docker0,lo,eno1 \
    -x NCCL_SOCKET_IFNAME=ens \
    -x NCCL_DEBUG=INFO \
    -x LD_LIBRARY_PATH \
    -x PATH \
    -x HOROVOD_MPI_THREADS_DISABLE=1 \
    -mca plm_rsh_args "-p 12345" \
    python3 tf_cnn_benchmarks.py \
    --data_format=NCHW \
    --model=resnet50 \
    --batch_size=32 \
    --optimizer=momentum \
    --weight_decay=1e-4 \
    --num_epochs=2 \
    --init_learning_rate=0.045 \
    --num_epochs_per_decay=2 \
    --learning_rate_decay_factor=0.94 \
    --learning_rate_scale_factor=1. \
    --num_gpus=1 \
    --allow_growth=True \
    --train_dir=./ \
    --variable_update=horovod

**Comment by taehyunkim1527** [comment]
The issue is solved.

**Comment by tgaddair** [comment]
Closing for now.  @taehyunkim1527, could you share how you solved this for anyone with the same issue?

**Comment by linkeal** [comment]
@taehyunkim1527: Could you please tell us how you solved the issue? I am facing the same problem and don't know how to solve it.

**Comment by taehyunkim1527** [comment]
Frankly, at first I was just watching rx_bytes/tx_bytes of ethtool and I couldn't find any changes.
However, the traffic of Horovod all_reduce is only captured at rx_bytes_phy/tx_bytes_phy. I don't know the exact reason why but you might find the changes in rx_bytes_phy/tx_bytes_phy.

**Comment by taehyunkim1527** [comment]
@linkeal Thank you. Good luck 👍
