### ISSUE TITLE
How to wait for other nodes?

### ISSUE THREAD

**Issue by ierosodin** [uber/horovod#657]
In my case, I want to wait for all nodes finishing their works in each epoch, and then do some evaluation.
So is there any function I can use in horovod?

Now, my situation is one epoch is finished, and its evaluation result is returned, but other process is still running in the training function.

BTW, I work in pytorch, thanks.

**Comment by maxhgerlach** [comment]
I use `MPI.COMM_WORLD.barrier()` from `mpi4py`.

**Comment by ierosodin** [comment]
I go to see the code, and I found that each time when I call optimizer.step(), it would synchronize all the other node in optimizer's parameter part, and then clear the parameter dictionary!!
I'm not sure where it get that parameter dictionary back again, but in my observation, the lens of parameter dictionary is correct for only first epoch, and when code run into the second epoch, the lens become zero!!
My solution is, I just call optimizer._register_hooks() to get that parameter dictionary back after each epoch.
But I'm not sure if there are some better ways, or I want to know why it didn't get that parameter dictionary back in second epoch.

**Comment by ierosodin** [comment]
> I use `MPI.COMM_WORLD.barrier()` from `mpi4py`.

I think using barrier is a good way.

**Comment by ierosodin** [comment]
I found the problem!
Because we do some evaluation for each iter., and in that function, we have some behavior like:

```
model = model.to('cpu')
... (save the model)
model = model.to('device')
```

and this would cause backward behavior strange. (and I think in two nodes, this model would be totally different.)
After we modify this function, everything is fine. Thanks.
close issue.
