### ISSUE TITLE
Many dataset APIs have been depreciated

### ISSUE THREAD

**Issue by ghltshubh** [uber/horovod#673]
Many tensorflow APIs for downloading datasets for running horovod examples have been depreciated.
This is one of the examples: https://www.tensorflow.org/api_docs/python/tf/contrib/learn/datasets

**Comment by tgaddair** [comment]
Hey @ghltshubh, looking at the older versions of TensorFlow, it looks like `tf.estimator` has been around for some time, so I think this is a good and safe change to make.  Thanks for bringing it up!
