### ISSUE TITLE
how to install libnccl2  and libnccl2-dev on centos 

### ISSUE THREAD

**Issue by kinglion811** [uber/horovod#677]
when I build horovod images,from centos7,when I run 
yum install libcudnn7
yum install libnccl-dev
no package to install

**Comment by tgaddair** [comment]
Hey @kinglion811, I believe you'll need to join the NVIDIA develop program and install from an archive file:

https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html

https://developer.nvidia.com/cudnn

**Comment by kinglion811** [comment]
@tgaddair thanks

**Comment by tgaddair** [comment]
No problem!  Closing this for now, but feel free to reopen if any additional issues come up.
