### ISSUE TITLE
undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE

### ISSUE THREAD

**Issue by imKKK** [uber/horovod#678]
hi i am trying to tuning the deepspeech 0.3.0 model from checkpoint which i cloned it on 30.10.2018. while 
trying this command..

python DeepSpeech.py --train_files /home/userk/DeepSpeechPro/datasets/train/train.csv --dev_files /home/userk/DeepSpeechPro/datasets/dev/dev.csv --test_files /home/userk/DeepSpeechPro/datasets/test/test.csv --n_hidden 2048 --epoch -3 --export_dir /home/userk/DeepSpeechPro/tuned_model/models/ --lm_binary_path /home/userk/DeepSpeechPro/native_client/models/lm.binary --checkpoint_dir /mnt/c/users/karthikeyan/downloads/modelss/DeepSpeech/ --decoder_library_path /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so --alphabet_config_path /home/userk/DeepSpeechPro/native_client/models/alphabet.txt --lm_trie_path /home/userk/DeepSpeechPro/native_client/models/trie --learning_rate 0.0001

i am getting the below error.....

Traceback (most recent call last):
  File "DeepSpeech.py", line 1959, in <module>
    tf.app.run(main)
  File "/home/userk/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1910, in main
    initialize_globals()
  File "DeepSpeech.py", line 330, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/userk/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE

operating system : windows subsystem for linux - ubuntu
tensorflow version: 1.12.0rc2
date cloned:30.10.2018

**Comment by tgaddair** [comment]
Hey @imKKK, can you run `ldd /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so` and print the result here.

I suspect that there are missing `.so` files that need to be added to your `LD_LIBRARY_PATH` similar to #656.

**Comment by imKKK** [comment]
this is what I am getting.. @tgaddair 

        linux-vdso.so.1 =>  (0x00007fffc543a000)
        libtensorflow_framework.so => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f586f960000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f586f730000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f586f420000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f586f090000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f586ee60000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f586ea90000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f586fc00000)

I think the libtensorflow_framework.so is missing...

**Comment by imKKK** [comment]
I found the file here...

/home/userk/.local/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so

and I tried adding it to the LD_LIBRARY_PATH...

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/userk/.local/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so

when i run this..

echo $LD_LIBRARY_PATH

I am getting this..

:/home/userk/.local/lib/python2.7/site-packages/tensorflow/libtensorflow_framework.so

now running this command...

 ldd /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so 

shows the same information...

        linux-vdso.so.1 =>  (0x00007fffc4ca9000)
        libtensorflow_framework.so => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2c249f0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2c247c0000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2c244b0000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2c24120000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2c23ef0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2c23b20000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2c24e00000)

**Comment by imKKK** [comment]
I have the path to LD_LIBRARY_PATH.
now the command
        ldd /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so
shows
        linux-vdso.so.1 =>  (0x00007fffc9bd1000)
        libtensorflow_framework.so => /home/userk/.local/lib/python2.7/site- 
        packages/tensorflow/libtensorflow_framework.so (0x00007ff6bdbc0000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff6bd9b0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff6bd780000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff6bd470000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff6bd0e0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff6bceb0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff6bcae0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff6bea00000)
but the issue still persists....
Traceback (most recent call last):
  File "DeepSpeech.py", line 1959, in <module>
    tf.app.run(main)
  File "/home/userk/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1910, in main
    initialize_globals()
  File "DeepSpeech.py", line 330, in initialize_globals
    custom_op_module = tf.load_op_library(FLAGS.decoder_library_path)
  File "/home/userk/.local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/userk/DeepSpeechPro/native_client/bin/libctc_decoder_with_kenlm.so: undefined symbol: _ZN10tensorflow12OpDefBuilderC1EN4absl11string_viewE

**Comment by imKKK** [comment]
now I built a comlpete new project from the deepspeech 0.3.0 release with the respective requirements.txt packages and native_client.amd64.cpu.linux.tar.xz file from the releases. And I am getting this issue...

('Preprocessing', ['/home/userk/DeepSpeechPro/datasets/train/train.csv'])
Traceback (most recent call last):
  File "DeepSpeech.py", line 1988, in <module>
    tf.app.run(main)
  File "/home/userk/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "DeepSpeech.py", line 1944, in main
    train()
  File "DeepSpeech.py", line 1468, in train
    hdf5_cache_path=FLAGS.train_cached_features_path)
  File "/home/userk/DeepSpeechPro/DeepSpeech2/DeepSpeech-0.3.0/util/preprocess.py", line 68, in preprocess
    out_data = pmap(step_fn, source_data.iterrows())
  File "/home/userk/DeepSpeechPro/DeepSpeech2/DeepSpeech-0.3.0/util/preprocess.py", line 13, in pmap
    results = pool.map(fun, iterable)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
**AttributeError: 'Series' object has no attribute 'transcript'**

**Comment by imKKK** [comment]
@alsrgv ,the issue is solved. Its was due to the mismatch error. I was using a wrong version of tensorflow and wrong project version(master) and native_clinet binaries and corrupted CSV files. Then I followed the steps suggested by @MuruganR96 to build project and @lissyx to re validate CSV files. now The training is going on.. Thank you for your support.

**Comment by alsrgv** [comment]
@imKKK, excellent!

**Comment by dengc367** [comment]
I solve the problem following the other thread method: 
https://github.com/horovod/horovod/issues/431#issuecomment-493030517
