### ISSUE TITLE
multi-machine training hangs on.

### ISSUE THREAD

**Issue by yyht** [uber/horovod#689]
![image](https://user-images.githubusercontent.com/14133687/49687534-3a094e80-fb3f-11e8-936b-6b5214599b32.png)

It seems som connections time-out and some coneections work fine. 

Here is my trianing script in docker:
mpirun -np 8 \
 -H 192.168.3.131:4,192.168.3.133:4 \
 -mca btl_tcp_if_exclude docker0,lo,br-1ca618956367,br-224fa76e2bea,br-be5c07c9e794,br-697da8ae7b12,br-6655561aac78,br-3e45e7ddc33c,docker_gwbridge,vboxnet0,virbr0 \
 -x NCCL_SOCKET_IFNAME=^docker0,lo,br-1ca618956367,br-224fa76e2bea,br-be5c07c9e794,br-697da8ae7b12,br-6655561aac78,br-3e45e7ddc33c,docker_gwbridge,vboxnet0,virbr0 \
 -x HOROVOD_MPI_THREADS_DISABLE=1 \
 -mca plm_rsh_args "-p 12345" \
 python test_oqmrc_distributed_final.py \
 --eval_data_file "/data/xuht/wsdm19/test.csv" \
 --output_file "/data/xuht/wsdm19/interaction/dev.tfrecords" \
 --config_file "/mnt/WebotNAS/data/horovod_distributed_test/chinese_L-12_H-768_A-12/bert_config.json" \
 --init_checkpoint "/mnt/WebotNAS/data/horovod_distributed_test/chinese_L-12_H-768_A-12/bert_model.ckpt" \
 --result_file "/data/xuht/wsdm19/interaction/model_11_15/submission.csv" \
 --vocab_file "/data/xuht/bert/chinese_L-12_H-768_A-12/vocab.txt" \
 --label_id "/data/xuht/wsdm19/data/label_dict.json" \
 --train_file "/mnt/WebotNAS/data/horovod_distributed_test/oqmrc/train.tfrecords" \
 --dev_file "/mnt/WebotNAS/data/horovod_distributed_test/oqmrc/test.tfrecords" \
 --max_length 200 \
 --model_output "/mnt/WebotNAS/data/horovod_distributed_test/oqmrc/mutli_machine_test/model_11_27" \
 --gpu_id "0" \
 --epoch 5 \
 --num_classes 3 \
 --batch_size 8

**Comment by alsrgv** [comment]
I assume this is superseded by #690, will close.  Feel free to reopen if it's not the case.
