### ISSUE TITLE
Error when pip install horovod

### ISSUE THREAD

**Issue by tobyyouup** [uber/horovod#70]
After installing nccl 2.0 and mpi, I use "HOROVOD_GPU_ALLREDUCE=NCCL pip install --no-cache-dir horovod" to install horovod, but is shows error: `horovod/tensorflow/mpi_ops.cc:802:79: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]`.

The details log shows:

`Collecting horovod
  Downloading horovod-0.9.11.tar.gz (65kB)
    100% |████████████████████████████████| 71kB 271kB/s 
Installing collected packages: horovod
  Running setup.py install for horovod ... error
    Complete output from command /usr/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g7B1qn/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-raRdo5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/horovod
    copying horovod/__init__.py -> build/lib.linux-x86_64-2.7/horovod
    creating build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/__init__.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops_test.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    copying horovod/tensorflow/mpi_ops.py -> build/lib.linux-x86_64-2.7/horovod/tensorflow
    running build_ext
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -I/usr/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -L/usr/anaconda2/lib -Wl,-rpath=/usr/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/anaconda2/lib/python2.7/site-packages/tensorflow/core -L/usr/anaconda2/lib -ltensorflow_framework -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    /usr/bin/ld: cannot find -ltensorflow_framework
    collect2: error: ld returned 1 exit status
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -I/usr/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -L/usr/anaconda2/lib -Wl,-rpath=/usr/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.o -L/usr/anaconda2/lib/python2.7/site-packages/tensorflow/core -L/usr/anaconda2/lib -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_libs.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -I/usr/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.cc -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -L/usr/anaconda2/lib -Wl,-rpath=/usr/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.o -L/usr/anaconda2/lib/python2.7/site-packages/tensorflow/core -L/usr/anaconda2/lib -o build/temp.linux-x86_64-2.7/test_compile/test_tensorflow_abi.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -I/usr/local/cuda/include -I/usr/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_cuda.cc -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -L/usr/anaconda2/lib -Wl,-rpath=/usr/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_cuda.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/usr/anaconda2/lib -lcudart -o build/temp.linux-x86_64-2.7/test_compile/test_cuda.so
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -std=c++11 -I/usr/local/cuda/include -I/usr/anaconda2/include/python2.7 -c build/temp.linux-x86_64-2.7/test_compile/test_nccl.cc -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -shared -L/usr/anaconda2/lib -Wl,-rpath=/usr/anaconda2/lib,--no-as-needed build/temp.linux-x86_64-2.7/test_compile/test_nccl.o -L/usr/local/cuda/lib -L/usr/local/cuda/lib64 -L/usr/anaconda2/lib -lnccl -o build/temp.linux-x86_64-2.7/test_compile/test_nccl.so
    building 'horovod.tensorflow.mpi_lib' extension
    creating build/temp.linux-x86_64-2.7/horovod
    creating build/temp.linux-x86_64-2.7/horovod/tensorflow
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -I/usr/local/cuda/include -I/usr/anaconda2/include/python2.7 -c horovod/tensorflow/mpi_message.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_message.o -std=c++11 -fPIC -O2 -I/usr/anaconda2/include -L/usr/anaconda2/lib -Wl,-rpath -Wl,/usr/anaconda2/lib -lmpichcxx -lmpich -lopa -lmpl -lrt -lpthread -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DHAVE_CUDA=1 -DHAVE_NCCL=1 -DHOROVOD_GPU_ALLREDUCE='N' -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include -I/usr/anaconda2/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -I/usr/local/cuda/include -I/usr/anaconda2/include/python2.7 -c horovod/tensorflow/mpi_ops.cc -o build/temp.linux-x86_64-2.7/horovod/tensorflow/mpi_ops.o -std=c++11 -fPIC -O2 -I/usr/anaconda2/include -L/usr/anaconda2/lib -Wl,-rpath -Wl,/usr/anaconda2/lib -lmpichcxx -lmpich -lopa -lmpl -lrt -lpthread -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    horovod/tensorflow/mpi_ops.cc: In function ‘void horovod::tensorflow::{anonymous}::PerformOperation(horovod::tensorflow::{anonymous}::TensorTable&, horovod::tensorflow::MPIResponse)’:
    horovod/tensorflow/mpi_ops.cc:802:79: # error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
                                      recvcounts, displcmnts, dtype, MPI_COMM_WORLD);
                                                                                   ^
    In file included from horovod/tensorflow/mpi_ops.cc:38:0:
    /usr/anaconda2/include/mpi.h:633:5: error:   initializing argument 1 of ‘int MPI_Allgatherv(void*, int, MPI_Datatype, void*, int*, int*, MPI_Datatype, MPI_Comm)’ [-fpermissive]
     int MPI_Allgatherv(void* , int, MPI_Datatype, void*, int *, int *, MPI_Datatype, MPI_Comm);
         ^
    horovod/tensorflow/mpi_ops.cc:1102:45: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
                                   MPI_COMM_WORLD))
                                                 ^
    horovod/tensorflow/mpi_ops.cc:534:24: note: in definition of macro ‘MPI_CHECK’
         auto mpi_result = (op);                                                    \
                            ^
    In file included from horovod/tensorflow/mpi_ops.cc:38:0:
    /usr/anaconda2/include/mpi.h:639:5: error:   initializing argument 1 of ‘int MPI_Allreduce(void*, void*, int, MPI_Datatype, MPI_Op, MPI_Comm)’ [-fpermissive]
     int MPI_Allreduce(void* , void*, int, MPI_Datatype, MPI_Op, MPI_Comm);
         ^
    horovod/tensorflow/mpi_ops.cc: In function ‘void horovod::tensorflow::{anonymous}::BackgroundThreadLoop(horovod::tensorflow::{anonymous}::HorovodGlobalState&)’:
    horovod/tensorflow/mpi_ops.cc:1261:39: error: ‘MPI_COMM_TYPE_SHARED’ was not declared in this scope
       MPI_Comm_split_type(MPI_COMM_WORLD, MPI_COMM_TYPE_SHARED, 0, MPI_INFO_NULL,
                                           ^
    horovod/tensorflow/mpi_ops.cc:1262:34: error: ‘MPI_Comm_split_type’ was not declared in this scope
                           &local_comm);
                                      ^
    horovod/tensorflow/mpi_ops.cc:1324:40: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
             MPI_Send(encoded_message.c_str(), (int)encoded_message.length() + 1,
                                            ^
    In file included from horovod/tensorflow/mpi_ops.cc:38:0:
    /usr/anaconda2/include/mpi.h:569:5: error:   initializing argument 1 of ‘int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm)’ [-fpermissive]
     int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm);
         ^
    horovod/tensorflow/mpi_ops.cc:1425:43: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
               MPI_Send(encoded_response.c_str(), (int)encoded_response.length() + 1,
                                               ^
    In file included from horovod/tensorflow/mpi_ops.cc:38:0:
    /usr/anaconda2/include/mpi.h:569:5: error:   initializing argument 1 of ‘int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm)’ [-fpermissive]
     int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm);
         ^
    horovod/tensorflow/mpi_ops.cc:1442:41: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
             MPI_Send(encoded_response.c_str(), (int)encoded_response.length() + 1,
                                             ^
    In file included from horovod/tensorflow/mpi_ops.cc:38:0:
    /usr/anaconda2/include/mpi.h:569:5: error:   initializing argument 1 of ‘int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm)’ [-fpermissive]
     int MPI_Send(void*, int, MPI_Datatype, int, int, MPI_Comm);
         ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-g7B1qn/horovod/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-raRdo5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-g7B1qn/horovod/`

This system is Ubuntu 14.04, python 2.7.6. CUDA 8.0 and CuDNN 6, Tensorflow 1.3.0. Can you help to figure out where is the problem?

**Comment by alsrgv** [comment]
@tobyyouup,

Can you update Open MPI to a more recent version? We recommend Open MPI 3.0.0.

```bash
$ sudo apt remove openmpi
$ <install fresh Open MPI>
```

See Open MPI installation instruction [here](https://www.open-mpi.org/faq/?category=building#easy-build).

**Comment by tobyyouup** [comment]
@alsrgv  I remove and reinstall open mpi with 3.0.0, but it still shows the same error. So is there something else that can fix this?

**Comment by alsrgv** [comment]
@tobyyouup, after reinstalling Open MPI, can you reinstall Horovod as well?

**Comment by tobyyouup** [comment]
@alsrgv   I finally uninstall mpich, then the system can find openmpi, and horovod can install successfully.

**Comment by nischalhp** [comment]
I followed the following steps to install horovod and it worked perfectly. 

1. Installing openMPI with apt-get
2. Installing tensorflow in the virtualenv with pip
3. Installing horovod with pip

**Comment by alsrgv** [comment]
Documentation has been updated, closing this issue.

**Comment by GabrielLin** [comment]
I am facing the same issue in the latest version.

**Comment by alsrgv** [comment]
@GabrielLin, could you open a new issue and share the installation log that shows the error you're seeing?

**Comment by GabrielLin** [comment]
@alsrgv . My log is almost the same. I fix this issue by installing OpenMPI by conda.
`conda install -c conda-forge mpi4py=3.0.0`

If I follow the instruction of OpenMPI website to install OpenMPI, then install mpi4py by pip. No matter which version, it always fails.

**Comment by alsrgv** [comment]
@GabrielLin, if you haven't resolved this yet, could you open new issue?

**Comment by GabrielLin** [comment]
@alsrgv Sorry for the late reply. I missed the notification. My solution is to install OpenMPI by conda. After that, I have not tried to install OpenMPI from its source code.

**Comment by kalyc** [comment]
What version of OpenMPI are you using with Conda @GabrielLin

**Comment by GabrielLin** [comment]
Here is the log when I ran `conda install -c conda-forge mpi4py=3.0.0`
```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /opt/miniconda2

  added / updated specs:
    - mpi4py=3.0.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpi-1.0                    |            mpich           4 KB  conda-forge
    mpi4py-3.0.0               |py27hf046da1_1005         651 KB  conda-forge
    mpich-3.2.1                |       h26a2512_7         5.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         6.0 MB

The following NEW packages will be INSTALLED:

  libgfortran        conda-forge/linux-64::libgfortran-3.0.0-1
  mpi                conda-forge/linux-64::mpi-1.0-mpich
  mpi4py             conda-forge/linux-64::mpi4py-3.0.0-py27hf046da1_1005
  mpich              conda-forge/linux-64::mpich-3.2.1-h26a2512_7
```

**Comment by shailensobhee** [comment]
> @alsrgv . My log is almost the same. I fix this issue by installing OpenMPI by conda.
> `conda install -c conda-forge mpi4py=3.0.0`
> 
> If I follow the instruction of OpenMPI website to install OpenMPI, then install mpi4py by pip. No matter which version, it always fails.

That did not work for me. CentOS 8, gcc8.3.1

**Comment by tgaddair** [comment]
Hey @shailensobhee, if you're using Conda, please take a look at the docs [here](https://github.com/horovod/horovod/blob/master/docs/conda.rst).

Also, be aware that Horovod no longer requires MPI to run.

If you have further issues, please feel free to open a new issue.

**Comment by shailensobhee** [comment]
> Hey @shailensobhee, if you're using Conda, please take a look at the docs [here](https://github.com/horovod/horovod/blob/master/docs/conda.rst).
> 
> Also, be aware that Horovod no longer requires MPI to run.
> 
> If you have further issues, please feel free to open a new issue.

I am using conda but I am using CPU-based nodes. The docs you referred is GPU related. Just a quick question, have you tried on a fresh machine the following:
- Install CentOS 8 (comes with gcc 8.3.1 on higher) on a fresh machine that has no GPUs (let's say a server machine)
- Create a fresh conda environment
- conda install the basic necessary packages, like Tensorflow, etc
- `pip install horovod`

Does it work? I can try this a thousand times and I can always reproduce failures getting Horovod to install properly. What am I missing here?
