### ISSUE TITLE
Example to dynamically spawn processes?

### ISSUE THREAD

**Issue by YeYuanS** [uber/horovod#710]
Hi team,
I have a 4 GPU instances and runs your examples using command like
`mpirun -np 4 -H localhost:4 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python  keras_mnist.py` perfectly.
However, I only want part of my code to run with Horovod. Is it something like the following? 
`# code without Horovod begins`
 ` #code without Horovod ends`
` import horovod.tensorflow as hvd `
 ` from mpi4py import MPI`
`MPI.COMM_SELF.Spawn(sys.executable, maxprocs=4)`
`hvd.init()`
`...`
`MPI.disconnect()`

**Comment by UditGupta10** [comment]
You can instantiate horovod in the beginning, run the 'code without horovod' on rank 0, put a barrier, then run code with horovod across 4 gpus

**Comment by YeYuanS** [comment]
> You can instantiate horovod in the beginning, run the 'code without horovod' on rank 0, put a barrier, then run code with horovod across 4 gpus

Thank you for the reply! I'm really a new bee for multiple GPUs. May I ask how can I run code with specific rank. Is there an example about it?

**Comment by UditGupta10** [comment]
if hvd.rank()==0:
    Single node code
else:
    pass
hvd.allreduce([0]) # this is used as barrier, check the usage once.
multigpu code.

**Comment by YeYuanS** [comment]
> if hvd.rank()==0:
> Single node code
> else:
> pass
> hvd.allreduce([0]) # this is used as barrier, check the usage once.
> multigpu code.

Awesome! Actually it's company's code base, so it seems not good to add some code in the beginning... Lol

**Comment by tgaddair** [comment]
Hey @YeYuanS, did @UditGupta10's solution work for you, or do you need something that doesn't modify the existing training script?

**Comment by YeYuanS** [comment]
> Hey @YeYuanS, did @UditGupta10's solution work for you, or do you need something that doesn't modify the existing training script?

It works but not elegant for production code I think... I would be very appreciated if you could provide solution that doesn't modify the existing training script.

**Comment by YeYuanS** [comment]
@UditGupta10 @tgaddair I noticed that if I put the barrier like hvd.allreduce([0]), it would cause memory leak for other gpus, do you have any idea about it?
