### ISSUE TITLE
where can I find compilation instruction for horovod？

### ISSUE THREAD

**Issue by scotthuang1989** [uber/horovod#714]
I want to build horovod from source code, where I can find the build instruction?
 I see there are some cpp files and I don't see any makefiles. I am not a professional cpp programmer, any instruction would be very helpful.

**Comment by scotthuang1989** [comment]
@tgaddair  thanks. I will try that. for now, I have met some isssues:
1. I can't find /usr/local/nccl, I install nccl with following command

> sudo dpkg -i nccl-repo-ubuntu1604-2.2.12-ga-cuda9.0_1-1_amd64.deb
> sudo apt update
> sudo apt install libnccl2 libnccl-dev

2. Whilch am figure out issue 1, I just compile it with this command:

> python setup.py install

then I got a dependency error, after I figure it out, I will get it back to you to see if it is error of my development enviroment, or horovod should add more dependency into setup.py

**Comment by alsrgv** [comment]
@scotthuang1989, if you install from deb package, you don't need to specify `HOROVOD_NCCL_HOME` - it will be in the system path.

**Comment by scotthuang1989** [comment]
@tgaddair sorry for the late response, I was working on other project.

I got an error:

> horovod/common/optim/bayesian_optimization.cc:24:10: fatal error: LBFGS.h: No such file or directory

in the source code this header file is include like this: 

> #include "LBFGS.h"
so it should be project directory of horovod. but I can't find it in horovod source code.

the commit id of source code  is: af0153c72ff9ecd34db7db1d6c984cac44646bd0

**Comment by scotthuang1989** [comment]
@alsrgv @tgaddair  I built it successfully.  I forget clone recursively to get third party libs at first time.  after I clone everything, no errors.
