### ISSUE TITLE
run distributed  tensorflow_mnist.py on kubernetes, got  "TCP connection request " error

### ISSUE THREAD

**Issue by xuerq** [uber/horovod#72]
Command :
```shell
mpirun -np 2 \ 
        -x LD_LIBRARY_PATH \
        -H xuerq-horovod0:1,xuerq-horovod1:1 python tensorflow_mnist.py
```
Error log :
```shell
--------------------------------------------------------------------------
Open MPI detected an inbound MPI TCP connection request from a peer
that appears to be part of this MPI job (i.e., it identified itself as
part of this Open MPI job), but it is from an IP address that is
unexpected.  This is highly unusual.

The inbound connection has been dropped, and the peer should simply
try again with a different IP interface (i.e., the job should
hopefully be able to continue).

  Local host:          xuerq-horovod0
  Local PID:           8136
  Peer hostname:       xuerq-horovod1 ([[30832,1],1])
  Source IP of socket: 10.10.10.8
  Known IPs of peer:   
	10.1.102.5
--------------------------------------------------------------------------
[xuerq-horovod0:08130] 1 more process has sent help message help-mpi-btl-tcp.txt / dropped inbound connection
[xuerq-horovod0:08130] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
But the following commands is ok
```shell
mpirun -np 1 \ 
        -x LD_LIBRARY_PATH \
        -H xuerq-horovod0:1 python tensorflow_mnist.py

mpirun -np 1 \ 
        -x LD_LIBRARY_PATH \
        -H xuerq-horovod1:1 python tensorflow_mnist.py
```

**Comment by alsrgv** [comment]
@xuerq, seems that you have multiple network interfaces. Can you show an output of `ifconfig` on both machines?

**Comment by ydp** [comment]
you may need to use host network for pod, specify eth0.

```
mpirun --allow-run-as-root --mca oob_tcp_if_include eth0 --mca btl_tcp_if_include eth0 -np 2 -x NCCL_SOCKET_IFNAME=eth0 -x NCCL_DEBUG -H hvd-0:1,hvd-1:1  python tensorflow_mnist.py
```
refer my issue #57

**Comment by pineking** [comment]
@ydp If the Pod network set to host network mode, does it mean there only one pod is working on each k8s node?

**Comment by xuerq** [comment]
@ydp  Thanks for your ideas , ”host network for pod“ solve my problem
@alsrgv  Thanks for your great job , the benchmark I got :
- 417.74 images/sec for 4 GPUs on 2 nodes
- 117.61 images/sec for 1 GPU on 1 nodes  

much faster than tensorflow' implementation, and is more convenient to be used than https://github.com/baidu-research/tensorflow-allreduce
```shell
mpirun -np 4 \ 
    -mca btl_tcp_if_include ens4d1 -x NCCL_SOCKET_IFNAME=ens4d1 \
    -x LD_LIBRARY_PATH \
    -H host0:2,host1:2 \
    python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --horovod_device gpu
```

**Comment by alsrgv** [comment]
@xuerq, congrats!  88.8% scaling, that's pretty good.

**Comment by alsrgv** [comment]
Closing this issue. Feel free to reopen if you have more questions.

**Comment by ydp** [comment]
@kinglion811  I am not sure, in my case need to read samples from hdfs, flannel would slow down IO process very much

**Comment by kinglion811** [comment]
@xuerq  I run horovod on kubernetes,the network is host ,but when I run tensorflow_word2vec,the error is 
![image](https://user-images.githubusercontent.com/6119243/42555233-27adaf06-851a-11e8-816b-4c0045659d07.png)
I think,the mpi use the physical machine's orted,not the container

**Comment by kinglion811** [comment]
@xuerq I run horovod on kubernetes,the network is host ,but when I run tensorflow_word2vec,the error is

mpirun -np 4 -mca btl_tcp_if_include eth02 -x  NCCL_SOCKET_IFNAME=eth02 -H h1:1,h2:1,h3:1,h4:1 --allow-run-as-root python3.5 tensorflow_word2vec.py

bash: /usr/local/bin/orted: No such file or directory
bash: /usr/local/bin/orted: No such file or directory
bash: /usr/local/bin/orted: No such file or directory

I think,the mpi use the physical machine's orted,not the container,how to avoid?
