### ISSUE TITLE
question about Queue on horovod timeline

### ISSUE THREAD

**Issue by ustcyue** [uber/horovod#743]
I run the tensorflow_synthetic_benchmark.py using VGG16 on two machines, each using 4 1080Ti card. and the output of one training step looks like this, and seems most time is spend on waiting NCCL to finish previous communication. But I checked the bandwidth is only around 600MB/s to 800MB/s,  which is less than half of the network bandwidth(2*10Gbps). 

Is this timeline normal for my setup and is there anything I can do to improve it ?

![image](https://user-images.githubusercontent.com/2103334/50893597-2ef65680-143c-11e9-9ef8-5c408bb8431c.png)

**Comment by alsrgv** [comment]
@ustcyue, can you share the log of NCCL messages during the run (use `NCCL_DEBUG=INFO`) and the output of `ifconfig` for us to understand the context better?

**Comment by ustcyue** [comment]
@alsrgv these info looks normal, I am running on a k8s cluster. Somehow after I set NCCL_MIN_NRINGS to 4, it is much faster. I remember that you mentioned using multiple rings will help with many nodes. I am surprised it make such a big difference on two nodes.

**Comment by alsrgv** [comment]
@ustcyue, I'd need to see the NCCL and ifconfig output to provide further feedback.

**Comment by ustcyue** [comment]
@alsrgv Thanks for your help, I am going to close the issue since network is no longer the issue for us now.
