### ISSUE TITLE
Extreme Performance Decrease when scaling with multiple machines

### ISSUE THREAD

**Issue by mr-ubik** [uber/horovod#752]
Having cloned the repository and run the `build-docker-images.sh` script I proceeded to run both PyTorch and TensorFlow synthetic benchmarks. 

On a dual 1080 Ti machine I obtain circa 171 img/sec GPU.

If I try and distribute the workload using an identical machine (following the "Running with Docker example") suddenly the computation becomes 10x slower.

Is this related to #221?

**Comment by alsrgv** [comment]
@mr-ubik, if I understand correctly, once you run Horovod across two machines using Docker, performance drops by 10x?  Can you tell us more about your network setup?

**Comment by mr-ubik** [comment]
Yes, the same 10x drop happens both when using Docker and manual installation. By the looks of it, it is probably due to our network being a normal 1GbE.

**Comment by mr-ubik** [comment]
Closing the issue for now.
