### ISSUE TITLE
TypeError: DistributedOptimizer() got an unexpected keyword argument 'backward_passesper_step

### ISSUE THREAD

**Issue by lakshmiumenon** [uber/horovod#774]
Getting the following  error while running pytorch_imagenet_resnet50.py

File "pytorch_imagenet_resnet50.py", line 143, in <module>
    backward_passesper_step=args.batches_per_allreduce)
TypeError: DistributedOptimizer() got an unexpected keyword argument 'backward_passesper_step'

**Comment by tgaddair** [comment]
Hey @lakshmiumenon, the parameter should be `backward_passes_per_step` with an additional underscore.  That's one possible cause of this error (assuming that wasn't just a transcription error).

That parameter was added very recently, and those changes haven't yet been packaged into a release yet, so it's possible that your installed version of Horovod is behind the version of the examples you're using.  

I'd suggest checking out the version of the examples that is the same as your version of Horovod.  For example, if you installed Horovod `v0.15.2`, then you could checkout that tag in your examples repo: `git checkout v0.15.2`.

**Comment by lakshmiumenon** [comment]
> Hey @lakshmiumenon, the parameter should be `backward_passes_per_step` with an additional underscore. That's one possible cause of this error (assuming that wasn't just a transcription error).
> 
> That parameter was added very recently, and those changes haven't yet been packaged into a release yet, so it's possible that your installed version of Horovod is behind the version of the examples you're using.
> 
> I'd suggest checking out the version of the examples that is the same as your version of Horovod. For example, if you installed Horovod `v0.15.2`, then you could checkout that tag in your examples repo: `git checkout v0.15.2`.

Thank you...
