### ISSUE TITLE
training GANs with Horovod

### ISSUE THREAD

**Issue by LeanderK** [uber/horovod#799]
Hi, I want to train a GAN using horovod and I wonder whether I can just get different step-counters for the discriminator and generator optimizers (I am using different numbers of steps).

My code is (essentially, i can't copy the code since I need to type this on another computer):

```python
gen_step = tf.tf.train.get_or_create_global_step()
disc_step = tf.variable(0)
tf.add_to_collection(tf.GraphKeys.GlobalVariables, disc_step)

session.run(hvd.broadcast_global_variables(0))

for epoch in range(epochs):
    for (idx, batch_img) in enumerate(self.train_batces):
         for _ in range(n_dics):
               (...)
               disc_optimizer.minimize(x,globalstep = disc_step)
         gen_optimizer.minimize(y,globalstep = gen_step)
```

Since I am still not sure how exactly horovod works, I raise this issue to ask whether the approach is ok or whether it will blow up later (I am still migrating to horovod 😉)

**Comment by alsrgv** [comment]
@LeanderK, I believe it should just work - but please let us know if it does not!

**Comment by LeanderK** [comment]
seems to work so far, thanks!
