### ISSUE TITLE
Implement allgather/allreduce for numpy arrays

### ISSUE THREAD

**Issue by LeanderK** [uber/horovod#806]
When working with more complex models and evaluations, it happens that I want to gather or reduce numpy arrays (for example when sklearn provides critical functionality). It would be great if there would be a simple way to gather and reduce numpy arrays, without going through tensorflow.

**Comment by alsrgv** [comment]
@LeanderK, we recommend using `mpi4py` for this.  [mpi4py](https://github.com/uber/horovod#mpi4py) coexists with Horovod very nicely.

**Comment by LeanderK** [comment]
ok, thansk!
