### ISSUE TITLE
Add tags to commits corresponding to pypi uploads.

### ISSUE THREAD

**Issue by TimZaman** [uber/horovod#81]
Hey Alex! Thanks for adding the `__version__`!. Would you mind adding tags to the corresponding commits?

**Comment by alsrgv** [comment]
@TimZaman, the tags [here](https://github.com/uber/horovod/releases) correspond to versions on pypi. Does that answer your question?

**Comment by TimZaman** [comment]
Whoops! Missed the `tags` tab!
