### ISSUE TITLE
Long time cost for Logging hook

### ISSUE THREAD

**Issue by weixsong** [uber/horovod#92]
Hi,

I found that the logging time cost is very high:
```
	Line 90303: INFO:tensorflow:loss = 4.74907, step = 5201 (1185.455 sec)
	Line 90304: INFO:tensorflow:loss = 4.74907, step = 5201 (1185.455 sec)
	Line 90306: INFO:tensorflow:loss = 5.53061, step = 5201 (1185.460 sec)
	Line 90307: INFO:tensorflow:loss = 5.53061, step = 5201 (1185.460 sec)
```

```python
    # BroadcastGlobalVariablesHook broadcasts variables from rank 0 to all other
    # processes during initialization.
    hooks = [hvd.BroadcastGlobalVariablesHook(0),
             tf.train.StopAtStepHook(last_step=8000000),
             tf.train.LoggingTensorHook(tensors={'step': global_step, 'loss': loss},
                                        every_n_iter=200),
            ]
```

Is there anything wrong for my code?

**Comment by alsrgv** [comment]
@weixsong, you should divide number of seconds by number of iterations. This means that every batch takes `1185.455 / 200 = 5.927275 sec/iter`.  What GPU utilization do you see in `nvidia-smi`?

**Comment by weixsong** [comment]
@alsrgv , got it.

Then the time cost make sense. I'm using a platform, could not get nvidia-smi info.
But my network is very big, according to my experience, the GPU utilization should be 100%.
