### ISSUE TITLE
Is Horovod support multiple Node and multiple GPU for each Node?

### ISSUE THREAD

**Issue by weixsong** [uber/horovod#93]
Hi,

I'd like to use Horovod with more than one node, and each node contains multiple GPU, such as 8 GPU each node.

Could me programming in each node the same way as gradient average TF code, and then use Horovod to do distributed gradient update?

**Comment by alsrgv** [comment]
@weixsong, it is absolutely supported. The idea is to code a single-GPU training script and let MPI run a copy of the script per GPU.  See [Running Horovod](https://github.com/uber/horovod/blob/master/docs/running.md) page for details on how to run multiple processes per node - most of examples use 4 GPUs per server.

**Comment by weixsong** [comment]
@alsrgv, thanks.

**Comment by ziyangli** [comment]
I don't see why this question is marked as solved. In fact I have similar requirements. That is my single training script will use all 8 GPUs on one server. Is it possible for me to use horovod to extend this to more than one servers?

**Comment by ziyangli** [comment]
I think I didn't make myself clear, but I find answer to my question from this issue. https://github.com/uber/horovod/issues/102

**Comment by surak** [comment]
Broken link

**Comment by tgaddair** [comment]
@surak here is the updated location: https://github.com/horovod/horovod/blob/master/docs/running.rst

**Comment by surak** [comment]
Thanks! I know, I just wanted to point out for other people who come here. Perhaps edit the original answer?

**Comment by tgaddair** [comment]
Sure, fixed!
