### ISSUE TITLE
Error at Create Session

### ISSUE THREAD

**Issue by weixsong** [uber/horovod#94]
Hi,

Sometimes I got this Error:
```
==================================
2017-11-15 01:21:03.972724: E tensorflow/core/common_runtime/direct_session.cc:138] Invalid argument: 'visible_device_list' listed an invalid GPU id '6' but visible device count is 1
Traceback (most recent call last):
  File "/tmp/apprunner/.working/runtime/app/train.py", line 455, in <module>
    main()
  File "/tmp/apprunner/.working/runtime/app/train.py", line 403, in main
    checkpoint_dir=work_path) as sess:
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 352, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 648, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 477, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 822, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 827, in _create_session
    return self._sess_creator.create_session()
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 538, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 412, in create_session
    init_fn=self._scaffold.init_fn)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py", line 178, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1292, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 562, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
ERROR:tensorflow:==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):
<tf.Tensor 'report_uninitialized_variables_1/boolean_mask/Gather:0' shape=(?,) dtype=string>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
['File "/tmp/apprunner/.working/runtime/app/train.py", line 455, in <module>\n    main()', 'File "/tmp/apprunner/.working/runtime/app/train.py", line 403, in main\n    checkpoint_dir=work_path) as sess:', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 352, in MonitoredTrainingSession\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 648, in __init__\n    stop_grace_period_secs=stop_grace_period_secs)', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 477, in __init__\n    self._sess = _RecoverableSession(self._coordinated_creator)', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 822, in __init__\n    _WrappedSession.__init__(self, self._create_session())', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 827, in _create_session\n    return self._sess_creator.create_session()', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 538, in create_session\n    self.tf_sess = self._session_creator.create_session()', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 403, in create_session\n    self._scaffold.finalize()', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 192, in finalize\n    default_ready_for_local_init_op)', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 254, in get_or_default\n    op = default_constructor()', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py", line 189, in default_ready_for_local_init_op\n    variables.global_variables())', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 170, in wrapped\n    return _add_should_use_warning(fn(*args, **kwargs))', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 139, in _add_should_use_warning\n    wrapped = TFShouldUseWarningWrapper(x)', 'File "/tmp/apprunner/.working/runtime/python/lib/python3.5/site-packages/tensorflow/python/util/tf_should_use.py", line 96, in __init__\n    stack = [s.strip() for s in traceback.format_stack()]']
==================================
```

Then my job will run into endless waiting for other sessions:
```
WARNING: One or more tensors were submitted to be reduced....
```

**Comment by alsrgv** [comment]
@weixsong, you shouldn't run more workers on the machine than you have GPUs on that machine. See [Running Horovod](https://github.com/uber/horovod/blob/master/docs/running.md) page for examples, and this [thread](https://github.com/uber/horovod/issues/86#issuecomment-343719006) for similar issue.

**Comment by alsrgv** [comment]
@weixsong, I also found an issue with Open MPI 3.0.0 that makes it behave weird with mixed NUMA configurations, so I'm in process of updating the running instructions to these:

```bash
  $ mpirun -np 16 \
      -H server1:4,server2:4,server3:4,server4:4 \
      -bind-to none -map-by slot \
      -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH \
      python train.py
  ```

Basically, the idea is to replace `-oversubscribe` with `-map-by slot`.

Could you give this new command a shot?

**Comment by weixsong** [comment]
@alsrgv , actually I use 16 GPU, and each node contains 8 GPU, so I think the workers on each machine is no more than the GPUs I have on that machine. But still has the "create session failed" issue.

I'm using a platform, and I see the platform seed a mpirun command contains "--npernode 8", does it make sense?

**Comment by alsrgv** [comment]
@weixsong, I see. Do you have `CUDA_VISIBLE_DEVICES` set anywhere? If so, can you unset it?

**Comment by weixsong** [comment]
@alsrgv , Yes, I have. 
I think this is the root cause of this "create session failure" issue. 
In the platform, each GPU card is set to a GPU by CUDA_VISIBLE_DEVICES 
such as:
worker_0: envs={'CUDA_VISIBLE_DEVICES': '0'}
worker_1: envs={'CUDA_VISIBLE_DEVICES': '1'}
worker_5: envs={'CUDA_VISIBLE_DEVICES': '5'}
...

I will contact the platform owner and try your suggestion.

Really thank you very very much. :)

Regards,
Wei

**Comment by shaunstoltz** [comment]
This seems to be a wide spread problem, have tried on two machines, and just keep on getting this error when trying accross more than one machine.

**Comment by alsrgv** [comment]
@shahzadlone, could you open a new issue and share the exact output you're seeing?

**Comment by shaunstoltz** [comment]
Moving on for now, to frustrated. Ray seems to be much more usable.

**Comment by ssstuvz** [comment]
If I unset CUDA_VISIBLE_DEVICES the code can't find any devices...

**Comment by ssstuvz** [comment]
Now I get 'tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '4' but visible device count is 4' :)

Here is the SLURM script:
#!/bin/bash -l
#SBATCH -J horovod
#SBATCH -N 2
#SBATCH -n 8
#SBATCH --gres=gpu:4
#SBATCH --time=1-0:0:0
#SBATCH -p all

module load gpu/cuda-9.0
module load mpi/openmpi-3.1.2
module load python/python-3.6.8

cd /trinity/home/s.rykovanov/horovod/examples
export -n CUDA_VISIBLE_DEVICES

mpirun -np 8 -bind-to none -map-by slot -x HOROVOD_MPI_THREADS_DISABLE=1 -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH -mca pml ob1 /trinity/shared/opt/python-3.6.8/bin/python3.6 tensorflow_synthetic_benchmark.py

**Comment by alwaysandeep** [comment]
@ssstuvz I am facing the same error :"tensorflow.python.framework.errors_impl.InvalidArgumentError: 'visible_device_list' listed an invalid GPU id '1' but visible device count is 1" right now when trying to run on multi-node cluster. Were you able to figure out the fix/cause?
P.S. I did not face any trouble running the same script on single machine.

**Comment by alsrgv** [comment]
@alwaysandeep, what's the content of the `hosts` file?  This error means that MPI is trying to launch two processes on a single node.  This may be caused by a malformed hosts file.

**Comment by alwaysandeep** [comment]
@alsrgv  hosts file had the below data(both ips can ssh each other)
X.X.X.X. slots=8
localhost slots=8
I was able to later successfully do the training in the cluster after adding the below 2 arguments in the openmpi command. I am yet to completely understand under-the-hood working of this, what do you think happened?
-x NCCL_SOCKET_IFNAME=ens3 -mca btl_tcp_if_exclude lo,docker0

**Comment by alsrgv** [comment]
@alwaysandeep, you should make `slots=1`, which would restrict MPI to a single process per node, equivalent to your number of GPUs.

**Comment by alwaysandeep** [comment]
@alsrgv  I am sorry, it was typo earlier, I entered slots=1 itself and got the error. Editing the above comment. Sorry for the confusion. Any idea why its happening?

**Comment by alsrgv** [comment]
@alwaysandeep, can you remove `localhost` and make both entries IP addresses of the servers?
