### ISSUE TITLE
Horovod Keras vs Horovod Tensorflow

### ISSUE THREAD

**Issue by SrivastavaKshitij** [uber/horovod#97]
Hi there 

I have installed horovod on a cluster and I am trying to run the code provided under the examples section. 
when I am trying to run keras_mnist.py , I get the following error : 

```
ModuleNotFoundError: No module named 'horovod.keras'
```

On the other hand, when I am trying to run tensorflow_mnist.py, I get the following error:

```
Traceback (most recent call last):
 File "hvd_tf.py", line 18, in <module>
   import horovod.tensorflow as hvd
 File "/lustre/atlas/proj-shared/csc264/anaconda3/envs/ftensorflowFF1/lib/python3.6/site-packages/horovod/tensorflow/__init__.py", line 34, in <module>
   from horovod.tensorflow.mpi_ops import size
 File "/lustre/atlas/proj-shared/csc264/anaconda3/envs/ftensorflowFF1/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 74, in <module>
   ['HorovodAllgather', 'HorovodAllreduce'])
 File "/lustre/atlas/proj-shared/csc264/anaconda3/envs/ftensorflowFF1/lib/python3.6/site-packages/horovod/tensorflow/mpi_ops.py", line 56, in _load_library
   library = load_library.load_op_library(filename)
 File "/lustre/atlas/proj-shared/csc264/anaconda3/envs/ftensorflowFF1/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
   None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lustre/atlas/proj-shared/csc264/anaconda3/envs/ftensorflowFF1/lib/python3.6/site-packages/horovod/tensorflow/mpi_lib.cpython-36m-powerpc64le-linux-gnu.so)
```

My question is : Is there any separate installation for horovod.keras and horovod.tensorflow ?
Also, any help in resolving the above error will be deeply appreciated.

**Comment by alsrgv** [comment]
@SrivastavaKshitij, can you try to upgrade Horovod to 0.11.0?  Make sure you install it on the same set of machines that you will use it on since it does compile a bit of native code.

**Comment by chandangm** [comment]
@alsrgv, facing the same issue . upgrading horovod to 0.11.0 didn't work . 
But from python interpreter i can import the line that's throwing the error , if you run the same thing from mpirun command it throws an error 
`Traceback (most recent call last):
  File "horovod.py", line 18, in <module>
    import horovod.tensorflow as hvd
  File "/home/chandangm/PycharmProjects/learning/horovod.py", line 18, in <module>
    import horovod.tensorflow as hvd
ModuleNotFoundError: No module named 'horovod.tensorflow'; 'horovod' is not a package
`
![screenshot from 2017-11-19 09-59-59](https://user-images.githubusercontent.com/25385631/32987389-7725e30e-cd10-11e7-9fe6-0888d78aece8.png)
Any help is appreciated .

**Comment by alsrgv** [comment]
@chandangm, I think in your case it doesn't like that you named your program `horovod.py`. Can you rename it and give it another shot?

**Comment by SrivastavaKshitij** [comment]
@alsrgv : Hi sorry for the late reply. I am asking cluster admin to install the latest version. I will let you know once its done. I will get back to you ASAP. Thanks again!

**Comment by SrivastavaKshitij** [comment]
Horovod works completely fine. I created a virtual conda environment on the cluster and it works.
